local GlobalAddonName, E = ... -- ns
----------------------------------------------------------------
E.MainAddonName = GlobalAddonName
OctoEngine = E -- в других аддонах
----------------------------------------------------------------
E.OctoTables_Vibor = {}
E.ALL_Currencies = {}
E.ALL_Items = {}
E.ALL_Reputations = {}
E.ALL_UniversalQuests = {}
E.ALL_Additionally = {}
E.ALL_Quests = {}
E.First_Option = {}
E.Second_Option = {}
E.ActiveHoliday = {}
E.Fourth_Option = {}
E.Holiday = {}
E.KeyStoneTBL = {}
E.Modules = {}
E.OctoTable_Expansions = {}
E.OctoTable_Frames = {}
E.OctoTable_itemID_ALL = {}
E.OctoTable_itemID_AutoOpen = {}
E.OctoTable_itemID_Cataloged_Research = {}
E.OctoTable_itemID_Ignore_List = {}
E.OctoTable_itemID_ItemsDelete = {}
E.OctoTable_itemID_ItemsUsable = {}
E.OctoTable_itemID_ItemsUsable_Other = {}
E.OctoTable_itemID_MECHAGON = {}
E.OctoTable_KeystoneAbbr = {}
E.OctoTable_LFGDungeons = {}
E.OctoTable_Mounts = {}
E.OctoTable_Portals = {}
E.OctoTable_QuestID = {}
E.OctoTable_QuestID_Paragon = {}
E.OctoTable_RemixInfinityResearch = {}
E.OctoTable_SavedVariables = {}
E.OctoTables_DataOtrisovka = {}
E.Octo_ProfessionsskillLine = {}
E.Octo_ProfessionsskillLine_Other = {}
E.Third_Option = {}
E.Timers = {}
E.OctoTable_ALL_Mounts = {}
E.Components = {}
E.OctoTable_CurrencyMountForFuncCurName = {}
E._spamLocks = {}
E._inCombats = {}
E._callAfterTimer = {}
E.minValue_ItemLevel = 0
E.maxValue_ItemLevel = 0
E.minValue_Money = 0
E.maxValue_Money = 0
E.REPUTATION_ALPHA = .3 -- Octo_ToDo_DB_Vars.Config_REPUTATION_ALPHA
E.CHARACTER_ALPHA = .2 -- Octo_ToDo_DB_Vars.Config_CHARACTER_ALPHA
E.MAINBACKGROUND_ALPHA = .8 -- Octo_ToDo_DB_Vars.Config_MAINBACKGROUND_ALPHA
E.MOVINGBACKGROUND_ALPHA = 1 -- Octo_ToDo_DB_Vars.Config_ExtraBackgroundFadeWhenMoving

E.DataProvider_Otrisovka = {}

E.CurrentProfile = "Default" -- profileName