local GlobalAddonName, E = ...
local AddonTitle = C_AddOns.GetAddOnMetadata(GlobalAddonName, "Title")
--------------------------------------------------------------------------------
local AL3 = LibStub("AceLocale-3.0")
local debug = false
local L = AL3:NewLocale("OctoTODO", "enUS", true, debug)
if L then
	L["Abandon All Quests"] = true
	L["Abandon: "] = true
	L["Bags"] = true
	L["Bank"] = true
	L["Battle Pet"] = true
	L["Bind Location"] = true
	L["Class quests"] = true
	L["Coins"] = true
	L["Community Feast"] = true
	L["Current Location"] = true
	L["Expire on"] = true
	L["Fyrakk Asssaults"] = true
	L["Garrison 3 Level"] = true
	L["Grand Hunt"] = true
	L["Keys of Loyalty"] = true
	L["Korthia"] = true
	L["Kyrian"] = true
	L["Last Update"] = true
	L["Level"] = true
	L["Maw"] = true
	L["Necrolord"] = true
	L["Night Fae"] = true
	L["Other"] = true
	L["Researchers Under Fire"] = true
	L["RESET"] = RESET
	L["Siege on Dragonbane Keep"] = true
	L["The Forbidden Reach"] = true
	L["The Storm's Fury"] = true
	L["Transferable Anima"] = true
	L["Transferable Flakes"] = true
	L["Treasure Goblin"] = true
	L["Vendored gray items for: "] = true
	L["Venthyr"] = true
	L["We need more gold"] = true
	L["You don't have enough money to repair."] = true
	L["Your items have been repaired for: "] = true
	L["Your items have been repaired using guild bank funds for: "] = true
	L["Zaralek Cavern"] = true
	L["Zereth Mortis"] = true
	L["Bodyguards"] = true
	L["Storyline"] = true
	L["No Reagent Bag"] = true
	L["Mythic Keystone"] = true
	L["Disciple of Fyrakk"] = true
	L["Fighting is Its Own Reward"] = true
	L["World Boss"] = true
	L["World Bosses"] = true
	L["PvP"] = true
	L["Weekend Event"] = true
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = true
	L["Sniffenseeking"] = true
	L["Sniffenseeking (items)"] = true
	L["Warmode"] = PVP_LABEL_WAR_MODE
	L["OFF"] = LOC_OPTION_OFF
	L["ON"] = PVP_WAR_MODE_ENABLED
	L["AutoSellGrey"] = true
	L["AutoRepair"] = true
	L["InputDelete"] = true
	L["AutoOpen"] = true
	L["AutoGossip"] = true
	L["CinematicCanceler"] = true
	L["ClearChat"] = true
	L["TalkingHeadFrame"] = true
	L["HideZoneText"] = true
	L["Covenant"] = true
	L["RaidBossEmoteFrame"] = true
	L["BossBanner"] = true
	L["HideErrorMessages"] = true
	L["UIErrorsFramePosition"] = true
	L["Functions"] = true
	L["Modules"] = true
	L["DisplaySettings"] = true
	L["TimeRift"] = true
	L["Dreamsurges"] = true
	L["Storm-Bound Chest"] = true
	L["Shadowmourne"] = true
	L["Green Fire"] = true
	L["Some Wicked Things"] = true
	L["Temporal Acquisitions Specialist"] = true
	L["d. "] = true
	L["h. "] = true
	L["m. "] = true
	L["s. "] = true
	L["The Veiled Ossuary"] = true
	L["Dilated Time Capsule"] = true
	L["Dreamsurge Chrysalis"] = true
	L["Dreamsurge Coalescence"] = true
	L["Charred Elemental Remains"] = true
	L["Encapsulated Destiny"] = true
	L["Dreamsurge Investigation"] = true
	L["Shaping the Dreamsurge"] = true
	L["Reforging the Tyr's Guard"] = true
	L["Tyr's Fall"] = true
	L["Head"] = true
	L["Shoulder"] = true
	L["Back"] = true
	L["Chest"] = true
	L["Wrist"] = true
	L["Hands"] = true
	L["Waist"] = true
	L["Legs"] = true
	L["Feet"] = true
	L["The Coalition of Flames"] = true
	L["Only Current Realm"] = true
	L["Player level: "] = true
	L["Item level: "] = true -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = true
	L["Auto Turn Quests"] = true
	L["Aiding the Accord"] = true
	L["InDev"] = true
	L["HideCovenant"] = true
	L["Total"] = true
	L["Consumables"] = true
	L["Parts"] = true
	L["Elemental"] = true
	L["Optional Reagents"] = true
	L["Trade Goods"] = true
	L["Auto_Screenshot"] = true
	L["When Time Needs Mending"] = true
	L["Current Date"] = true
	L["About"] = true
	L["Portals"] = true
	L["Firelands"] = true
	L["Black Temple"] = true
	L["Dawn of the Infinites"] = true
	L["ShowSkips"] = true
	L["Race quests"] = true
	L["Seeing Red"] = true






	-- print (LOC_OPTION_OFF, VIDEO_OPTIONS_ENABLED)
end
L = AL3:NewLocale("OctoTODO", "ruRU")
if L then
	L["Abandon All Quests"] = "Отменить все задания"
	L["Abandon"] = "Отменено: "
	L["Bags"] = "Сумки"
	L["Bank"] = "Банк"
	L["Battle Pet"] = "Боевой питомец"
	L["Bind Location"] = "Место привязки"
	L["Class quests"] = "Классовые задания"
	L["Coins"] = "Монетки"
	L["Community Feast"] = "Большое пиршество"
	L["Current Location"] = "Текущее местоположение"
	L["Expire on"] = "Истекает"
	L["Fyrakk Asssaults"] = "Налет Фиракка (Локалка)"
	L["Garrison 3 Level"] = "Гарнизон 3 уровня"
	L["Grand Hunt"] = "Великая охота"
	L["Keys of Loyalty"] = "Ключи преданности"
	L["Korthia"] = "Кортия"
	L["Kyrian"] = "Кирии"
	L["Last Update"] = "Последнее Обновление"
	L["Level"] = "Уровень"
	L["Maw"] = "Утроба"
	L["Necrolord"] = "Некролорды"
	L["Night Fae"] = "Ночной народец"
	L["Other"] = "Другое"
	L["Researchers Under Fire"] = "Исследователли под огнем" --func_questName(74905)
	L["RESET"] = "Сброс всех данных аддона"
	L["Siege on Dragonbane Keep"] = "Осада Драконьей Погибели"
	L["The Forbidden Reach"] = "Запретный край" -- "Запретный край (10.0.7)"
	L["The Storm's Fury"] = "Неистовство бури"
	L["Transferable Anima"] = "Переносимая анима"
	L["Transferable Flakes"] = "Переносимая стружка"
	L["Treasure Goblin"] = "Алчный гоблин"
	L["Vendored gray items for: "] = "Серые предметы проданы на сумму: "
	L["Venthyr"] = "Вентиры"
	L["We need more gold"] = "Нужно больше золота!"
	L["You don't have enough money to repair."] = "У Вас недостаточно денег для ремонта."
	L["Your items have been repaired for: "] = "Ремонт обошелся в "
	L["Your items have been repaired using guild bank funds for: "] = "Ремонт обошелся гильдии в "
	L["Zaralek Cavern"] = "Пещера Заралек" -- "Пещера Заралек (10.1.0)"
	L["Zereth Mortis"] = "Зерет Мортис"
	L["Bodyguards"] = "Телохранители"
	L["Storyline"] = "Сюжетная линия"
	L["No Reagent Bag"] = "Нет сумки реагентов"
	L["Mythic Keystone"] = "Эпохальный ключ"
	L["Disciple of Fyrakk"] = "Ученик Фиракка"
	L["Fighting is Its Own Reward"] = "Славный бой – это уже награда"
	L["World Boss"] = "Мировой босс"
	L["World Bosses"] = "Мировые боcсы"
	L["PvP"] = "PvP"
	L["Weekend Event"] = "Событие выходного дня"
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = "Достойный союзник: лоаммские ниффы"
	L["Sniffenseeking"] = "Нюхорысканье"
	L["Sniffenseeking (items)"] = "Нюхорысканье ("..ITEMS..")"
	L["AutoSellGrey"] = "Автопродажа серого хлама"
	L["AutoRepair"] = "Автопочинка"
	L["InputDelete"] = "Автозаполнение 'УДАЛИТЬ'"
	L["AutoOpen"] = "Автооткрытие предметов"
	L["AutoGossip"] = "Авторазговор с НПЦ"
	L["CinematicCanceler"] = "Автопропуск видео"
	L["ClearChat"] = "Чистка чата при заходе в игру"
	L["TalkingHeadFrame"] = "Скрытие говорящей головы"
	L["HideZoneText"] = "Скрытие текста зон"
	L["HideCovenant"] = "Скрытие смены ковенанта"
	L["RaidBossEmoteFrame"] = "Скрытие эмоций босса"
	L["BossBanner"] = "Скрытие баннера босса"
	L["HideErrorMessages"] = "Скрытие красного текста ошибок"
	L["UIErrorsFramePosition"] = "Смена позиции фрейма ошибок/квестов"
	L["Functions"] = "Функции"
	L["Modules"] = "Модули"
	L["DisplaySettings"] = "Настройки отображения"
	L["TimeRift"] = "Портал времени"
	L["Dreamsurges"] = "Прилив Снов"
	L["Storm-Bound Chest"] = "Запечатанный бурей сундук"
	L["Shadowmourne"] = "Темная Скорбь"
	L["Green Fire"] = "Зелёный Огонь"
	L["Some Wicked Things"] = "Некоторые неприятные вещи (10.1.5)"
	L["Temporal Acquisitions Specialist"] = "Темпоральный специалист по снабжению"
	L["d. "] = "д. "
	L["h. "] = "ч. "
	L["m. "] = "м. "
	L["s. "] = "с. "
	L["The Veiled Ossuary"] = "Тайный склеп"
	L["Dilated Time Capsule"] = "Капсула растянутого времени"
	L["Dreamsurge Chrysalis"] = "Хризалида Дикого Сна"
	L["Dreamsurge Coalescence"] = "Слияние Прилива Снов"
	L["Charred Elemental Remains"] = "Обугленные останки элементалей"
	L["Encapsulated Destiny"] = "Инкапсулированная судьба"
	L["Dreamsurge Investigation"] = "Исследование Прилива Снов"
	L["Shaping the Dreamsurge"] = "Укрощение Прилива Снов"
	L["Reforging the Tyr's Guard"] = "Возрождение Стражей Тира"
	L["Tyr's Fall"] = "Последнее пристанище Тира"
	L["Head"] = "Голова"
	L["Shoulder"] = "Плечи"
	L["Back"] = "Спина"
	L["Chest"] = "Грудь"
	L["Wrist"] = "Запястья"
	L["Hands"] = "Кисти рук"
	L["Waist"] = "Пояс"
	L["Legs"] = "Ноги"
	L["Feet"] = "Ступни"
	L["The Coalition of Flames"] = "Союз пламени"
	L["InDev"] = "|cffFF0000В разработке|r"
	L["Only Current Realm"] = "Только текущий сервер"
	L["Player level: "] = "Уровень игрока: "
	L["Item level: "] = "Уровень предметов: " -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = "Ширина: "
	L["Auto Turn Quests"] = "Автопринятие заданий"
	L["Aiding the Accord"] = "Помощь союзу"
	L["Total"] = "Всего"
	L["Consumables"] = "Расходуемые предметы"
	L["Parts"] = "Детали"
	L["Elemental"] = "Стихии"
	L["Optional Reagents"] = "Дополнительные реагенты"
	L["Trade Goods"] = "Хозяйственные товары"
	L["Auto_Screenshot"] = "Автоскриншот"
	L["When Time Needs Mending"] = "Исцелить само время"
	L["Current Date"] = "Текущая дата"
	L["About"] = "Об аддоне"
	L["Portals"] = "Порталы"
	L["Firelands"] = "Огненные Просторы"
	L["Dawn of the Infinites"] = "Рассвет Бесконечности"
	L["ShowSkips"] = "Проходки"
	L["Black Temple"] = "Чёрный Храм"
	L["Race quests"] = "Рассовые задания"
	L["Seeing Red"] = "Ярость или стыд?"
end
