-- local GlobalAddonName, E = ...
-- local AddonTitle = C_AddOns.GetAddOnMetadata(GlobalAddonName, "Title")
-- ----------------------------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------------------------
-- local function Hide()
--     WowheadQuickLinkConfig_Frame:Hide()
-- end

-- local function SetUrl()
--     WowheadQuickLinkConfig_FinalUrlText:SetText(string.format(E.Octo_Globals.baseWowheadUrl, Octo_ToDoOther.prefix, "<type>", "<id>", Octo_ToDoOther.suffix))
-- end
-- SLASH_WOWHEAD_QUICK_LINK1 = "/wql"
-- SLASH_WOWHEAD_QUICK_LINK2 = "/wowheadquicklink"
-- SlashCmdList["WOWHEAD_QUICK_LINK"] =

-- function(message, editBox)
--     WowheadQuickLinkConfig_EditBoxPrefix:SetText(Octo_ToDoOther.prefix)
--     WowheadQuickLinkConfig_EditBoxSuffix:SetText(Octo_ToDoOther.suffix)
--     SetUrl()
--     WowheadQuickLinkConfig_Frame:Show()
-- end
-- WowheadQuickLinkConfig_EditBoxPrefix:SetScript("OnEscapePressed", Hide)
-- WowheadQuickLinkConfig_EditBoxPrefix:SetScript("OnEnterPressed", Hide)
-- WowheadQuickLinkConfig_EditBoxSuffix:SetScript("OnEscapePressed", Hide)
-- WowheadQuickLinkConfig_EditBoxSuffix:SetScript("OnEnterPressed", Hide)
-- WowheadQuickLinkConfig_EditBoxPrefix:SetScript("OnTextChanged",
--     function(self)
--         Octo_ToDoOther.prefix = self:GetText()
--         SetUrl()
--     end
-- )
-- WowheadQuickLinkConfig_EditBoxSuffix:SetScript("OnTextChanged",
--     function(self)
--         Octo_ToDoOther.suffix = self:GetText()
--         SetUrl()
--     end
-- )
-- WowheadQuickLinkConfig_EditBoxPrefix:SetScript("OnTabPressed",
--     function(self)
--         WowheadQuickLinkConfig_EditBoxSuffix:SetFocus()
--     end
-- )
-- WowheadQuickLinkConfig_EditBoxSuffix:SetScript("OnTabPressed",
--     function(self)
--         WowheadQuickLinkConfig_EditBoxPrefix:SetFocus()
--     end
-- )
-- BINDING_HEADER_WOWHEAD_QUICK_LINK_HEADER = "Wowhead Quick Link"
-- BINDING_DESCRIPTION_WOWHEAD_QUICK_LINK_DESC = "Keybind for generating Wowhead link"
-- BINDING_NAME_WOWHEAD_QUICK_LINK_NAME = "Generate Wowhead link"
-- BINDING_NAME_WOWHEAD_QUICK_LINK_RAIDERIO_NAME = "Generate Raider.IO link"