local GlobalAddonName, E = ...
local AddonTitle = C_AddOns.GetAddOnMetadata(GlobalAddonName, "Title")
--------------------------------------------------------------------------------
local AL3 = LibStub("AceLocale-3.0")
local debug = false
local L = AL3:NewLocale("OctoTODO", "enUS", true, debug)
if L then
	L["GlobalAddonName"] = AddonTitle
	L["|cFF00A3FFTalking head frame|r |cffFF4C4Fcanceled.|r"] = true

	L["Abandon All Quests"] = true
	L["Abandon: "] = true
	L["Bags"] = true
	L["Bank"] = true
	L["Battle Pet"] = true
	L["Bind Location"] = true
	L["Class quests"] = true
	L["Coins"] = true
	L["Community Feast"] = true
	L["Current Location"] = true
	L["Expire on"] = true
	L["Fyrakk Asssaults"] = true
	L["Garrison 3 Level"] = true
	L["Grand Hunt"] = true
	L["Keys of Loyalty"] = true
	L["Korthia"] = true
	L["Kyrian"] = true
	L["Last Update"] = true
	L["Level"] = true
	L["Maw"] = true
	L["Necrolord"] = true
	L["Night Fae"] = true
	L["Other"] = true
	L["Researchers Under Fire"] = true
	L["RESET"] = RESET
	L["Siege on Dragonbane Keep"] = true
	L["The Forbidden Reach"] = true
	L["The Storm's Fury"] = true
	L["Transferable Anima"] = true
	L["Transferable Flakes"] = true
	L["Treasure Goblin"] = true
	L["Vendored gray items for: "] = true
	L["Venthyr"] = true
	L["We need more gold"] = true
	L["You don't have enough money to repair."] = true
	L["Your items have been repaired for: "] = true
	L["Your items have been repaired using guild bank funds for: "] = true
	L["Zaralek Cavern"] = true
	L["Zereth Mortis"] = true
	L["Bodyguards"] = true
	L["Storyline"] = true
	L["No Reagent Bag"] = true
	L["Mythic Keystone"] = true
	L["Disciple of Fyrakk"] = true
	L["Fighting is Its Own Reward"] = true
	L["World Boss"] = true
	L["World Bosses"] = true
	L["PvP"] = true
	L["Weekend Event"] = true
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = true
	L["Sniffenseeking"] = true
	L["Sniffenseeking (items)"] = true
	L["Warmode"] = PVP_LABEL_WAR_MODE
	L["OFF"] = LOC_OPTION_OFF
	L["ON"] = PVP_WAR_MODE_ENABLED
	L["AutoSellGrey"] = true
	L["AutoRepair"] = true
	L["InputDelete"] = true
	L["AutoOpen"] = true
	L["AutoGossip"] = true
	L["CinematicCanceler"] = true
	L["ClearChat"] = true
	L["TalkingHeadFrame"] = true
	L["HideZoneText"] = true
	L["Covenant"] = true
	L["RaidBossEmoteFrame"] = true
	L["BossBanner"] = true
	L["HideErrorMessages"] = true
	L["UIErrorsFramePosition"] = true
	L["Functions"] = true
	L["Modules"] = true
	L["DisplaySettings"] = true
	L["Time Rift"] = true
	L["Dreamsurges"] = true
	L["Storm-Bound Chest"] = true
	L["Shadowmourne"] = true
	L["Green Fire"] = true
	L["Some Wicked Things"] = true
	L["Temporal Acquisitions Specialist"] = true
	L["d. "] = true
	L["h. "] = true
	L["m. "] = true
	L["s. "] = true
	L["The Veiled Ossuary"] = true
	L["Dilated Time Capsule"] = true
	L["Dreamsurge Chrysalis"] = true
	L["Dreamsurge Coalescence"] = true
	L["Charred Elemental Remains"] = true
	L["Encapsulated Destiny"] = true
	L["Dreamsurge Investigation"] = true
	L["Shaping the Dreamsurge"] = true
	L["Reforging the Tyr's Guard"] = true
	L["Tyr's Fall"] = true

	L["Head"] = true
	L["Shoulder"] = true
	L["Back"] = true
	L["Chest"] = true
	L["Wrist"] = true
	L["Hands"] = true
	L["Waist"] = true
	L["Legs"] = true
	L["Feet"] = true
	L["The Coalition of Flames"] = true
	L["Only Current Realm"] = true
	L["Player level: "] = true
	L["Item level: "] = true -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = true










L["Deadmines"] = true
L["Shadowfang Keep"] = true
L["Throne of the Tides"] = true
L["Blackrock Caverns"] = true
L["The Stonecore"] = true
L["The Vortex Pinnacle"] = true
L["Lost City of the Tol'vir"] = true
L["Halls of Origination"] = true
L["Grim Batol"] = true
L["The Bastion of Twilight"] = true
L["Blackwing Descent"] = true
L["Throne of the Four Winds"] = true
L["Baradin Hold"] = true
L["Zul'Gurub"] = true
L["Zul'Aman"] = true
L["Firelands"] = true
L["End Time"] = true
L["Well of Eternity"] = true
L["Hour of Twilight"] = true
L["Dragon Soul"] = true
L["Ragefire Chasm"] = true
L["Blackfathom Deeps"] = true
L["Blackrock Depths"] = true
L["Lower Blackrock Spire"] = true
L["Dire Maul"] = true
L["Gnomeregan"] = true
L["Maraudon"] = true
L["Razorfen Downs"] = true
L["Razorfen Kraul"] = true
L["Scarlet Monastery - OLD"] = true
L["Stratholme"] = true
L["The Temple of Atal'hakkar"] = true
L["The Stockade"] = true
L["Uldaman"] = true
L["Wailing Caverns"] = true
L["Zul'Farrak"] = true
L["Scholomance"] = true
L["Auchenai Crypts"] = true
L["Hellfire Ramparts"] = true
L["Magisters' Terrace"] = true
L["Mana-Tombs"] = true
L["Old Hillsbrad Foothills"] = true
L["Sethekk Halls"] = true
L["Shadow Labyrinth"] = true
L["The Arcatraz"] = true
L["The Black Morass"] = true
L["The Blood Furnace"] = true
L["The Botanica"] = true
L["The Mechanar"] = true
L["The Shattered Halls"] = true
L["The Slave Pens"] = true
L["The Steamvault"] = true
L["The Underbog"] = true
L["Ahn'kahet: The Old Kingdom"] = true
L["Azjol-Nerub"] = true
L["Drak'Tharon Keep"] = true
L["Gundrak"] = true
L["Halls of Lightning"] = true
L["Halls of Reflection"] = true
L["Halls of Stone"] = true
L["Pit of Saron"] = true
L["The Culling of Stratholme"] = true
L["The Forge of Souls"] = true
L["The Nexus"] = true
L["The Oculus"] = true
L["The Violet Hold"] = true
L["Trial of the Champion"] = true
L["Utgarde Keep"] = true
L["Utgarde Pinnacle"] = true
L["Stormstout Brewery"] = true
L["Gate of the Setting Sun"] = true
L["Scarlet Halls"] = true
L["Shado-Pan Monastery"] = true
L["Temple of the Jade Serpent"] = true
L["Scarlet Monastery"] = true
L["Mogu'shan Vaults"] = true
L["Terrace of Endless Spring"] = true
L["Mogu'shan Palace"] = true
L["Pandaria"] = true
L["Siege of Niuzao Temple"] = true
L["Heart of Fear"] = true
L["Throne of Thunder"] = true
L["Siege of Orgrimmar"] = true
L["Bloodmaul Slag Mines"] = true
L["Blackrock Foundry"] = true
L["Skyreach"] = true
L["Highmaul"] = true
L["Grimrail Depot"] = true
L["Shadowmoon Burial Grounds"] = true
L["Auchindoun"] = true
L["The Everbloom"] = true
L["Draenor"] = true
L["Iron Docks"] = true
L["Upper Blackrock Spire"] = true
L["Hellfire Citadel"] = true
L["Vault of the Wardens"] = true
L["Eye of Azshara"] = true
L["Halls of Valor"] = true
L["The Arcway"] = true
L["Maw of Souls"] = true
L["Black Rook Hold"] = true
L["Molten Core"] = true
L["Blackwing Lair"] = true
L["Ruins of Ahn'Qiraj"] = true
L["Temple of Ahn'Qiraj"] = true
L["Karazhan"] = true
L["Gruul's Lair"] = true
L["Magtheridon's Lair"] = true
L["Serpentshrine Cavern"] = true
L["The Eye"] = true
L["The Battle for Mount Hyjal"] = true
L["Black Temple"] = true
L["Sunwell Plateau"] = true
L["Vault of Archavon"] = true
L["Naxxramas"] = true
L["The Obsidian Sanctum"] = true
L["The Eye of Eternity"] = true
L["Trial of the Crusader"] = true
L["Icecrown Citadel"] = true
L["Ulduar"] = true
L["Onyxia's Lair"] = true
L["The Ruby Sanctum"] = true
L["Darkheart Thicket"] = true
L["Neltharion's Lair"] = true
L["The Emerald Nightmare"] = true
L["Assault on Violet Hold"] = true
L["The Nighthold"] = true
L["Court of Stars"] = true
L["Broken Isles"] = true
L["Return to Karazhan"] = true
L["Trial of Valor"] = true
L["Tomb of Sargeras"] = true
L["Cathedral of Eternal Night"] = true
L["Seat of the Triumvirate"] = true
L["Antorus, the Burning Throne"] = true
L["Invasion Points"] = true
L["Atal'Dazar"] = true
L["Freehold"] = true
L["Tol Dagor"] = true
L["The MOTHERLODE!!"] = true
L["Waycrest Manor"] = true
L["The Underrot"] = true
L["Siege of Boralus"] = true
L["Azeroth"] = true
L["Temple of Sethraliss"] = true
L["Uldir"] = true
L["Shrine of the Storm"] = true
L["Kings' Rest"] = true
L["Battle of Dazar'alor"] = true
L["Crucible of Storms"] = true
L["Operation: Mechagon"] = true
L["The Eternal Palace"] = true
L["Ny'alotha, the Waking City"] = true
L["The Necrotic Wake"] = true
L["Plaguefall"] = true
L["Mists of Tirna Scithe"] = true
L["Halls of Atonement"] = true
L["Spires of Ascension"] = true
L["Theater of Pain"] = true
L["De Other Side"] = true
L["Sanguine Depths"] = true
L["Castle Nathria"] = true
L["Shadowlands"] = true
L["Sanctum of Domination"] = true
L["Tazavesh, the Veiled Market"] = true
L["Sepulcher of the First Ones"] = true
L["Brackenhide Hollow"] = true
L["Uldaman: Legacy of Tyr"] = true
L["The Nokhud Offensive"] = true
L["Neltharus"] = true
L["Vault of the Incarnates"] = true
L["Algeth'ar Academy"] = true
L["Ruby Life Pools"] = true
L["The Azure Vault"] = true
L["Halls of Infusion"] = true
L["Dragon Isles"] = true
L["The Nokud Offensive"] = true
L["Aberrus, the Shadowed Crucible"] = true
L["Dawn of the Infinite"] = true
L["InDev"] = true --"|cffFF0000(In the pipeline)|r"
L["In the pipeline"] = true
L["HideCovenant"] = true


	-- print (LOC_OPTION_OFF, VIDEO_OPTIONS_ENABLED)


L["|cffffff00Click|r to open weekly rewards"] = "|cffffff00Click|r to open weekly rewards"
L["|cffffff00Left-click|r to detach tooltip"] = "|cffffff00Left-click|r to detach tooltip"
L["|cffffff00Middle-click|r to show Blizzard's Raid Information"] = "|cffffff00Middle-click|r to show Blizzard's Raid Information"
L["|cffffff00Right-click|r to configure SavedInstances"] = "|cffffff00Right-click|r to configure SavedInstances"
L["AA"] = "AA"
L["Abbreviate keystones"] = "Abbreviate keystones"
L["Abbreviate Mythic keystone dungeon names"] = "Abbreviate Mythic keystone dungeon names"
L["Account"] = "Account"
L["Account Summary"] = "Account Summary"
L["AD"] = "AD"
L["Add Entry"] = "Add Entry"
L["Aiding the Accord"] = "Aiding the Accord"
L["Air"] = "Air"
L["Air Core"] = "Air Core"
L["Always show"] = "Always show"
L["Amathet Reliquary"] = "Amathet Reliquary"
L["Ambered Coffer"] = "Ambered Coffer"
L["ARC"] = "ARC"
L["Are you sure you want to remove %s from the SavedInstances character database?"] = "Are you sure you want to remove %s from the SavedInstances character database?"
L["Are you sure you want to report all your keys to %s?"] = "Are you sure you want to report all your keys to %s?"
L["Are you sure you want to reset the SavedInstances character database? Characters will be re-populated as you log into them."] = "Are you sure you want to reset the SavedInstances character database? Characters will be re-populated as you log into them."
L["Attempt to recover completed daily quests for this character. Note this may recover some additional, linked daily quests that were not actually completed today."] = "Attempt to recover completed daily quests for this character. Note this may recover some additional, linked daily quests that were not actually completed today."
L["Automatically shrink the tooltip to fit on the screen"] = "Automatically shrink the tooltip to fit on the screen"
L["Azuregos"] = "Azuregos"
L["Battleground Deserter"] = "Battleground Deserter"
L["BH"] = "BH"
L["Bind a key to toggle the SavedInstances tooltip"] = "Bind a key to toggle the SavedInstances tooltip"
L["Bonus loot frame"] = "Bonus loot frame"
L["Bonus rolls"] = "Bonus rolls"
L[ [=[Boss kill information is missing for this lockout.
This is a Blizzard bug affecting certain old raids.]=] ] = [=[Boss kill information is missing for this lockout.
This is a Blizzard bug affecting certain old raids.]=]
L["Bouldron"] = "Bouldron"
L["BRH"] = "BRH"
L["Calling Missing"] = "Calling Missing"
L["Categories"] = "Categories"
L["Characters"] = "Characters"
L["Clean Entry"] = "Clean Entry"
L["COEN"] = "COEN"
L["Color currency by cap"] = "Color currency by cap"
L["Combine Callings"] = "Combine Callings"
L["Combine Emissaries"] = "Combine Emissaries"
L["Combine emissaries of same expansion"] = "Combine emissaries of same expansion"
L["Combine LFR"] = "Combine LFR"
L["Combine World Bosses"] = "Combine World Bosses"
L["Community Feast"] = "Community Feast"
L["Connected Realms"] = "Connected Realms"
L["COS"] = "COS"
L["Covenant"] = "Covenant"
L["Covenant Assaults"] = "Covenant Assaults"
L["Crystalus"] = "Crystalus"
L["Currency settings"] = "Currency settings"
L["Cursed Coffer"] = "Cursed Coffer"
L["Daily Quests"] = "Daily Quests"
L["Day"] = "Day"
L["Debug Mode"] = "Debug Mode"
L["Delete Entry"] = "Delete Entry"
L["DHT"] = "DHT"
L["Disable mouseover"] = "Disable mouseover"
L["Disable tooltip display on icon mouseover"] = "Disable tooltip display on icon mouseover"
L["Disciple of Fyrakk"] = "Disciple of Fyrakk"
L["Display instances in order of recommended level from lowest to highest"] = "Display instances in order of recommended level from lowest to highest"
L["Display instances with space inserted between categories"] = "Display instances with space inserted between categories"
L["Disturbed Dirt / Expedition Scout's Pack"] = "Disturbed Dirt / Expedition Scout's Pack"
L["Doomwalker"] = "Doomwalker"
L["DOS"] = "DOS"
L["Dragon of Nightmare"] = "Dragon of Nightmare"
L["Dragonflight Experimentation"] = "Dragonflight Experimentation"
L["Dragonflight Renown"] = "Dragonflight Renown"
L["Dragonflight Transmute"] = "Dragonflight Transmute"
L["Dump quest debugging information"] = "Dump quest debugging information"
L["Dump time debugging information"] = "Dump time debugging information"
L["Earth"] = "Earth"
L["Earth Core"] = "Earth Core"
L["Emblazion"] = "Emblazion"
L["Emissary Missing"] = "Emissary Missing"
L["Emissary of War"] = "Emissary of War"
L["Emissary Quests"] = "Emissary Quests"
L["Emissary quests"] = "Emissary quests"
L["EOA"] = "EOA"
L["Expansion"] = "Expansion"
L["Expired Lockout - Can be extended"] = "Expired Lockout - Can be extended"
L["Export"] = "Export"
L["Extended Lockout - Not yet saved"] = "Extended Lockout - Not yet saved"
L["Facets of Research"] = "Facets of Research"
L["FH"] = "FH"
L["Fighting is Its Own Reward"] = "Fighting is Its Own Reward"
L["Fire"] = "Fire"
L["Fire Core"] = "Fire Core"
L["Fit to screen"] = "Fit to screen"
L["Flex"] = "Flex"
L["Format large numbers"] = "Format large numbers"
L["Frozion"] = "Frozion"
L["Full Clear + 1 Mask"] = "Full Clear + 1 Mask"
L["Full Clear + 2 Masks"] = "Full Clear + 2 Masks"
L["Full Clear + 3 Masks"] = "Full Clear + 3 Masks"
L["Full Clear + 4 Masks"] = "Full Clear + 4 Masks"
L["Full Clear + 5 Masks"] = "Full Clear + 5 Masks"
L["Full Clear No Masks"] = "Full Clear No Masks"
L["Full Objective"] = "Full Objective"
L["Gaelzion"] = "Gaelzion"
L["GD"] = "GD"
L["General settings"] = "General settings"
L["GMBT"] = "GMBT"
L["Grand Hunt"] = "Grand Hunt"
L["Grand Hunts: Mythic Reward"] = "Grand Hunts: Mythic Reward"
L["Grand Hunts: Rare Reward"] = "Grand Hunts: Rare Reward"
L["Grand Hunts: Uncommon Reward"] = "Grand Hunts: Uncommon Reward"
L["Gravlion"] = "Gravlion"
L["Grizzlerock"] = "Grizzlerock"
L["Group"] = "Group"
L["Guild"] = "Guild"
L["HOA"] = "HOA"
L["HOI"] = "HOI"
L["Hold Alt to show all data"] = "Hold Alt to show all data"
L["HOV"] = "HOV"
L["Hover mouse on indicator for details"] = "Hover mouse on indicator for details"
L["Hunt: Death Elementals"] = "Hunt: Death Elementals"
L["Hunt: Shadehounds"] = "Hunt: Shadehounds"
L["Hunt: Soul Eaters"] = "Hunt: Soul Eaters"
L["Hunt: Winged Soul Eaters"] = "Hunt: Winged Soul Eaters"
L["Iceblade Trio"] = "Iceblade Trio"
L["ID"] = "ID"
L["Ignore"] = "Ignore"
L["Indicators"] = "Indicators"
L["Infernum"] = "Infernum"
L["Infested Strongbox"] = "Infested Strongbox"
L["Instance limit in Broker"] = "Instance limit in Broker"
L["Instances"] = "Instances"
L["Interleave"] = "Interleave"
L["Kain Firebrand"] = "Kain Firebrand"
L["Karantun"] = "Karantun"
L["Keystone report target"] = "Keystone report target"
L["KR"] = "KR"
L["Last updated"] = "Last updated"
L["Legion Transmute"] = "Legion Transmute"
L["Lesser Visions of N'Zoth"] = "Lesser Visions of N'Zoth"
L["Level %d Characters"] = "Level %d Characters"
L["LFG cooldown"] = "LFG cooldown"
L["LFR"] = "LFR"
L["List categories from the current expansion pack first"] = "List categories from the current expansion pack first"
L["List raid categories before dungeon categories"] = "List raid categories before dungeon categories"
L["Loot Aspect Crest Fragment"] = "Loot Aspect Crest Fragment"
L["Loot Drake Crest Fragment"] = "Loot Drake Crest Fragment"
L["Loot Spark of Shadowflame"] = "Loot Spark of Shadowflame"
L["Loot Whelpling Crest Fragment"] = "Loot Whelpling Crest Fragment"
L["Loot Wyrm Crest Fragment"] = "Loot Wyrm Crest Fragment"
L["Lord Kazzak"] = "Lord Kazzak"
L["LOWR"] = "LOWR"
L["Manage"] = "Manage"
L["Mechanized Chest"] = "Mechanized Chest"
L["Miscellaneous Tracking"] = "Miscellaneous Tracking"
L["MISTS"] = "MISTS"
L["ML"] = "ML"
L["Mogu Strongbox"] = "Mogu Strongbox"
L["MOS"] = "MOS"
L["Most recent first"] = "Most recent first"
L["Mythic Best"] = "Mythic Best"
L["Mythic Key Best"] = "Mythic Key Best"
L["Mythic Keystone"] = "Mythic Keystone"
L["Nathanos Blightcaller"] = "Nathanos Blightcaller"
L["Neela Firebane"] = "Neela Firebane"
L["NELT"] = "NELT"
L["Never show"] = "Never show"
L["New Single Quest"] = "New Single Quest"
L["NL"] = "NL"
L["NW"] = "NW"
L["Opacity of the tooltip row highlighting"] = "Opacity of the tooltip row highlighting"
L["Open config"] = "Open config"
L["Order must be a number in [0 - 999]"] = "Order must be a number in [0 - 999]"
L["Paragon Chests"] = "Paragon Chests"
L["Party"] = "Party"
L["Patterns Within Patterns"] = "Patterns Within Patterns"
L["PF"] = "PF"
L["Pipspark Thundersnap"] = "Pipspark Thundersnap"
L["Presets"] = "Presets"
L["Primal Storms Core"] = "Primal Storms Core"
L["Primal Storms Elementals"] = "Primal Storms Elementals"
L["Progress Persists"] = "Progress Persists"
L["Quest ID"] = "Quest ID"
L["Quest Name"] = "Quest Name"
L["Quest progresses"] = "Quest progresses"
L["Quest Reset Type"] = "Quest Reset Type"
L["Raids before dungeons"] = "Raids before dungeons"
L["Recent Bonus Rolls"] = "Recent Bonus Rolls"
L["Recent Instances"] = "Recent Instances"
L["Recover Dailies"] = "Recover Dailies"
L["Report instance resets to group"] = "Report instance resets to group"
L["Researchers Under Fire"] = "Researchers Under Fire"
L["Reset Characters"] = "Reset Characters"
L["Reverse ordering"] = "Reverse ordering"
L["RLP"] = "RLP"
L["Roll Bonus"] = "Roll Bonus"
L["Rouen Icewind"] = "Rouen Icewind"
L["Row Highlight"] = "Row Highlight"
L["SBG"] = "SBG"
L["SD"] = "SD"
L["SEAT"] = "SEAT"
L["Secured Shipment"] = "Secured Shipment"
L["Set All"] = "Set All"
L["Show all emissary names"] = "Show all emissary names"
L["Show both factions' emissay name"] = "Show both factions' emissay name"
L["Show calling line when all quests completed"] = "Show calling line when all quests completed"
L["Show category names"] = "Show category names"
L["Show category names in the tooltip"] = "Show category names in the tooltip"
L["Show cooldown for characters to use battleground system"] = "Show cooldown for characters to use battleground system"
L["Show cooldown for characters to use LFG dungeon system"] = "Show cooldown for characters to use LFG dungeon system"
L["Show currency earned"] = "Show currency earned"
L["Show currency max"] = "Show currency max"
L["Show emissary line when all quests completed"] = "Show emissary line when all quests completed"
L["Show Expired"] = "Show Expired"
L["Show expired instance lockouts"] = "Show expired instance lockouts"
L["Show Holiday"] = "Show Holiday"
L["Show holiday boss rewards"] = "Show holiday boss rewards"
L["Show minimap button"] = "Show minimap button"
L["Show name for a category when all displayed instances belong only to that category"] = "Show name for a category when all displayed instances belong only to that category"
L["Show only current server"] = "Show only current server"
L["Show Random"] = "Show Random"
L["Show random dungeon bonus reward"] = "Show random dungeon bonus reward"
L["Show self always"] = "Show self always"
L["Show self first"] = "Show self first"
L["Show server name"] = "Show server name"
L["Show the SavedInstances minimap button"] = "Show the SavedInstances minimap button"
L["Show tooltip hints"] = "Show tooltip hints"
L["Show When"] = "Show When"
L["Show when completed"] = "Show when completed"
L["Show when saved"] = "Show when saved"
L["Show/Hide the SavedInstances tooltip"] = "Show/Hide the SavedInstances tooltip"
L["SIEGE"] = "SIEGE"
L["Siege on Dragonbane Keep"] = "Siege on Dragonbane Keep"
L["Similarly, the words KILLED and TOTAL will be substituted with the number of bosses killed and total in the lockout."] = "Similarly, the words KILLED and TOTAL will be substituted with the number of bosses killed and total in the lockout."
L["Single category name"] = "Single category name"
L["SOA"] = "SOA"
L["Sort by currency name"] = "Sort by currency name"
L["Sort by server"] = "Sort by server"
L["Sort categories by"] = "Sort categories by"
L["Sort Order"] = "Sort Order"
L["Sorting"] = "Sorting"
L["SOTS"] = "SOTS"
L["Space between categories"] = "Space between categories"
L["Sparks of Life"] = "Sparks of Life"
L["Storm Surge"] = "Storm Surge"
L["STRT"] = "STRT"
L["TAV"] = "TAV"
L["TD"] = "TD"
L["Text"] = "Text"
L["The Four Celestials"] = "The Four Celestials"
L["The World Awaits"] = "The World Awaits"
L["These are the instances that count towards the %i instances per hour account limit, and the time until they expire."] = "These are the instances that count towards the %i instances per hour account limit, and the time until they expire."
L["This should only be used for characters who have been renamed or deleted, as characters will be re-populated when you log into them."] = "This should only be used for characters who have been renamed or deleted, as characters will be re-populated when you log into them."
L["Time /played"] = "Time /played"
L["Time Left"] = "Time Left"
L["Timewalking Weekend Event"] = "Timewalking Weekend Event"
L["Timeworn Mythic Keystone"] = "Timeworn Mythic Keystone"
L["TJS"] = "TJS"
L["TNO"] = "TNO"
L["Tooltip Scale"] = "Tooltip Scale"
L["TOP"] = "TOP"
L["Tormentors of Torghast"] = "Tormentors of Torghast"
L["TOS"] = "TOS"
L["Track Mythic keystone acquisition"] = "Track Mythic keystone acquisition"
L["Track Mythic keystone best run"] = "Track Mythic keystone best run"
L["Track Timeworn Mythic keystone acquisition"] = "Track Timeworn Mythic keystone acquisition"
L["Trade Skill Cooldowns"] = "Trade Skill Cooldowns"
L["Trade skills"] = "Trade skills"
L["Transmute"] = "Transmute"
L["Trial of Elements"] = "Trial of Elements"
L["Trial of Flood"] = "Trial of Flood"
L["Type"] = "Type"
L["ULD"] = "ULD"
L["UNDR"] = "UNDR"
L["UPPR"] = "UPPR"
L["Use class color"] = "Use class color"
L["User"] = "User"
L["Vision Boss + 2 Bonus Objectives"] = "Vision Boss + 2 Bonus Objectives"
L["Vision Boss Only"] = "Vision Boss Only"
L["Voraazka"] = "Voraazka"
L["VOTW"] = "VOTW"
L["VP"] = "VP"
L["Warfronts"] = "Warfronts"
L["Warn about instance limit"] = "Warn about instance limit"
L["Warning: You've entered about %i instances recently and are approaching the %i instance per hour limit for your account. More instances should be available in %s."] = "Warning: You've entered about %i instances recently and are approaching the %i instance per hour limit for your account. More instances should be available in %s."
L["Water"] = "Water"
L["Water Core"] = "Water Core"
L["Weekly Quests"] = "Weekly Quests"
L["Wild Transmute"] = "Wild Transmute"
L["WM"] = "WM"
L["WORK"] = "WORK"
L["Wrath of the Jailer"] = "Wrath of the Jailer"
L["YARD"] = "YARD"
L["You can combine icons and text in a single indicator if you wish. Simply choose an icon, and insert the word ICON into the text field. Anywhere the word ICON is found, the icon you chose will be substituted in."] = "You can combine icons and text in a single indicator if you wish. Simply choose an icon, and insert the word ICON into the text field. Anywhere the word ICON is found, the icon you chose will be substituted in."
L["Zurgaz Corebreaker"] = "Zurgaz Corebreaker"
end

L = AL3:NewLocale("OctoTODO", "ruRU")
if L then
	L["Abandon All Quests"] = "Отменить все задания"
	L["Abandon"] = "Отменено: "
	L["Bags"] = "Сумки"
	L["Bank"] = "Банк"
	L["Battle Pet"] = "Боевой питомец"
	L["Bind Location"] = "Место привязки"
	L["Class quests"] = "Классовые задания"
	L["Coins"] = "Монетки"
	L["Community Feast"] = "Большое пиршество"
	L["Current Location"] = "Текущее местоположение"
	L["Expire on"] = "Истекает"
	L["Fyrakk Asssaults"] = "Налет Фиракка (Локалка)"
	L["Garrison 3 Level"] = "Гарнизон 3 уровня"
	L["Grand Hunt"] = "Великая охота"
	L["Keys of Loyalty"] = "Ключи преданности"
	L["Korthia"] = "Кортия"
	L["Kyrian"] = "Кирии"
	L["Last Update"] = "Последнее Обновление"
	L["Level"] = "Уровень"
	L["Maw"] = "Утроба"
	L["Necrolord"] = "Некролорды"
	L["Night Fae"] = "Ночной народец"
	L["Other"] = "Разное"
	L["Researchers Under Fire"] = "Исследователли под огнем" --func_questName(74905)
	L["RESET"] = "Сброс всех данных аддона"
	L["Siege on Dragonbane Keep"] = "Осада Драконьей Погибели"
	L["The Forbidden Reach"] = "Запретный край" -- "Запретный край (10.0.7)"
	L["The Storm's Fury"] = "Неистовство бури"
	L["Transferable Anima"] = "Переносимая анима"
	L["Transferable Flakes"] = "Переносимая стружка"
	L["Treasure Goblin"] = "Алчный гоблин"
	L["Vendored gray items for: "] = "Серые предметы проданы на сумму: "
	L["Venthyr"] = "Вентиры"
	L["We need more gold"] = "Нужно больше золота!"
	L["You don't have enough money to repair."] = "У Вас недостаточно денег для ремонта."
	L["Your items have been repaired for: "] = "Ремонт обошелся в "
	L["Your items have been repaired using guild bank funds for: "] = "Ремонт обошелся гильдии в "
	L["Zaralek Cavern"] = "Пещера Заралек" -- "Пещера Заралек (10.1.0)"
	L["Zereth Mortis"] = "Зерет Мортис"
	L["Bodyguards"] = "Телохранители"
	L["Storyline"] = "|cffd6bfa6Сюжетная линия|r"
	L["No Reagent Bag"] = "Нет сумки реагентов"
	L["Mythic Keystone"] = "Эпохальный ключ"
	L["Disciple of Fyrakk"] = "Ученик Фиракка"
	L["Fighting is Its Own Reward"] = "Славный бой – это уже награда"
	L["World Boss"] = "Мировой босс"
	L["World Bosses"] = "Мировые боcсы"
	L["PvP"] = "PvP"
	L["Weekend Event"] = "Событие выходного дня"
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = "Достойный союзник: лоаммские ниффы"
	L["Sniffenseeking"] = "Нюхорысканье"
	L["Sniffenseeking (items)"] = "Нюхорысканье ("..ITEMS..")"
	L["AutoSellGrey"] = "Автопродажа серого хлама"
	L["AutoRepair"] = "Автопочинка"
	L["InputDelete"] = "Автозаполнение 'УДАЛИТЬ'"
	L["AutoOpen"] = "Автооткрытие предметов"
	L["AutoGossip"] = "Авторазговор с НПЦ"
	L["CinematicCanceler"] = "Автопропуск видео"
	L["ClearChat"] = "Чистка чата при заходе в игру"
	L["TalkingHeadFrame"] = "Скрытие говорящей головы"
	L["HideZoneText"] = "Скрытие текста зон"
	L["HideCovenant"] = "Скрытие смены ковенанта"
	L["RaidBossEmoteFrame"] = "Скрытие эмоций босса"
	L["BossBanner"] = "Скрытие баннера босса"
	L["HideErrorMessages"] = "Скрытие красного текста ошибок"
	L["UIErrorsFramePosition"] = "Смена позиции фрейма ошибок/квестов"
	L["Functions"] = "Функции"
	L["Modules"] = "Модули"
	L["DisplaySettings"] = "Настройки отображения"
	L["Time Rift"] = "Портал времени"
	L["Dreamsurges"] = "Прилив Снов"
	L["Storm-Bound Chest"] = "Запечатанный бурей сундук"
	L["Shadowmourne"] = "Темная Скорбь"
	L["Green Fire"] = "Зелёный Огонь"
	L["Some Wicked Things"] = "Некоторые неприятные вещи (10.1.5)"
	L["Temporal Acquisitions Specialist"] = "Темпоральный специалист по снабжению"
	L["d. "] = "д. "
	L["h. "] = "ч. "
	L["m. "] = "м. "
	L["s. "] = "с. "
	L["The Veiled Ossuary"] = "Тайный склеп"
	L["Dilated Time Capsule"] = "Капсула растянутого времени"
	L["Dreamsurge Chrysalis"] = "Хризалида Дикого Сна"
	L["Dreamsurge Coalescence"] = "Слияние Прилива Снов"
	L["Charred Elemental Remains"] = "Обугленные останки элементалей"
	L["Encapsulated Destiny"] = "Инкапсулированная судьба"
	L["Dreamsurge Investigation"] = "Исследование Прилива Снов"
	L["Shaping the Dreamsurge"] = "Укрощение Прилива Снов"
	L["Reforging the Tyr's Guard"] = "Возрождение Стражей Тира"
	L["Tyr's Fall"] = "Последнее пристанище Тира"

	L["Head"] = "Голова"
	L["Shoulder"] = "Плечи"
	L["Back"] = "Спина"
	L["Chest"] = "Грудь"
	L["Wrist"] = "Запястья"
	L["Hands"] = "Кисти рук"
	L["Waist"] = "Пояс"
	L["Legs"] = "Ноги"
	L["Feet"] = "Ступни"
	L["The Coalition of Flames"] = "Союз пламени"
	L["InDev"] = "|cffFF0000(В стадии разработки)|r"
	L["Only Current Realm"] = "Только текущий сервер"
	L["Player level: "] = "Уровень игрока: "
	L["Item level: "] = "Уровень предметов: " -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = "Ширина: "

L["Deadmines"] = "Мертвые копи"
L["Shadowfang Keep"] = "Крепость Темного Клыка"
L["Throne of the Tides"] = "Трон Приливов"
L["Blackrock Caverns"] = "Пещеры Черной горы"
L["The Stonecore"] = "Каменные Недра"
L["The Vortex Pinnacle"] = "Вершина Смерча"
L["Lost City of the Tol'vir"] = "Затерянный город Тол'вир"
L["Halls of Origination"] = "Чертоги Созидания"
L["Grim Batol"] = "Грим Батол"
L["The Bastion of Twilight"] = "Сумеречный бастион"
L["Blackwing Descent"] = "Твердыня Крыла Тьмы"
L["Throne of the Four Winds"] = "Трон Четырех Ветров"
L["Baradin Hold"] = "Крепость Барадин"
L["Zul'Gurub"] = "Зул'Гуруб"
L["Zul'Aman"] = "Зул'Аман"
L["Firelands"] = "Огненные Просторы"
L["End Time"] = "Конец Времен"
L["Well of Eternity"] = "Источник Вечности"
L["Hour of Twilight"] = "Время Сумерек"
L["Dragon Soul"] = "Душа Дракона"
L["Ragefire Chasm"] = "Огненная Пропасть"
L["Blackfathom Deeps"] = "Непроглядная Пучина"
L["Blackrock Depths"] = "Глубины Черной горы"
L["Lower Blackrock Spire"] = "Нижняя часть пика Черной горы"
L["Dire Maul"] = "Забытый город"
L["Gnomeregan"] = "Гномреган"
L["Maraudon"] = "Мародон"
L["Razorfen Downs"] = "Курганы Иглошкурых"
L["Razorfen Kraul"] = "Лабиринты Иглошкурых"
L["Scarlet Monastery - OLD"] = "Монастырь Алого ордена"
L["Stratholme"] = "Стратхольм"
L["The Temple of Atal'hakkar"] = "Храм Атал'Хаккар"
L["The Stockade"] = "Тюрьма"
L["Uldaman"] = "Ульдаман"
L["Wailing Caverns"] = "Пещеры Стенаний"
L["Zul'Farrak"] = "Зул'Фаррак"
L["Scholomance"] = "Некроситет"
L["Auchenai Crypts"] = "Аукенайские гробницы"
L["Hellfire Ramparts"] = "Бастионы Адского Пламени"
L["Magisters' Terrace"] = "Терраса Магистров"
L["Mana-Tombs"] = "Гробницы маны"
L["Old Hillsbrad Foothills"] = "Старые предгорья Хилсбрада"
L["Sethekk Halls"] = "Сетеккские залы"
L["Shadow Labyrinth"] = "Темный лабиринт"
L["The Arcatraz"] = "Аркатрац"
L["The Black Morass"] = "Черные топи"
L["The Blood Furnace"] = "Кузня Крови"
L["The Botanica"] = "Ботаника"
L["The Mechanar"] = "Механар"
L["The Shattered Halls"] = "Разрушенные залы"
L["The Slave Pens"] = "Узилище"
L["The Steamvault"] = "Паровое подземелье"
L["The Underbog"] = "Нижетопь"
L["Ahn'kahet: The Old Kingdom"] = "Ан'кахет: Старое Королевство"
L["Azjol-Nerub"] = "Азжол-Неруб"
L["Drak'Tharon Keep"] = "Крепость Драк'Тарон"
L["Gundrak"] = "Гундрак"
L["Halls of Lightning"] = "Чертоги Молний"
L["Halls of Reflection"] = "Залы Отражений"
L["Halls of Stone"] = "Чертоги Камня"
L["Pit of Saron"] = "Яма Сарона"
L["The Culling of Stratholme"] = "Очищение Стратхольма"
L["The Forge of Souls"] = "Кузня Душ"
L["The Nexus"] = "Нексус"
L["The Oculus"] = "Окулус"
L["The Violet Hold"] = "Аметистовая крепость"
L["Trial of the Champion"] = "Испытание чемпиона"
L["Utgarde Keep"] = "Крепость Утгард"
L["Utgarde Pinnacle"] = "Вершина Утгард"
L["Stormstout Brewery"] = "Хмелеварня Буйных Портеров"
L["Gate of the Setting Sun"] = "Врата Заходящего Солнца"
L["Scarlet Halls"] = "Залы Алого ордена"
L["Shado-Pan Monastery"] = "Монастырь Шадо-Пан"
L["Temple of the Jade Serpent"] = "Храм Нефритовой Змеи"
L["Scarlet Monastery"] = "Монастырь Алого ордена"
L["Mogu'shan Vaults"] = "Подземелья Могу'шан"
L["Terrace of Endless Spring"] = "Терраса Вечной Весны"
L["Mogu'shan Palace"] = "Дворец Могу'шан"
L["Pandaria"] = "Пандария"
L["Siege of Niuzao Temple"] = "Осада храма Нюцзао"
L["Heart of Fear"] = "Сердце Страха"
L["Throne of Thunder"] = "Престол Гроз"
L["Siege of Orgrimmar"] = "Осада Оргриммара"
L["Bloodmaul Slag Mines"] = "Шлаковые шахты Кровавого Молота"
L["Blackrock Foundry"] = "Литейная клана Черной горы"
L["Skyreach"] = "Небесный Путь"
L["Highmaul"] = "Верховный Молот"
L["Grimrail Depot"] = "Депо Мрачных Путей"
L["Shadowmoon Burial Grounds"] = "Некрополь Призрачной Луны"
L["Auchindoun"] = "Аукиндон"
L["The Everbloom"] = "Вечное Цветение"
L["Draenor"] = "Дренор"
L["Iron Docks"] = "Железные доки"
L["Upper Blackrock Spire"] = "Верхняя часть пика Черной горы"
L["Hellfire Citadel"] = "Цитадель Адского Пламени"
L["Vault of the Wardens"] = "Казематы Стражей"
L["Eye of Azshara"] = "Око Азшары"
L["Halls of Valor"] = "Чертоги Доблести"
L["The Arcway"] = "Катакомбы Сурамара"
L["Maw of Souls"] = "Утроба Душ"
L["Black Rook Hold"] = "Крепость Черной Ладьи"
L["Molten Core"] = "Огненные недра"
L["Blackwing Lair"] = "Логово Крыла Тьмы"
L["Ruins of Ahn'Qiraj"] = "Руины Ан'Киража"
L["Temple of Ahn'Qiraj"] = "Храм Ан'Киража"
L["Karazhan"] = "Каражан"
L["Gruul's Lair"] = "Логово Груула"
L["Magtheridon's Lair"] = "Логово Магтеридона"
L["Serpentshrine Cavern"] = "Змеиное святилище"
L["The Eye"] = "Око"
L["The Battle for Mount Hyjal"] = "Битва за гору Хиджал"
L["Black Temple"] = "Черный храм"
L["Sunwell Plateau"] = "Плато Солнечного Колодца"
L["Vault of Archavon"] = "Хранилище Аркавона"
L["Naxxramas"] = "Наксрамас"
L["The Obsidian Sanctum"] = "Обсидиановое святилище"
L["The Eye of Eternity"] = "Око Вечности"
L["Trial of the Crusader"] = "Испытание крестоносца"
L["Icecrown Citadel"] = "Цитадель Ледяной Короны"
L["Ulduar"] = "Ульдуар"
L["Onyxia's Lair"] = "Логово Ониксии"
L["The Ruby Sanctum"] = "Рубиновое святилище"
L["Darkheart Thicket"] = "Чаща Темного Сердца"
L["Neltharion's Lair"] = "Логово Нелтариона"
L["The Emerald Nightmare"] = "Изумрудный Кошмар"
L["Assault on Violet Hold"] = "Штурм Аметистовой крепости"
L["The Nighthold"] = "Цитадель Ночи"
L["Court of Stars"] = "Квартал Звезд"
L["Broken Isles"] = "Расколотые острова"
L["Return to Karazhan"] = "Возвращение в Каражан"
L["Trial of Valor"] = "Испытание доблести"
L["Tomb of Sargeras"] = "Гробница Саргераса"
L["Cathedral of Eternal Night"] = "Собор Вечной Ночи"
L["Seat of the Triumvirate"] = "Престол Триумвирата"
L["Antorus, the Burning Throne"] = "Анторус Пылающий Трон"
L["Invasion Points"] = "Точки вторжения"
L["Atal'Dazar"] = "Атал'Дазар"
L["Freehold"] = "Вольная Гавань"
L["Tol Dagor"] = "Тол Дагор"
L["The MOTHERLODE!!"] = "ЗОЛОТАЯ ЖИЛА!!!"
L["Waycrest Manor"] = "Усадьба Уэйкрестов"
L["The Underrot"] = "Подгнилье"
L["Siege of Boralus"] = "Осада Боралуса"
L["Azeroth"] = "Азерот"
L["Temple of Sethraliss"] = "Храм Сетралисс"
L["Uldir"] = "Ульдир"
L["Shrine of the Storm"] = "Святилище Штормов"
L["Kings' Rest"] = "Гробница королей"
L["Battle of Dazar'alor"] = "Битва за Дазар'алор"
L["Crucible of Storms"] = "Горнило Штормов"
L["Operation: Mechagon"] = "Операция Мехагон"
L["The Eternal Palace"] = "Вечный дворец"
L["Ny'alotha, the Waking City"] = "Ни'алота"
L["The Necrotic Wake"] = "Смертельная тризна"
L["Plaguefall"] = "Чумные каскады"
L["Mists of Tirna Scithe"] = "Туманы Тирна Скитта"
L["Halls of Atonement"] = "Чертоги Покаяния"
L["Spires of Ascension"] = "Шпили Перерождения"
L["Theater of Pain"] = "Театр Боли"
L["De Other Side"] = "Та Сторона"
L["Sanguine Depths"] = "Кровавые катакомбы"
L["Castle Nathria"] = "Замок Нафрия"
L["Shadowlands"] = "Темные Земли"
L["Sanctum of Domination"] = "Святилище Господства"
L["Tazavesh, the Veiled Market"] = "Тайный рынок Тазавеш"
L["Sepulcher of the First Ones"] = "Гробница Предвечных"
L["Brackenhide Hollow"] = "Лощина Бурошкуров"
L["Uldaman: Legacy of Tyr"] = "Ульдаман: наследие Тира"
L["The Nokhud Offensive"] = "Наступление клана Нокхуд"
L["Neltharus"] = "Нелтарий"
L["Vault of the Incarnates"] = "Хранилище Воплощений"
L["Algeth'ar Academy"] = "Академия Алгет'ар"
L["Ruby Life Pools"] = "Рубиновые Омуты Жизни"
L["The Azure Vault"] = "Лазурное хранилище"
L["Halls of Infusion"] = "Чертоги Насыщения"
L["Dragon Isles"] = "Драконьи острова"
L["The Nokud Offensive"] = "Наступление клана Нокхуд"
L["Aberrus, the Shadowed Crucible"] = "Аберрий, Затененное Горнило"
L["Dawn of the Infinite"] = "Рассвет Бесконечности"









L["|cffffff00Click|r to open weekly rewards"] = "|cffffff00ЛКМ|r, чтобы открыть еженедельные награды"
L["|cffffff00Left-click|r to detach tooltip"] = "|cffffff00ЛКМ|r, чтобы показать информацию в отдельном окне"
L["|cffffff00Middle-click|r to show Blizzard's Raid Information"] = "Нажмите на колёсико мышки, чтобы показать информацию о рейдах от Blizzard"
L["|cffffff00Right-click|r to configure SavedInstances"] = "|cffffff00ПКМ|r, чтобы настроить SavedInstances"
L["AA"] = "АА"
L["Abbreviate keystones"] = "Сокращение названия ключей"
L["Abbreviate Mythic keystone dungeon names"] = "Сократить названия эпохальных подземелий"
L["Account"] = "Аккаунт"
L["Account Summary"] = "Общая сводка по аккаунту"
L["AD"] = "АТАЛ"
L["Add Entry"] = "Добавить запись"
L["Aiding the Accord"] = "Помощь союзу"
L["Air"] = "Воздух"
L["Air Core"] = "Воздушное ядро"
L["Always show"] = "Всегда отображать"
L["Amathet Reliquary"] = "Реликварий аматетов"
L["Ambered Coffer"] = "Покрытый янтарем сундук"
L["ARC"] = "КС"
L["Are you sure you want to remove %s from the SavedInstances character database?"] = "Вы уверены, что хотите удалить %s из базы данных персонажей SavedInstances?"
L["Are you sure you want to report all your keys to %s?"] = "Вы уверены, что хотите сообщить обо всех своих ключах %s?"
L["Are you sure you want to reset the SavedInstances character database? Characters will be re-populated as you log into them."] = "Вы уверены, что хотите сбросить базу данных персонажей SavedInstances? Персонажи будут повторно заполнены, как только Вы зайдёте ими в игру."
L["Attempt to recover completed daily quests for this character. Note this may recover some additional, linked daily quests that were not actually completed today."] = "Попытка восстановить завершённые ежедневные задания для этого персонажа. Обратите внимание, что это может восстановить некоторые дополнительные, связанные ежедневные задания, которые не были фактически сегодня завершены."
L["Automatically shrink the tooltip to fit on the screen"] = "Автоматически уменьшать размер подсказки, чтобы вместить на экран"
L["Azuregos"] = "Азурегос"
L["Battleground Deserter"] = "Дезертир с Поля Боя"
L["BH"] = "ЛОЩИНА"
L["Bind a key to toggle the SavedInstances tooltip"] = "Клавиша для вкл./выкл. подсказок SavedInstances"
L["Bonus loot frame"] = "Окно дополнительной добычи"
L["Bonus rolls"] = "Отслеживать бонусные броски"
L[ [=[Boss kill information is missing for this lockout.
This is a Blizzard bug affecting certain old raids.]=] ] = [=[Отсутствует информация об убийстве босса для этого сохранения рейда.
Это является ошибкой компании Blizzard, затрагивающей некоторые старые рейды.]=]
L["Bouldron"] = "Валурон"
L["BRH"] = "КЧЛ"
L["Calling Missing"] = "Призыв отсутствует"
L["Categories"] = "Категории"
L["Characters"] = "Персонажи"
L["Clean Entry"] = "Чистая запись"
L["COEN"] = "СОБОР"
L["Color currency by cap"] = "Расцвечивать валюту в зависимости от достижения максимума"
L["Combine Callings"] = "Совмещать призывы"
L["Combine Emissaries"] = "Объединить эмиссаров"
L["Combine emissaries of same expansion"] = "Объединить эмиссаров одного и того же дополнения"
L["Combine LFR"] = "Объединять СПР (LFR)"
L["Combine World Bosses"] = "Объединять мировых босcов"
L["Community Feast"] = "Большое пиршество"
L["Connected Realms"] = "Соединенные сервера"
L["COS"] = "КЗ"
L["Covenant"] = "Ковенант"
L["Covenant Assaults"] = "Атаки ковенантов"
L["Crystalus"] = "Кристалий"
L["Currency settings"] = "Настройки валюты"
L["Cursed Coffer"] = "Проклятый сундук"
L["Daily Quests"] = "Ежедневные задания"
L["Day"] = "День"
L["Debug Mode"] = "Режим отладки"
L["Delete Entry"] = "Удалить запись"
L["DHT"] = "ЧАЩА"
L["Disable mouseover"] = "Откл. отобр. по наведению"
L["Disable tooltip display on icon mouseover"] = "Отключить отображение подсказки по наведению на иконку"
L["Disciple of Fyrakk"] = "Ученик Фиракка"
L["Display instances in order of recommended level from lowest to highest"] = "Отображать подземелья в порядке рекомендуемого уровня от самого низкого до самого высокого"
L["Display instances with space inserted between categories"] = "Показывать подземелья с промежутком между категориями"
L["Disturbed Dirt / Expedition Scout's Pack"] = "Потревоженная почва / Сумка разведчика экспедиции"
L["Doomwalker"] = "Судьболом"
L["DOS"] = "ТС"
L["Dragon of Nightmare"] = "Драконы Кошмара"
L["Dragonflight Experimentation"] = "Эксперименты Драконьих островов"
L["Dragonflight Renown"] = "Известность Драконьих островов"
L["Dragonflight Transmute"] = "Трансмутация Драконьих островов"
L["Dump quest debugging information"] = "Сохранить отладочную информацию квеста в файле"
L["Dump time debugging information"] = "Вывести информацию о времени для отладки"
L["Earth"] = "Земля"
L["Earth Core"] = "Земляное ядро"
L["Emblazion"] = "Пламенион"
L["Emissary Missing"] = "Посланники отсутствуют"
L["Emissary of War"] = "Emissary of War"
L["Emissary Quests"] = "Задания Посланников"
L["Emissary quests"] = "Задания Посланников"
L["EOA"] = "ОКО"
L["Expansion"] = "Сохранение подземелий"
L["Expired Lockout - Can be extended"] = "Сохранение с истекшим сроком - можно продлить"
L["Export"] = "Экспорт"
L["Extended Lockout - Not yet saved"] = "Продление сохранения - ещё не сохранено"
L["Facets of Research"] = "Грань исследования (ювелирное дело)"
L["FH"] = "ГАВАНЬ"
L["Fighting is Its Own Reward"] = "Славный бой – это уже награда"
L["Fire"] = "Огонь"
L["Fire Core"] = "Огненное ядро"
L["Fit to screen"] = "Подогнать под размер экрана"
L["Flex"] = "Гибкий"
L["Format large numbers"] = "Формат больших чисел"
L["Frozion"] = "Ледозион"
L["Full Clear + 1 Mask"] = "Полный проход + 1 Маска"
L["Full Clear + 2 Masks"] = "Полный проход + 2 Маски"
L["Full Clear + 3 Masks"] = "Полный проход + 3 Маски"
L["Full Clear + 4 Masks"] = "Полный проход + 4 Маски"
L["Full Clear + 5 Masks"] = "Полный проход + 5 Масок"
L["Full Clear No Masks"] = "Полный проход без масок"
L["Full Objective"] = "Полная задача"
L["Gaelzion"] = "Шторморон"
L["GD"] = "ДЕПО"
L["General settings"] = "Общие настройки"
L["GMBT"] = "ГАМБИТ"
L["Grand Hunt"] = "Великая охота"
L["Grand Hunts: Mythic Reward"] = "Великая охота: эпохальная награда"
L["Grand Hunts: Rare Reward"] = "Великая охота: редкая награда"
L["Grand Hunts: Uncommon Reward"] = "Великая охота: необычная награда"
L["Gravlion"] = "Гравлион"
L["Grizzlerock"] = "Седокамень"
L["Group"] = "Группировать"
L["Guild"] = "Гильдия"
L["HOA"] = "ЧП"
L["HOI"] = "ЧЕРТОГИ"
L["Hold Alt to show all data"] = "Удерживайте Alt для просмотра всей информации"
L["HOV"] = "ЧД"
L["Hover mouse on indicator for details"] = "Наведите мышкой на индикатор для детальной информации"
L["Hunt: Death Elementals"] = "Охота: элементали смерти"
L["Hunt: Shadehounds"] = "Охота: Темные Гончие"
L["Hunt: Soul Eaters"] = "Охота: Пожиратели Душ"
L["Hunt: Winged Soul Eaters"] = "Охота: Крылатые пожиратели душ"
L["Iceblade Trio"] = "Трио ледяных клинков"
L["ID"] = "ДОКИ"
L["Ignore"] = "Игнорировать"
L["Indicators"] = "Индикаторы"
L["Infernum"] = "Инферн"
L["Infested Strongbox"] = "Зараженный сундучок"
L["Instance limit in Broker"] = "Предел подземелий на Расколотых Островах"
L["Instances"] = "Подземелья"
L["Interleave"] = "Смешивать в пределах соединенного сервера"
L["Kain Firebrand"] = "Кайн Жгучее Клеймо"
L["Karantun"] = "Карантун"
L["Keystone report target"] = "Цель отчета по ключам"
L["KR"] = "ГК"
L["Last updated"] = "Последнее обновление"
L["Legion Transmute"] = "Трансмутация Легиона"
L["Lesser Visions of N'Zoth"] = "Малое Видение Н'Зота"
L["Level %d Characters"] = "Персонажи уровня %d"
L["LFG cooldown"] = "Отслеживать время задержки Поиска группы для подземелий"
L["LFR"] = "СПР (LFR)"
L["List categories from the current expansion pack first"] = "Сортировать список категорий по сохраненным подземельям"
L["List raid categories before dungeon categories"] = "Список категорий рейда до категорий подземелий"
L["Loot Aspect Crest Fragment"] = "Добыча Фрагмента гребня Аспекта из пламени Тьмы"
L["Loot Drake Crest Fragment"] = "Добыча Фрагмента гребня дракона из пламени Тьмы"
L["Loot Spark of Shadowflame"] = "Добыча Искры пламени Тьмы"
L["Loot Whelpling Crest Fragment"] = "Добыча Фрагмента гребня дракончика из пламени Тьмы"
L["Loot Wyrm Crest Fragment"] = "Добыча Фрагмента гребня змея из пламени Тьмы"
L["Lord Kazzak"] = "Владыка Каззак"
L["LOWR"] = "НИЗ"
L["Manage"] = "Управление"
L["Mechanized Chest"] = "Механизированный сундук"
L["Miscellaneous Tracking"] = "Разнообразное отслеживание"
L["MISTS"] = "ТТС"
L["ML"] = "ЖИЛА"
L["Mogu Strongbox"] = "Сундучок могу"
L["MOS"] = "УТРОБА"
L["Most recent first"] = "Сначала новые"
L["Mythic Best"] = "Лучший Эпохальный"
L["Mythic Key Best"] = "Лучший эпохальный ключ"
L["Mythic Keystone"] = "Эпохальный ключ"
L["Nathanos Blightcaller"] = "Натанос Гнилостень"
L["Neela Firebane"] = "Нила Гнев Пламени"
L["NELT"] = "НЕЛТАРИЙ"
L["Never show"] = "Никогда не отображать"
L["New Single Quest"] = "Новый одиночный квест"
L["NL"] = "ЛН"
L["NW"] = "СТ"
L["Opacity of the tooltip row highlighting"] = "Прозрачность подсказки подсвеченной строки"
L["Open config"] = "Открыть настройки"
L["Order must be a number in [0 - 999]"] = "Заказ должен быть числом в диапазоне [0 - 999]"
L["Paragon Chests"] = "Сундуки за Репутацию"
L["Party"] = "Группа"
L["Patterns Within Patterns"] = "Patterns Within Patterns"
L["PF"] = "ЧК"
L["Pipspark Thundersnap"] = "Искрописк Громошлепс"
L["Presets"] = "Presets"
L["Primal Storms Core"] = "Primal Storms Core"
L["Primal Storms Elementals"] = "Primal Storms Elementals"
L["Progress Persists"] = "Прогресс сохраняется"
L["Quest ID"] = "ID квеста"
L["Quest Name"] = "Название квеста"
L["Quest progresses"] = "Прогресс квеста"
L["Quest Reset Type"] = "Тип сброса квеста"
L["Raids before dungeons"] = "Рейды перед подземельями"
L["Recent Bonus Rolls"] = "Недавние бонусные броски"
L["Recent Instances"] = "Недавние подземелья"
L["Recover Dailies"] = "Восстановление Ежедневных заданий"
L["Report instance resets to group"] = "Сообщать группе об обновлении подземелья"
L["Researchers Under Fire"] = "Исследователи под огнем"
L["Reset Characters"] = "Сброс персонажей"
L["Reverse ordering"] = "Обратный порядок"
L["RLP"] = "РОЖ"
L["Roll Bonus"] = "Бонусный бросок"
L["Rouen Icewind"] = "Руан Ледяной Ветер"
L["Row Highlight"] = "Подсветка строки"
L["SBG"] = "НпЛ"
L["SD"] = "КК"
L["SEAT"] = "ПТ"
L["Secured Shipment"] = "Защищенные ресурсы"
L["Set All"] = "Установить значение для всех"
L["Show all emissary names"] = "Показать все имена эмиссаров"
L["Show both factions' emissay name"] = "Показать название эмиссаров обеих фракций"
L["Show calling line when all quests completed"] = "Показывать строку завершенного призыва"
L["Show category names"] = "Показывать названия категорий"
L["Show category names in the tooltip"] = "Отображать названия категорий в подсказках"
L["Show cooldown for characters to use battleground system"] = "Показывать время задержки системы Полей битв"
L["Show cooldown for characters to use LFG dungeon system"] = "Показывать время задержки системы Поиска группы для подземелий"
L["Show currency earned"] = "Показывать полученную валюту"
L["Show currency max"] = "Показать максимальную валюту"
L["Show emissary line when all quests completed"] = "Показать линию эмиссара, когда все задания завершены"
L["Show Expired"] = "Показывать истекшие"
L["Show expired instance lockouts"] = "Показывать истекшие сохранённые подземелья"
L["Show Holiday"] = "Показывать События"
L["Show holiday boss rewards"] = "Показывать награду с праздничных боссов"
L["Show minimap button"] = "Показать кнопку миникарты"
L["Show name for a category when all displayed instances belong only to that category"] = "Показать имя для категории для всех отображаемых подземелий, принадлежащих только этой категории"
L["Show only current server"] = "Показывать только текущий сервер"
L["Show Random"] = "Показывать случайный выбор"
L["Show random dungeon bonus reward"] = "Показывать бонусную награду за случайное подземелье"
L["Show self always"] = "Показывать себя всегда"
L["Show self first"] = "Вначале показывать себя"
L["Show server name"] = "Показать название сервера"
L["Show the SavedInstances minimap button"] = "Отображать кнопку SavedInstances у миникарты"
L["Show tooltip hints"] = "Показывать подсказки"
L["Show When"] = "Показывать, если"
L["Show when completed"] = "Показать, когда завершено"
L["Show when saved"] = "Отображать при сохранении"
L["Show/Hide the SavedInstances tooltip"] = "Показать/спрятать подсказку SavedInstances"
L["SIEGE"] = "ОСАДА"
L["Siege on Dragonbane Keep"] = "Осада Драконьей Погибели"
L["Similarly, the words KILLED and TOTAL will be substituted with the number of bosses killed and total in the lockout."] = "Аналогично, слова KILLED и TOTAL будут заменены числом убитых и всего боссов в сохранении."
L["Single category name"] = "Одиночное название категории"
L["SOA"] = "ШП"
L["Sort by currency name"] = "Сортировка по названию валюты"
L["Sort by server"] = "Сорт. по серверам"
L["Sort categories by"] = "Сорт. категории по"
L["Sort Order"] = "Порядок сортировки"
L["Sorting"] = "Сортировка"
L["SOTS"] = "СШ"
L["Space between categories"] = "Промежуток между категориями"
L["Sparks of Life"] = "Искры жизни"
L["Storm Surge"] = "Пробуждение бури"
L["STRT"] = "УЛИЦЫ"
L["TAV"] = "ЛХ"
L["TD"] = "ТД"
L["Text"] = "Текст"
L["The Four Celestials"] = "Четыре небожителя"
L["The World Awaits"] = "The World Awaits"
L["These are the instances that count towards the %i instances per hour account limit, and the time until they expire."] = "Это те подземелья, на которые существуют ограничения в %i подземелий в час."
L["This should only be used for characters who have been renamed or deleted, as characters will be re-populated when you log into them."] = "Используйте только для переименованных или удаленных персонажей, так как данные все равно будут заполнены заново при входе на персонажа."
L["Time /played"] = "Общее время игры"
L["Time Left"] = "Обновится через"
L["Timewalking Weekend Event"] = "Timewalking Weekend Event"
L["Timeworn Mythic Keystone"] = "Старый ключ"
L["TJS"] = "ХНЗ"
L["TNO"] = "НкН"
L["Tooltip Scale"] = "Масштаб подсказки"
L["TOP"] = "Театр"
L["Tormentors of Torghast"] = "Мучители из Торгаста"
L["TOS"] = "ХС"
L["Track Mythic keystone acquisition"] = "Отслеживать полученные эпохальные ключи"
L["Track Mythic keystone best run"] = "Отслеживать лучший заход на эпохальный ключ"
L["Track Timeworn Mythic keystone acquisition"] = "Отслеживать полученные старые ключи"
L["Trade Skill Cooldowns"] = "Восстановление способностей профессий."
L["Trade skills"] = "Отслеживать восстановление способностей профессий"
L["Transmute"] = "Трансмутация (алхимия)"
L["Trial of Elements"] = "Испытание стихий"
L["Trial of Flood"] = "Испытание наводнения"
L["Type"] = "Тип"
L["ULD"] = "УЛЬДАМАН"
L["UNDR"] = "ПОДГН"
L["UPPR"] = "ВЕРХ"
L["Use class color"] = "Цвет класса"
L["User"] = "Пользователь"
L["Vision Boss + 2 Bonus Objectives"] = "Босс Видения + 2 Бонусных цели"
L["Vision Boss Only"] = "Только Босс Видения"
L["Voraazka"] = "Вораазка"
L["VOTW"] = "КС"
L["VP"] = "ВС"
L["Warfronts"] = "Фронты"
L["Warn about instance limit"] = "Предупреждать о пределе подземелий"
L["Warning: You've entered about %i instances recently and are approaching the %i instance per hour limit for your account. More instances should be available in %s."] = "Внимание! За последнее время Вы вошли в %i подземелий и приближаетесь к ограничению в \"%i подземелий в час\" для Вашего аккаунта. Новые подземелья будут доступны через %s."
L["Water"] = "Вода"
L["Water Core"] = "Водяное ядро"
L["Weekly Quests"] = "Еженедельные задания"
L["Wild Transmute"] = "Дикая трансмутация"
L["WM"] = "УУ"
L["WORK"] = "МАСТЕР"
L["Wrath of the Jailer"] = "Гнев Тюремщика"
L["YARD"] = "СВАЛКА"
L["You can combine icons and text in a single indicator if you wish. Simply choose an icon, and insert the word ICON into the text field. Anywhere the word ICON is found, the icon you chose will be substituted in."] = "Вы можете комбинировать иконки и текст в одном индикаторе. Выберите иконку и вставьте слово ICON в текстовое поле. Слово ICON будет автоматически заменено на выбранную иконку."
L["Zurgaz Corebreaker"] = "Зургаз Разрушительница Недр"






end

