local GlobalAddonName, E = ...
local AddonTitle = GetAddOnMetadata(GlobalAddonName, "Title")
--E.modules = {}
--------------------------------------------------------------------------------
local LSM = LibStub("LibSharedMedia-3.0")
--[[SOUND
]]
local GlobalAddonName = ...
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime
LSM:Register("sound", "|cFF00A1FFO_01_ayaya|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\ayaya.ogg]])
LSM:Register("sound", "|cFF00A1FFO_01_Fuck You|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\Fuck You.ogg]])
LSM:Register("sound", "|cFF00A1FFO_01_Hadouken|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\Hadouken.ogg]])
LSM:Register("sound", "|cFF00A1FFO_01_Jojo - The Hand|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\Jojo - The Hand.ogg]])
LSM:Register("sound", "|cFF00A1FFO_01_Jojo - Timestop teleport|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\Jojo - Timestop teleport.ogg]])
LSM:Register("sound", "|cFF00A1FFO_01_Nyaa|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Anime\Nyaa.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\CS
LSM:Register("sound", "|cFF00A2FFO_02_awp|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\CS\awp.ogg]])
LSM:Register("sound", "|cFF00A2FFO_02_usp|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\CS\usp.ogg]])
LSM:Register("sound", "|cFF00A2FFO_02_zoom|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\CS\zoom.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik
LSM:Register("sound", "|cFF00A3FFH_Female 1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik\Female 1.ogg]])
LSM:Register("sound", "|cFF00A3FFH_Female 2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik\Female 2.ogg]])
LSM:Register("sound", "|cFF00A3FFH_Female 3|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik\Female 3.ogg]])
LSM:Register("sound", "|cFF00A3FFH_Female 4|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik\Female 4.ogg]])
LSM:Register("sound", "|cFF00A3FFH_Female 5|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Hostik\Female 5.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes
LSM:Register("sound", "|cFF00A4FFO_04_Batida de porta troll|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Batida de porta troll.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Directed by Robert B Weide|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Directed by Robert B Weide.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Dramatic|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Dramatic.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Dry fart|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Dry fart.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_EAR RAPE Moaning|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\EAR RAPE Moaning.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Ephey|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Ephey.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_ERA RAPE BLYAT|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\ERA RAPE BLYAT.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Gnome Woo|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Gnome Woo.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_rat|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\rat.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Hehe Boy|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Hehe Boy.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Hey thats pretty good|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Hey thats pretty good.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Its a trap|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Its a trap.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Allahu_akbar|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Allahu_akbar.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_AnnihilationGun|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_AnnihilationGun.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Dun_dun_dun|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Dun_dun_dun.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_eeee_ep|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_eeee_ep.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_fbi_open_up|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_fbi_open_up.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_gta_san_andreas_mission_complete|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_gta_san_andreas_mission_complete.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_gta_v_death_sound_effect|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_gta_v_death_sound_effect.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_John_Cena|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_John_Cena.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Loh_pidr|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Loh_pidr.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Murloc|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Murloc.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Nemesis|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Nemesis.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Noo|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Noo.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_ny che - ebaniu|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_ny che - ebaniu.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_ny che - full|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_ny che - full.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_ny che - narod|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_ny che - narod.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_O_kurwa|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_O_kurwa.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Ou_eee|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Ou_eee.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Risitaskekw|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Risitaskekw.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Savage_fap|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Savage_fap.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_The_rap_battle_parody_oh|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_The_rap_battle_parody_oh.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Triggered|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Triggered.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Ultimate_respect|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Ultimate_respect.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Vestige_elephant|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Vestige_elephant.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Zoidberg_whoop|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\O_Zoidberg_whoop.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Omae Wa Mou Shindeiru|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Omae Wa Mou Shindeiru.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Peanut Butter Kid|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Peanut Butter Kid.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Porn Hub|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Porn Hub.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Really Nigga|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Really Nigga.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Ricefields|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Ricefields.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Roblox Death|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Roblox Death.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_WeNeedMoreGold_ENG|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\WeNeedMoreGold_ENG.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_WeNeedMoreGold_RU|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\WeNeedMoreGold_RU.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Surprise motherfucker|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Surprise motherfucker.ogg]])
LSM:Register("sound", "|cFF00A4FFO_04_Why are you running|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Memes\Why are you running.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto
LSM:Register("sound", "|cFF00A5FFO_05_Chidori Kouken1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Chidori Kouken1.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Chidori Kouken2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Chidori Kouken2.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Hand Sign|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Hand Sign.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Jutsu|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Jutsu.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Jutsu2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Jutsu2.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai Throw1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai Throw1.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai Throw2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai Throw2.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai1.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai2.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai3|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai3.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Kunai4|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Kunai4.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Shadow Clone|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Shadow Clone.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Shadow SMS|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Shadow SMS.ogg]])
LSM:Register("sound", "|cFF00A5FFO_05_Teleport|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Naruto\Teleport.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other
LSM:Register("sound", "|cFF00A6FFO_06_Bokudan|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Bokudan.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Dark Souls - You died|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\.Dark Souls - You diedogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Ding|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\.Dingogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Discord1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Discord1.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Discord2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Discord2.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_EAR RAPE Skullsound|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\EAR RAPE Skullsound.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Error|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Error.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Failsafe|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Failsafe.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Fatality|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Fatality.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Finish Him|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Finish Him.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Magic immune|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Magic immune.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_MGS Alert|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\MGS Alert.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Nope|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Nope.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Portal gun - ice|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Portal gun - ice.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Quack|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Quack.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Readycheck|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Readycheck.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Record scratch|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Record scratch.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Sonic|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Sonic.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Teleport valorant|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Teleport valorant.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Teleport1|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Teleport1.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Teleport2|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Teleport2.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_TS3|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\TS3.ogg]])
LSM:Register("sound", "|cFF00A6FFO_06_Windows XP|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\Other\Windows XP.ogg]])
--Interface\Addons\]]..GlobalAddonName..[[\Media\ut4\
LSM:Register("sound", "|cFF00A7FFO_07_01|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\01.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_02|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\02.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_03|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\03.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_04|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\04.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_05|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\05.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_06|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\06.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_07|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\07.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_08|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\08.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_09|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\09.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_10|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\10.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Averted|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Averted.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Combowhore|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Combowhore.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Dominating|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Dominating.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_GodLike|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\GodLike.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_HolyShit|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\HolyShit.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Killing_Spree|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Killing_Spree.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_MegaKill|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\MegaKill.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Monster_kill|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Monster_kill.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Ownage|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Ownage.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Rampage|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Rampage.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Retribution|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Retribution.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_Unstoppable|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\Unstoppable.ogg]])
LSM:Register("sound", "|cFF00A7FFO_07_WhickedSick|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\sound\ut4\WhickedSick.ogg]])
--[[BACKGROUND
]]
--Interface\Addons\]]..GlobalAddonName..[[\Media\background
--[[FONT
]]
--Interface\Addons\]]..GlobalAddonName..[[\Media\font\
--
LSM:Register("font", " |cFF00A3FF01|r |cffFF4C4FOcto|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\01 Octo.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", " |cFF00A3FF02|r |cffFF4C4FOcto-Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\02 Octo-Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF03|r |cffFF4C4FGothamPro-Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\03 GothamPro-Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF04|r |cffFF4C4FGothamPro-Medium|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\04 GothamPro-Medium.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF05|r |cffFF4C4FMontserrat Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\05 Montserrat Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF06|r |cffFF4C4FMonsterrat Black|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\06 Monsterrat Black.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF07|r |cffFF4C4FHomespun TT BRK|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\07 Homespun TT BRK.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF08|r |cffFF4C4FMagistralTT Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\08 MagistralTT Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF09|r |cffFF4C4FPT Sans Narrow Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\09 PT Sans Narrow Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF10|r |cffFF4C4FExpressway Rg Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\10 Expressway Rg Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF11|r |cffFF4C4FVerdana 12px|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\11 Verdana 12px.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF12|r |cffFF4C4FArial 14px|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\12 Arial 14px.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF13|r |cffFF4C4FTimes New Roman 16px|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\13 Times New Roman 16px.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF14|r |cffFF4C4FTahoma 13px|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\14 Tahoma 13px.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF15|r |cffFF4C4FGeorgia 15px|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\15 Georgia 15px.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF16|r |cffFF4C4FSegoe UI|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\16 Segoe UI.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF17|r |cffFF4C4FBigNoodleTitlingCyr|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\17 BigNoodleTitlingCyr.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF18|r |cffFF4C4FRobotoBlack|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\18 RobotoBlack.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF19|r |cffFF4C4FRobotoCondensedBold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\19 RobotoCondensedBold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF20|r |cffFF4C4FMontserrat-Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\20 Montserrat-Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("font", "|cFF00A3FF21|r |cffFF4C4FBitcrusherCdRg-Bold|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\font\21 BitcrusherCdRg-Bold.TTF]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
--[[BORDER
]]
--Interface\Addons\]]..GlobalAddonName..[[\Media\border\
LSM:Register("border", " |cFF00A3FF01|r |cffFF4C4FOcto|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\border\01 Octo.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
--[[STATUSBAR
]]
--Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\
LSM:Register("statusbar", " |cFF00A3FF01|r |cffFF4C4FOcto|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\01 Octo.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", " |cFF00A3FF02|r |cffFF4C4FOcto-Blank|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\02 Octo-Blank.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", " |cFF00A3FF03|r |cffFF4C4FOcto|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\03 Octo.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_03|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_03.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_04|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_04.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_05|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_05.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_06|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_06.blp]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_07|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_07.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_08|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_08.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_09|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_09.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_10|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_10.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_11|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_11.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_12|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_12.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_13|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_13.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_14|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_14.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_15|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_15.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_16|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_16.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_17|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_17.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_18|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_18.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_19|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_19.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_20|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_20.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_21|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_21.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_22|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_22.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF00A3FFO_23|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\O_23.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
--Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\AtrocityUI
LSM:Register("statusbar", "|cFF8e7cc3Atrocity|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\AtrocityUI\Atrocity.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
LSM:Register("statusbar", "|cFF8e7cc3Kait|r", [[Interface\Addons\]]..GlobalAddonName..[[\Media\statusbar\AtrocityUI\Kait.tga]], LSM.LOCALE_BIT_ruRU+LSM.LOCALE_BIT_western)
