
Octo_ToDo_DB_Players = {
	["Player-1615-0B55FBC0"] = {
		["levelCapped20"] = true,
		["hasMail"] = true,
		["loginDay"] = "03.12.2024",
		["GameLimitedMode_IsActive"] = true,
		["bounty_Legion3"] = 0,
		["avgItemLevel"] = 91,
		["specName"] = "Воздаяние",
		["numQuests"] = 13,
		["IsTestBuild"] = nil --[[ skipped inline function ]],
		["IsRestrictedAccount"] = true,
		["bounty_Legion3_end"] = 0,
		["IsTrialAccount"] = false,
		["bounty_Legion3_icon"] = 0,
		["bounty_Legion2_questID"] = 0,
		["Possible_CatalogedResearch"] = 0,
		["Money"] = 4011282,
		["className"] = "Паладин",
		["loginHour"] = "18:53",
		["bounty_BfA2_questID"] = 0,
		["buildDate"] = "Nov 19 2024",
		["avgItemLevelPvp"] = 91,
		["bounty_BfA1_questID"] = 0,
		["bounty_BfA1_end"] = 0,
		["Shadowland"] = {
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			["curCovID"] = 0,
		},
		["classColorHex"] = "|cffF48CBA",
		["Possible_Anima"] = 0,
		["GetRestrictedAccountData_rLevel"] = 20,
		["currentXP"] = 1499,
		["bounty_BfA3_icon"] = 0,
		["bounty_Legion2_icon"] = 0,
		["classId"] = 2,
		["usedSlots"] = 44,
		["RaceLocal"] = "Эльфийка крови",
		["bounty_Legion1_end"] = 0,
		["specId"] = 70,
		["cloak_lvl"] = 0,
		["curServerShort"] = "РФ",
		["tmstp_Weekly"] = 1733284800,
		["normalizedRealm"] = "normalizedRealm",
		["loginDate"] = "03.12.2024 18:53:36",
		["raceID"] = 10,
		["bounty_BfA2_end"] = 0,
		["classFilename"] = "PALADIN",
		["PlayerCanEarnExperience"] = false,
		["numShownEntries"] = 16,
		["bounty_BfA3_end"] = 0,
		["IsPublicBuild"] = true,
		["bounty_Legion1_questID"] = 0,
		["CurrentKeyLevel"] = 0,
		["cloak_res"] = 0,
		["LFGInstance"] = {
			[287] = {
				["donetoday"] = "|cff505050Нет|r",
				["D_name"] = "Корен Худовар",
			},
			[285] = {
				["donetoday"] = "|cff505050Нет|r",
				["D_name"] = "Всадник без головы",
			},
		},
		["Name"] = "Маслен",
		["RIO_weeklyBest_TWW_S1"] = 0,
		["tmstp_Daily"] = 1733284800,
		["WarMode"] = true,
		["isShownPLAYER"] = true,
		["GetRestrictedAccountData_rMoney"] = 10000000,
		["bounty_BfA2_icon"] = 0,
		["tmstp_Month"] = 1734667200,
		["isBeta"] = false,
		["PlayerDurability"] = 96,
		["RaceEnglish"] = "BloodElf",
		["totalSlots"] = 162,
		["BattleTag"] = "Octo#21447",
		["UnitXPMax"] = 19770,
		["time"] = 1733226816,
		["realTotalTime"] = 251792,
		["islandBfA"] = "|cff505050Нет|r",
		["buildNumber"] = "57689",
		["Chromie_canEnter"] = true,
		["CurrentKeyFULL"] = 0,
		["Chromie_inChromieTime"] = true,
		["IsAccountSecured"] = false,
		["GreatVault"] = {
			{
				["progress"] = 22,
				["type"] = "Подземелья",
				["threshold"] = 8,
				["hyperlink_STRING"] = "593, 593, 593",
			},
			{
				["threshold"] = 0,
				["hyperlink_STRING"] = 0,
				["type"] = "",
				["progress"] = 0,
			},
			{
				["progress"] = 0,
				["type"] = "Рейды",
				["hyperlink_STRING"] = 0,
				["threshold"] = 6,
			},
			{
				["threshold"] = 0,
				["hyperlink_STRING"] = 0,
				["type"] = "",
				["progress"] = 0,
			},
			{
				["threshold"] = 0,
				["hyperlink_STRING"] = 0,
				["type"] = "",
				["progress"] = 0,
			},
			{
				["progress"] = 1,
				["type"] = "Мир",
				["hyperlink_STRING"] = 0,
				["threshold"] = 8,
			},
			[0] = {
				["threshold"] = 0,
				["hyperlink_STRING"] = 0,
				["type"] = "",
				["progress"] = 0,
			},
		},
		["bounty_Legion2"] = 0,
		["CurrentLocation"] = "Драконий Погост",
		["bounty_Legion1_icon"] = 0,
		["curServer"] = "Ревущий фьорд",
		["Chromie_UnitChromieTimeID"] = 7,
		["UnitXPPercent"] = 8,
		["needResetMonth"] = false,
		["Faction"] = "Horde",
		["CurrentKey"] = 0,
		["bounty_Legion3_questID"] = 0,
		["RIO_Score_TWW_S1"] = 0,
		["bounty_Legion2_end"] = 0,
		["specRole"] = "DAMAGER",
		["Chromie_name"] = "Падение Короля-лича",
		["GUID"] = "Player-1615-0B55FBC0",
		["BindLocation"] = "Молот Агмара",
		["UnitLevel"] = 20,
		["IsVeteranTrialAccount"] = true,
		["BattleTagLocal"] = "Octo (Retail)",
		["needResetDaily"] = false,
		["specPrimaryStatString"] = "Основная характеристика: сила",
		["maxNumQuestsCanAccept"] = 35,
		["bounty_BfA1_icon"] = 0,
		["journalInstance"] = {
		},
		["guildRankIndex"] = 0,
		["bounty_BfA2"] = 0,
		["bounty_Legion1"] = 0,
		["GetRestrictedAccountData_profCap"] = 0,
		["buildVersion"] = "11.0.5",
		["realLevelTime"] = 224061,
		["currentTier"] = 11,
		["bounty_BfA3"] = 0,
		["bounty_BfA3_questID"] = 0,
		["bounty_BfA1"] = 0,
		["needResetWeekly"] = false,
		["classColor"] = "f48cba",
		["MoneyOnLogin"] = 4011282,
		["avgItemLevelEquipped"] = 90,
		["specIcon"] = 135873,
		["interfaceVersion"] = 110005,
		["HasAvailableRewards"] = true,
		["specPrimaryStat"] = 1,
	},
	["Player-1615-0B228060"] = {
		["levelCapped20"] = false,
		["hasMail"] = false,
		["loginDay"] = "03.12.2024",
		["GameLimitedMode_IsActive"] = true,
		["numQuests"] = 0,
		["IsTrialAccount"] = false,
		["avgItemLevel"] = 0,
		["loginHour"] = "18:53",
		["interfaceVersion"] = 110005,
		["buildDate"] = "Nov 19 2024",
		["Shadowland"] = {
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			{
				0,
				0,
			},
			["curCovID"] = 0,
		},
		["classColorHex"] = "|cffF48CBA",
		["Possible_Anima"] = 0,
		["currentXP"] = 0,
		["classId"] = 1,
		["curServerShort"] = "РФ",
		["raceID"] = 0,
		["classFilename"] = "ROGUE",
		["numShownEntries"] = 0,
		["GetRestrictedAccountData_rLevel"] = 20,
		["CurrentKeyLevel"] = 0,
		["Name"] = "Октобанкрф",
		["className"] = "Разбойница",
		["WarMode"] = false,
		["isShownPLAYER"] = true,
		["GUID"] = "Player-1615-0B228060",
		["tmstp_Month"] = 1734667200,
		["isBeta"] = false,
		["PlayerDurability"] = 100,
		["RaceEnglish"] = "Orc",
		["BattleTag"] = "Octo#21447",
		["UnitXPMax"] = 0,
		["realTotalTime"] = 0,
		["buildVersion"] = "11.0.5",
		["avgItemLevelEquipped"] = 0,
		["CurrentKeyFULL"] = 0,
		["RIO_weeklyBest_TWW_S1"] = 0,
		["IsAccountSecured"] = false,
		["Chromie_UnitChromieTimeID"] = 0,
		["guildRankIndex"] = 0,
		["UnitXPPercent"] = 0,
		["avgItemLevelPvp"] = 0,
		["curServer"] = "Ревущий фьорд",
		["PlayerCanEarnExperience"] = true,
		["LFGInstance"] = {
			[287] = {
				["donetoday"] = "|cff505050Нет|r",
				["D_name"] = "Корен Худовар",
			},
			[285] = {
				["donetoday"] = "|cff505050Нет|r",
				["D_name"] = "Всадник без головы",
			},
		},
		["tmstp_Daily"] = 1733284800,
		["Faction"] = "Horde",
		["CurrentKey"] = 0,
		["RIO_Score_TWW_S1"] = 0,
		["BindLocation"] = 0,
		["CurrentLocation"] = 0,
		["Chromie_name"] = "",
		["guildRankName"] = "",
		["Chromie_canEnter"] = false,
		["loginDate"] = "03.12.2024 18:53:18",
		["UnitLevel"] = 1,
		["IsVeteranTrialAccount"] = false,
		["BattleTagLocal"] = "Octo (Retail)",
		["needResetDaily"] = true,
		["buildNumber"] = "57689",
		["maxNumQuestsCanAccept"] = 0,
		["totalSlots"] = 0,
		["journalInstance"] = {
		},
		["Money"] = 0,
		["normalizedRealm"] = "normalizedRealm",
		["IsPublicBuild"] = true,
		["GetRestrictedAccountData_profCap"] = 0,
		["IsTestBuild"] = false,
		["realLevelTime"] = 0,
		["currentTier"] = 11,
		["time"] = 1733226798,
		["RaceLocal"] = "Орчиха",
		["usedSlots"] = 0,
		["needResetWeekly"] = true,
		["classColor"] = {
			["r"] = 0.5,
			["g"] = 0.5,
			["b"] = 0.5,
		},
		["MoneyOnLogin"] = 0,
		["GetRestrictedAccountData_rMoney"] = 10000000,
		["guildName"] = "",
		["needResetMonth"] = true,
		["Possible_CatalogedResearch"] = 0,
		["HasAvailableRewards"] = false,
		["tmstp_Weekly"] = 1733284800,
	},
}

