MASLENGO.UniversalQuest.Octopussy_ALL_Blingtron_Daily
MASLENGO.UniversalQuest.Octopussy_ALL_BloodElfHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_DarkIronDwarfHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_DwarvenHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_ForsakenHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_GnomeHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_GoblinHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_HighmountainTaurenHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_HumanHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_KulTiranHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_LightforgedDraeneiHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_MagharOrcHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_MechagnomeHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_NightborneHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_NightElfHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_OrcHeritageArmor_Once
MASLENGO.UniversalQuest.Octopussy_ALL_VoidElfHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_VulperaHeritageArmorAllied_Once
MASLENGO.UniversalQuest.Octopussy_ALL_WorgenHeritageArmor_Once

MASLENGO.UniversalQuest.Octopussy_BattleforAzeroth_DarkshoreRares_Daily
MASLENGO.UniversalQuest.Octopussy_BattleforAzeroth_WBNazjatar_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ACalltoBattle_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_CatchingUp_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_DarkmoonFaire_Daily
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_1Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_2Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_3Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_4Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_5Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_6Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_7Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_ALL_Storylines_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_AWorthyAllyDreamWardens_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_BloomingDreamseeds_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_DreamsUnified_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Rares_Daily
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Seeds_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_ACalltoAid_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_ADragoninHand_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_APassedTorch_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_ASleepySearch_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_MemoryoftheDreamer_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_SkyMothersIre_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_TheDryadGarden_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_TheQonzuQuery_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Sidequests_TroubleattheTree_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_TheSuperbloom_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmeraldDream_Treasures_Once
MASLENGO.UniversalQuest.Octopussy_Dragonflight_EmissaryofWar_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_SomethingDifferent_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_SparksofLife_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_SummerFestival_Month
MASLENGO.UniversalQuest.Octopussy_Dragonflight_TheArenaCalls_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_TheBigDig_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_TheEasternKingdomsCupBegins_Month
MASLENGO.UniversalQuest.Octopussy_Dragonflight_TheWorldAwaits_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_WBHibernationHeroes_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_WBZaqaliElders_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZandalariTrollHeritageArmorAllied_ALL
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernAWorthyAllyLoammNiffen_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernEvents_Daily
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernRares_Daily
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernSniffenseeking_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernSniffenseekingItems_Weekly
MASLENGO.UniversalQuest.Octopussy_Dragonflight_ZaralekCavernStorylines_Once
MASLENGO.UniversalQuest.Octopussy_Holiday_Brewfest_BarrelingDown_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_Brewfest_BubblingBrews_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_Brewfest_DirebrewsDireBrew_Month
MASLENGO.UniversalQuest.Octopussy_Holiday_Brewfest_Month
MASLENGO.UniversalQuest.Octopussy_Holiday_DayoftheDead_Once
MASLENGO.UniversalQuest.Octopussy_Holiday_PilgrimsBountyAlliance_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_PilgrimsBountyHorde_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeil_ASmokywoodPasturesThankYouAlliance_Once
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeil_ASmokywoodPasturesThankYouHorde_Once
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeil_YoureaMeanOneAlliance_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeil_YoureaMeanOneHorde_Daily
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeilAlliance_Once
MASLENGO.UniversalQuest.Octopussy_Holiday_WinterVeilHorde_Once

MASLENGO.UniversalQuest.Octopussy_Legion_InvasionQuests_Daily
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaCollection_Daily
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMResearchReportAdaptiveAlloys_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMResearchReportFirstAlloys_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMResearchReportRelicExaminationTechniques_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMTreatiseBondsofStygiainMortals_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMTreatiseRecognizingStygiaanditsUses_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMTreatiseRelicsAboundintheShadowlands_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMTreatiseTheStudyofAnimaandHarnessingEveryDrop_Once
MASLENGO.UniversalQuest.Octopussy_Shadowlands_KorthiaITEMVaultAnimaTracker_Once








MASLENGO.UniversalQuest.Octopussy_TheWarWithin_Delve_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_DungeonQuest_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_MajorKeyflames_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_MinorKeyflames_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_TheTheaterTroupe_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_WorldBoss_Weekly
MASLENGO.UniversalQuest.Octopussy_TheWarWithin_Worldsoul_Weekly @#!@#!@#!@#
MASLENGO.UniversalQuest.Octopussy_Timewalk_ATimetoReflect_Weekly
MASLENGO.UniversalQuest.Octopussy_Timewalk_CelebrateGoodFun_Weekly
MASLENGO.UniversalQuest.Octopussy_Timewalk_ChromiesCodex_Weekly
MASLENGO.UniversalQuest.Octopussy_Timewalk_Dungeons_Weekly
MASLENGO.UniversalQuest.Octopussy_Timewalk_Raid_Weekly
MASLENGO.UniversalQuest.Octopussy_Timewalk_SoldierofTime_Weekly