-- local GlobalAddonName, E = ...
-- local L = LibStub("AceLocale-3.0"):GetLocale("Octo")
-- ----------------------------------------------------------------
-- local currentSTATE = 13
-- 
-- E.OctoTables_DataOtrisovka[currentSTATE] = {}
-- E.OctoTables_Vibor[currentSTATE] = {}
-- E.OctoTables_Vibor[currentSTATE].icon = E.OctoTable_Expansions[currentSTATE].icon
-- E.OctoTables_Vibor[currentSTATE].name = E.OctoTable_Expansions[currentSTATE].color..E.OctoTable_Expansions[currentSTATE].name
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Currencies = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Items = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Reputations = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].UniversalQuests = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Additionally = {

-- }
-- ----------------------------------------------------------------
-- function E.func_Otrisovka_13_TheLastTitan()
-- 	local OctoTable_Otrisovka_textCENT = {}
-- 	----------------------------------------------------------------
-- 	----------------------------------------------------------------
-- 	----------------------------------------------------------------
-- 	if Octo_ToDo_DB_Vars.ExpansionToShow[currentSTATE] then
-- 		E.func_Otrisivka_CURRENCIESnITEMS(OctoTable_Otrisovka_textCENT, currentSTATE)
-- 		E.func_Universal(OctoTable_Otrisovka_textCENT, currentSTATE)
-- 		E.func_Otrisovka_REPUTATION(OctoTable_Otrisovka_textCENT, currentSTATE)
-- 	end
-- 	----------------------------------------------------------------
-- 	----------------------------------------------------------------
-- 	----------------------------------------------------------------
-- 	return OctoTable_Otrisovka_textCENT
-- end