-- local GlobalAddonName, E = ...
-- local L = LibStub("AceLocale-3.0"):GetLocale("Octo")
-- ----------------------------------------------------------------
-- local currentSTATE = 13
-- E.OctoTables_DataOtrisovka[currentSTATE] = {}
-- E.OctoTables_Vibor[currentSTATE] = {}
-- E.OctoTables_Vibor[currentSTATE].icon = E.OctoTable_Expansions[currentSTATE].icon
-- E.OctoTables_Vibor[currentSTATE].name = E.OctoTable_Expansions[currentSTATE].color..E.OctoTable_Expansions[currentSTATE].name
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Currencies = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Items = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].Reputations = {
-- }
-- ----------------------------------------------------------------
-- E.OctoTables_DataOtrisovka[currentSTATE].UniversalQuests = {
-- }
-- ----------------------------------------------------------------
-- E.func_TableConcat(E.ALL_Currencies, E.OctoTables_DataOtrisovka[currentSTATE].Currencies)
-- E.func_TableConcat(E.ALL_Items, E.OctoTables_DataOtrisovka[currentSTATE].Items)
-- E.func_TableConcat(E.ALL_Reputations, E.OctoTables_DataOtrisovka[currentSTATE].Reputations)
-- E.func_TableConcat(E.ALL_UniversalQuests, E.OctoTables_DataOtrisovka[currentSTATE].UniversalQuests)