local GlobalAddonName, E = ... -- ns
----------------------------------------------------------------
E.MainAddonName = GlobalAddonName
OctoEngine = E -- в других аддонах
E.OctoTables_Vibor = {}
E.ALL_Currencies = {}
E.ALL_Items = {}
E.ALL_Reputations = {}
E.ALL_UniversalQuests = {}
E.ALL_Additionally = {}
E.First_Option = {}
E.Second_Option = {}
E.ActiveHoliday = {}
E.altStrategies = {}
E.Fourth_Option = {}
E.Holiday = {}
E.KeyStoneTBL = {}
E.Modules = {}
E.OctoTable_Expansions = {}
E.OctoTable_Frames = {}
E.OctoTable_GarrisonBuildingIDs = {}
E.OctoTable_itemID_ALL = {}
E.OctoTable_itemID_AutoOpen = {}
E.OctoTable_itemID_Cataloged_Research = {}
E.OctoTable_itemID_Ignore_List = {}
E.OctoTable_itemID_ItemsDelete = {}
E.OctoTable_itemID_ItemsUsable = {}
E.OctoTable_itemID_ItemsUsable_Other = {}
E.OctoTable_itemID_MECHAGON = {}
E.OctoTable_KeystoneAbbr = {}
E.OctoTable_LFGDungeons = {}
E.OctoTable_Mounts = {}
E.OctoTable_Portals = {}
E.OctoTable_QuestID = {}
E.OctoTable_QuestID_Paragon = {}
E.OctoTable_RemixInfinityResearch = {}
E.OctoTable_ReputationsDB = {}
E.OctoTable_SavedVariables = {}
E.OctoTables_DataOtrisovka = {}
E.Octo_ProfessionsskillLine = {}
E.Octo_ProfessionsskillLine_Other = {}
E.strategies = {}
E.Third_Option = {}
E.Timers = {}
-- local dataMeta = {
-- __index = {
-- Currencies = {},
-- Items = {},
-- Reputations = {},
-- UniversalQuests = {},
-- Additionally = {},
-- }
-- }
-- for i = 1, 15 do
-- E.OctoTables_DataOtrisovka[i] = setmetatable({}, dataMeta)
-- end
E.newOTRISOVKA = {}
E.newOTRISOVKA2 = {}