local GlobalAddonName, E = ...
--------------------------------------------------------------------------------
local qwe = {
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2697] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Chase's test faction (DNT)", side = "-", },
	[2645] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Земельники", side = "-", },
	[2604] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Команда Бочконога (идеал)", side = "-", },
	[2569] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "The War Within", side = "-", },
	[2554] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Тогус", side = "-", },
	[2522] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Тирай", side = "-", },
	[2513] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Он'ир", side = "-", },
	[2512] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Айлааг", side = "-", },
	[2509] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Шикаар", side = "-", },
	[2506] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Dragonflight", side = "-", },
	[2431] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Owen Test", side = "-", },
	[2422] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ночной народец", side = "-", },
	[2414] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Темные Земли", side = "-", },
	[2265] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кул-Тирас - долина Штормов", side = "-", },
	[2264] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кул-Тирас - Друствар", side = "-", },
	[2167] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Защитники Аргуса (идеал)", side = "-", },
	[2120] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кул-Тирас - Тирагард", side = "Alliance", },
	[2104] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Battle for Azeroth", side = "-", },
	[2063] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Arne Test - Paragon Reputation Stormwind", side = "-", },
	[1834] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Legion", side = "-", },
	[1444] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Warlords of Draenor", side = "-", },
	[1245] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Mists of Pandaria", side = "-", },
	[1162] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Cataclysm", side = "-", },
	[1118] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "World of Warcraft", side = "-", },
	[1097] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Wrath of the Lich King", side = "-", },
	[1072] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "[DNT] AC Major Faction Child Renown Test", side = "-", },
	[949] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Тестовая фракция 1", side = "-", },
	[948] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Тестовая фракция 2", side = "-", },
	[980] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "The Burning Crusade", side = "-", },
	[892] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Силы Орды", side = "-", },
	[891] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Силы Альянса", side = "-", },
	[2695] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Test Account Wide Stormwind (DNT)", side = "Alliance", },
	[1169] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Гильдия", side = "-", },
	[2166] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Армия Света (идеал)", side = "-", },
	[2091] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Армия погибели Легиона (идеал)", side = "-", },
	[2090] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Стражи (идеал)", side = "-", },
	[2089] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Помраченные (идеал)", side = "-", },
	[2088] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ткачи Снов (идеал)", side = "-", },
	[2087] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Двор Фарондиса (идеал)", side = "-", },
	[2086] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Валарьяры (идеал)", side = "-", },
	[2085] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Племена Крутогорья (идеал)", side = "-", },
	[1989] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Лунные стражи", side = "-", },
	[1947] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Иллидари", side = "-", },
	[1888] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Яндвикские врайкулы", side = "-", },
	[2693] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Путь участника вылазки (1-й сезон)", side = "-", },
	[2683] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Вылазки: 2-й сезон", side = "-", },
	[2667] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картели Нижней Шахты (идеал)", side = "-", },
	[2644] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Вылазки: 1-й сезон", side = "-", },
	[2613] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ассамблея глубин (идеал)", side = "-", },
	[2612] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Совет Дорногала (идеал)", side = "-", },
	[2611] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Арати Тайносводья (идеал)", side = "-", },
	[2596] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Отрезанные нити (идеал)", side = "-", },
	[2649] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Генерал (идеал)", side = "-", },
	[2648] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Прядильщица (идеал)", side = "-", },
	[2647] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Визирь (идеал)", side = "-", },
	[2684] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клуб лояльности Галаджио (идеал)", side = "-", },
	[2676] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картель Хитрой Шестеренки (идеал)", side = "-", },
	[2674] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картель Черноводья (идеал)", side = "-", },
	[2672] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картель Трюмных Вод (идеал)", side = "-", },
	[2670] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Торговая компания (идеал)", side = "-", },
	[2668] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Мрачные Решалы (идеал)", side = "-", },
	[2575] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Стражи Сна (идеал)", side = "-", },
	[2565] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Лоаммские ниффы (идеал)", side = "-", },
	[2555] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Кейган", side = "-", },
	[2552] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Союз Вальдраккена (идеал)", side = "-", },
	[2551] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Искарские клыкарры (идеал)", side = "-", },
	[2542] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Укхел", side = "-", },
	[2521] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Нокуд (идеал)", side = "-", },
	[2520] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Клан Нокхуд", side = "-", },
	[2508] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Драконья экспедиция (идеал)", side = "-", },
	[2504] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кентавры Маруук (идеал)", side = "-", },
	[2479] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Просветленные (идеал)", side = "-", },
	[2474] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ве'нари (идеал)", side = "-", },
	[2473] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кодекс архивариуса (идеал)", side = "-", },
	[2471] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Легион Смерти (идеал)", side = "-", },
	[2444] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Дикая Охота (Идеал)", side = "-", },
	[2442] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Двор Жнецов (Идеал)", side = "-", },
	[2441] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Перерожденные (Идеал)", side = "-", },
	[2440] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Неумирающая армия (Идеал)", side = "-", },
	[2418] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ульдумский союз (идеал)", side = "-", },
	[2416] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Раджани (идеал)", side = "-", },
	[2401] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Анкоа из клана Клинков Волн (идеал)", side = "-", },
	[2392] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ржавоболтское сопротивление (идеал)", side = "-", },
	[2387] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Тортолланские искатели (идеал)", side = "-", },
	[2386] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Защитники Азерот (идеал)", side = "-", },
	[2385] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Армия Чести (идеал)", side = "-", },
	[2384] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "7-й легион (идеал)", side = "-", },
	[2383] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Орден Пылающих Углей (идеал)", side = "-", },
	[2382] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Жители Вол'дуна (идеал)", side = "-", },
	[2381] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Орден Возрождения Шторма (идеал)", side = "-", },
	[2380] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Экспедиция Таланджи (идеал)", side = "-", },
	[2379] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Адмиралтейство Праудмуров (идеал)", side = "-", },
	[2378] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Империя Зандалари (идеал)", side = "-", },
	[2374] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Освобожденные (идеал)", side = "-", },
	[1861] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Arcane Thirst (Silgryn) DEPRECATED", side = "-", },
	[1815] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Выжившие из Гилнеаса", side = "-", },
	[1984] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Спасатели", side = "-", },
	[1899] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Лунные стражи", side = "-", },
	[2111] = {icon = 236192, icon2 = "", itemREP = "", name = "Зандаларские динозавры", side = "-", },
	[1520] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Изгнанники клана Призрачной Луны", side = "-", },
	[1735] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Телохранители из казарм", side = "-", },
	[1351] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Хмелевары", side = "-", },
	[1216] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Академия Шан Си", side = "-", },
	[1440] = {icon = 666624, icon2 = "", itemREP = "", name = "Восстание Черного Копья", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2653] = {icon = "Interface\\ICONS\\UI_MajorFactions_Rocket", icon2 = "", itemREP = "", name = "Картели Нижней Шахты", side = "-", },
	[2640] = {icon = 604882, icon2 = "", itemREP = "", name = "Бранн Бронзобород", side = "-", },
	[2600] = {icon = "Interface\\ICONS\\UI_MajorFactions_web", icon2 = "", itemREP = "", name = "Отрезанные нити", side = "-", },
	[2594] = {icon = "Interface\\ICONS\\UI_MajorFactions_candle", icon2 = "", itemREP = "", name = "Ассамблея глубин", side = "-", },
	[2590] = {icon = "Interface\\ICONS\\UI_MajorFactions_storm", icon2 = "", itemREP = "", name = "Совет Дорногала", side = "-", },
	[2570] = {icon = "Interface\\ICONS\\UI_MajorFactions_flame", icon2 = "", itemREP = "", name = "Арати Тайносводья", side = "-", },
	[2607] = {icon = 5862763, icon2 = "", itemREP = "", name = "Визирь", side = "-", },
	[2605] = {icon = 5862762, icon2 = "", itemREP = "", name = "Генерал", side = "-", },
	[2601] = {icon = 5862764, icon2 = "", itemREP = "", name = "Прядильщица", side = "-", },
	[2685] = {icon = "Interface\\ICONS\\UI_MajorFactions_stars", icon2 = "", itemREP = "", name = "Клуб лояльности Галаджио", side = "-", },
	[2677] = {icon = 632354, icon2 = "", itemREP = "", name = "Картель Хитрой Шестеренки", side = "-", },
	[2675] = {icon = 632354, icon2 = "", itemREP = "", name = "Картель Черноводья", side = "-", },
	[2673] = {icon = 632354, icon2 = "", itemREP = "", name = "Картель Трюмных Вод", side = "-", },
	[2671] = {icon = 632354, icon2 = "", itemREP = "", name = "Торговая компания", side = "-", },
	[2669] = {icon = 133714, icon2 = "", itemREP = "", name = "Мрачные Решалы", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2510] = {icon = 4638429, icon2 = "", itemREP = "", name = "Союз Вальдраккена", side = "-", },
	[2507] = {icon = 454065, icon2 = "", itemREP = "", name = "Драконья экспедиция", side = "-", },
	[2503] = {icon = 2101975, icon2 = "", itemREP = "", name = "Кентавры Маруук", side = "-", },
	[2511] = {icon = 629056, icon2 = "", itemREP = "", name = "Искарские клыкарры", side = "-", },
	[2574] = {icon = 1394953, icon2 = "", itemREP = "", name = "Стражи Сна", side = "-", },
	[2568] = {icon = 604882, icon2 = "", itemREP = "", name = "Гонщик Мерцающего Огга", side = "-", },
	[2564] = {icon = 237477, icon2 = "", itemREP = "", name = "Лоаммские ниффы", side = "-", },
	[2526] = {icon = 4905324, icon2 = "", itemREP = "", name = "Фурболги из клана Зимней Шкуры", side = "-", },
	[2553] = {icon = 604882, icon2 = "", itemREP = "", name = "Соридорми", side = "-", },
	[2550] = {icon = 4191562, icon2 = "", itemREP = "", name = "Кобальтовая ассамблея", side = "-", },
	[2544] = {icon = 604882, icon2 = "", itemREP = "", name = "Консорциум ремесленников – филиал на Драконьих островах", side = "-", },
	[2518] = {icon = 604882, icon2 = "", itemREP = "", name = "Сабеллиан", side = "-", },
	[2517] = {icon = 604882, icon2 = "", itemREP = "", name = "Гневион", side = "-", },
	[2615] = {icon = 1391545, icon2 = "", itemREP = "", name = "Азеротские Архивы", side = "-", },
	[2593] = {icon = 5690395, icon2 = "", itemREP = "", name = "Команда Бочконога", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2478] = {icon = 4280206, icon2 = "", itemREP = "", name = "Просветленные", side = "-", },
	[2472] = {icon = 4191562, icon2 = "", itemREP = "", name = "Кодекс архивариуса", side = "-", },
	[2470] = {icon = 4083292, icon2 = "", itemREP = "", name = "Легион Смерти", side = "-", },
	[2469] = {icon = 3762255, icon2 = "", itemREP = "", name = "Понимание фракталов", side = "-", },


	[2465] = {icon = 3517784, icon2 = E.ICON_NIGHTFAE, itemREP = "", name = "Дикая Охота", side = "-", },
	[2464] = {icon = 604882, icon2 = E.ICON_NIGHTFAE, itemREP = "", name = "Двор Ночи", side = "-", },
	[2463] = {icon = 604882, icon2 = E.ICON_NIGHTFAE, itemREP = "", name = "Чесночник", side = "-", },
	[2462] = {icon = 604882, icon2 = E.ICON_NECROLORD, itemREP = "", name = "Штопальщики", side = "-", },
	[2439] = {icon = 3514227, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Нераскаявшиеся", side = "-", },
	[2432] = {icon = 4216713, icon2 = "", itemREP = "", name = "Ве'нари", side = "-", },
	[2413] = {icon = 3540525, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Двор Жнецов", side = "-", },
	[2410] = {icon = 3604102, icon2 = E.ICON_NECROLORD, itemREP = "", name = "Неумирающая армия", side = "-", },
	[2407] = {icon = 3555147, icon2 = E.ICON_KYRIAN, itemREP = "", name = "Перерожденные", side = "-", },


	[2445] = {icon = 3601527, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Пепельный двор", side = "-", },
	[2461] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Изобретатель чумы Марилет", side = "-", },
	[2460] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Камнелоб", side = "-", },
	[2459] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Сика", side = "-", },
	[2458] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Клейя и Пелагий", side = "-", },
	[2457] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Великий мастер Воул", side = "-", },
	[2456] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Дроман Алиот", side = "-", },
	[2455] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Хранитель склепа Каззир", side = "-", },
	[2454] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Чуфа", side = "-", },
	[2453] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Рендл и Дуборыл", side = "-", },
	[2452] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Полемарх Адрест", side = "-", },
	[2451] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Капитан-егерь Корейн", side = "-", },
	[2450] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Александрос Могрейн", side = "-", },
	[2449] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Графиня", side = "-", },
	[2448] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Миканикос", side = "-", },
	[2447] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Леди Лунная Ягода", side = "-", },
	[2446] = {icon = 604882, icon2 = E.ICON_VENTHYR, itemREP = "", name = "Баронесса Вайш", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- BFA
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2427] = {icon = 604882, icon2 = "", itemREP = "", name = "Молодой акир", side = "-", },
	[2417] = {icon = 3204478, icon2 = "", itemREP = "", name = "Ульдумский союз", side = "-", },
	[2415] = {icon = 3204479, icon2 = "", itemREP = "", name = "Раджани", side = "-", },
	[2391] = {icon = 2921023, icon2 = "", itemREP = "", name = "Ржавоболтское сопротивление", side = "-", },
	[2164] = {icon = 2029406, icon2 = "", itemREP = "", name = "Защитники Азерот", side = "-", },
	[2163] = {icon = 2065717, icon2 = "", itemREP = "", name = "Тортолланские искатели", side = "-", },
	[2157] = {icon = 2024073, icon2 = "", itemREP = "", name = "Армия Чести", side = "Horde", },
	[2373] = {icon = 2821776, icon2 = "", itemREP = "", name = "Освобожденные", side = "Horde", },
	[2158] = {icon = 2057295, icon2 = "", itemREP = "", name = "Жители Вол'дуна", side = "Horde", },
	[2103] = {icon = 2015853, icon2 = "", itemREP = "", name = "Империя Зандалари", side = "Horde", },
	[2156] = {icon = 2043330, icon2 = "", itemREP = "", name = "Экспедиция Таланджи", side = "Horde", },
	[2233] = {icon = 1391545, icon2 = "", itemREP = "", name = "Dino Training - Pterrodax", side = "Horde", },
	[2370] = {icon = 604882, icon2 = "", itemREP = "", name = "Обучение динозавров – Дикорог", side = "Horde", },
	[2390] = {icon = 604882, icon2 = "", itemREP = "", name = "Вим Соленодух", side = "Horde", },
	[2389] = {icon = 604882, icon2 = "", itemREP = "", name = "Нери Остроерш", side = "Horde", },
	[2388] = {icon = 666624, icon2 = "", itemREP = "", name = "Поэн Солежабрик", side = "Horde", },
	[2159] = {icon = 2024072, icon2 = "", itemREP = "", name = "7-й легион", side = "Alliance", },
	[2400] = {icon = 2921024, icon2 = "", itemREP = "", name = "Клинки Волн", side = "Alliance", },
	[2160] = {icon = 2012311, icon2 = "", itemREP = "", name = "Адмиралтейство Праудмуров", side = "Alliance", },
	[2162] = {icon = 2027009, icon2 = "", itemREP = "", name = "Орден Возрождения Шторма", side = "Alliance", },
	[2161] = {icon = 2012312, icon2 = "", itemREP = "", name = "Орден Пылающих Углей", side = "Alliance", },
	[2395] = {icon = 3066347, icon2 = "", itemREP = "", name = "Улей Медокрылов", side = "Alliance", },
	[2398] = {icon = 604882, icon2 = "", itemREP = "", name = "Фуражир из улья Медокрылов", side = "Alliance", },
	[2397] = {icon = 604882, icon2 = "", itemREP = "", name = "Пчеломатка улья Медокрылов", side = "Alliance", },
	[2396] = {icon = 604882, icon2 = "", itemREP = "", name = "Трутень из улья Медокрылов", side = "Alliance", },
	[2376] = {icon = 604882, icon2 = "", itemREP = "", name = "Оракул Ори", side = "Alliance", },
	[2375] = {icon = 604882, icon2 = "", itemREP = "", name = "Мастер охоты Акана", side = "Alliance", },
	[2377] = {icon = 604882, icon2 = "", itemREP = "", name = "Мастер клинка Иновари", side = "Alliance", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[2170] = {icon = 1708511, icon2 = "", itemREP = "", name = "Защитники Аргуса", side = "-", },
	[2165] = {icon = 1608729, icon2 = "", itemREP = 249780, name = "Армия Света", side = "-", },
	[2045] = {icon = 1585245, icon2 = "", itemREP = 249784, name = "Армия погибели Легиона", side = "-", },
	[2018] = {icon = 1531511, icon2 = "", itemREP = "", name = "Отмщение Когтя", side = "-", },
	[1948] = {icon = 1447611, icon2 = "", itemREP = 249782, name = "Валарьяры", side = "-", },
	[1900] = {icon = 1447607, icon2 = "", itemREP = 249787, name = "Двор Фарондиса", side = "-", },
	[1894] = {icon = 1447613, icon2 = "", itemREP = 249781, name = "Стражи", side = "-", },
	[1883] = {icon = 1447610, icon2 = "", itemREP = 249786, name = "Ткачи Снов", side = "-", },
	[1859] = {icon = 1447608, icon2 = "", itemREP = 249783, name = "Помраченные", side = "-", },
	[1828] = {icon = 1447612, icon2 = "", itemREP = 249785, name = "Племена Крутогорья", side = "-", },
	[2097] = {icon = 604882, icon2 = "", itemREP = "", name = "Илиссия Водная", side = "-", },
	[2099] = {icon = 604882, icon2 = "", itemREP = "", name = "Акуле Речной Рог", side = "-", },
	[2101] = {icon = 604882, icon2 = "", itemREP = "", name = "Ша'лет", side = "-", },
	[2100] = {icon = 604882, icon2 = "", itemREP = "", name = "Корбин", side = "-", },
	[2102] = {icon = 604882, icon2 = "", itemREP = "", name = "Бесс", side = "-", },
	[2098] = {icon = 604882, icon2 = "", itemREP = "", name = "Хранительница Рейна", side = "-", },
	[1919] = {icon = 1391545, icon2 = "", itemREP = "", name = "Жажда магии Вальтруа", side = "-", },
	[1862] = {icon = 1391545, icon2 = "", itemREP = "", name = "Жажда магии Окулета", side = "-", },
	[1860] = {icon = 1391545, icon2 = "", itemREP = "", name = "Жажда магии Талисры", side = "-", },
	[2135] = {icon = 4191562, icon2 = "", itemREP = "", name = "Хроми", side = "-", },
	[1975] = {icon = 604882, icon2 = "", itemREP = "", name = "Кудесник Маргосс", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- DRAENOR
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[1850] = {icon = 1240657, icon2 = "", itemREP = "", name = "Охотники за саблеронами", side = "-", },
	[1849] = {icon = 1240656, icon2 = "", itemREP = "", name = "Орден Пробудившихся", side = "-", },
	[1732] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Дренорcкая Экспедиция Хитрой Шестеренки", side = "-", },
	[1711] = {icon = 1052654, icon2 = "", itemREP = "", name = "Археологическое общество Хитрой Шестеренки", side = "-", },
	[1515] = {icon = 1042646, icon2 = "", itemREP = "", name = "Араккоа-изгои", side = "-", },
	----------------------------------------------------------------
	[1708] = {icon = 1043559, icon2 = "", itemREP = "", name = "Клан Веселого Черепа", side = "Horde", },
	[1445] = {icon = 1044164, icon2 = "", itemREP = "", name = "Клан Северного Волка", side = "Horde", },
	[1848] = {icon = 1122137, icon2 = "", itemREP = "", name = "Охотники за головами", side = "Horde", },
	----------------------------------------------------------------
	[1731] = {icon = 1048727, icon2 = "", itemREP = "", name = "Совет экзархов", side = "Alliance", },
	[1710] = {icon = 1042739, icon2 = "", itemREP = "", name = "Защитники Ша'тар", side = "Alliance", },
	[1847] = {icon = 1122137, icon2 = "", itemREP = "", name = "Длань Пророка", side = "Alliance", },
	----------------------------------------------------------------
	[1741] = {icon = 666623, icon2 = "", itemREP = "", name = "Леорадж", side = "-", },
	[1740] = {icon = 666623, icon2 = "", itemREP = "", name = "Аеда Ясная Заря", side = "-", },
	[1739] = {icon = 666623, icon2 = "", itemREP = "", name = "Вивианна", side = "-", },
	[1738] = {icon = 666623, icon2 = "", itemREP = "", name = "Защитница Иллона", side = "-", },
	[1737] = {icon = 666623, icon2 = "", itemREP = "", name = "Жрец Когтя Ишааль", side = "-", },
	[1736] = {icon = 666623, icon2 = "", itemREP = "", name = "Тормок", side = "-", },
	[1733] = {icon = 666623, icon2 = "", itemREP = "", name = "Делвар Железный Кулак", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- PANDA
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[1492] = {icon = 901300, icon2 = "", itemREP = "", name = "Император Шаохао", side = "-", },
	[1435] = {icon = 838811, icon2 = "", itemREP = "", name = "Натиск Шадо-Пан", side = "-", },
	[1359] = {icon = 397907, icon2 = "", itemREP = "", name = "Черный принц", side = "-", },
	[1345] = {icon = 645218, icon2 = "", itemREP = "", name = "Хранители истории", side = "-", },
	[1341] = {icon = 645203, icon2 = "", itemREP = "", name = "Небожители", side = "-", },
	[1337] = {icon = 646377, icon2 = "", itemREP = "", name = "Клакси", side = "-", },
	[1302] = {icon = 643874, icon2 = "", itemREP = "", name = "Рыболовы", side = "-", },
	[1272] = {icon = 645198, icon2 = "", itemREP = "", name = "Земледельцы", side = "-", },
	[1271] = {icon = 646324, icon2 = "", itemREP = "", name = "Орден Облачного Змея", side = "-", },
	[1270] = {icon = 645204, icon2 = "", itemREP = "", name = "Шадо-Пан", side = "-", },
	[1269] = {icon = 643910, icon2 = "", itemREP = "", name = "Золотой Лотос", side = "-", },
	[1283] = {icon = 604882, icon2 = "", itemREP = "", name = "Фермер Фун", side = "-", },
	[1282] = {icon = 604882, icon2 = "", itemREP = "", name = "Рыба Тростниковая Шкура", side = "-", },
	[1281] = {icon = 604882, icon2 = "", itemREP = "", name = "Джина Грязный Коготь", side = "-", },
	[1280] = {icon = 604882, icon2 = "", itemREP = "", name = "Тина Грязный Коготь", side = "-", },
	[1279] = {icon = 604882, icon2 = "", itemREP = "", name = "Хаохань Грязный Коготь", side = "-", },
	[1278] = {icon = 604882, icon2 = "", itemREP = "", name = "Шо", side = "-", },
	[1277] = {icon = 604882, icon2 = "", itemREP = "", name = "Чи-Чи", side = "-", },
	[1276] = {icon = 604882, icon2 = "", itemREP = "", name = "Старик Горная Лапа", side = "-", },
	[1275] = {icon = 604882, icon2 = "", itemREP = "", name = "Элла", side = "-", },
	[1273] = {icon = 604882, icon2 = "", itemREP = "", name = "Йогу Пьяный", side = "-", },
	[1358] = {icon = 604882, icon2 = "", itemREP = "", name = "Нат Пэгл", side = "-", },
	[1357] = {icon = 604882, icon2 = "", itemREP = "", name = "Номи", side = "-", },
	[1388] = {icon = 838819, icon2 = "", itemREP = "", name = "Войска Похитителей Солнца", side = "Horde", },
	[1375] = {icon = 463451, icon2 = "", itemREP = "", name = "Армия Покорителей", side = "Horde", },
	[1228] = {icon = 1542852, icon2 = "", itemREP = "", name = "Лесные хозены", side = "Horde", },
	[1387] = {icon = 801132, icon2 = "", itemREP = "", name = "Армия Кирин-Тора", side = "Alliance", },
	[1376] = {icon = 463450, icon2 = "", itemREP = "", name = "Операция \"Заслон\"", side = "Alliance", },
	[1242] = {icon = 1542852, icon2 = "", itemREP = "", name = "Цзинь-юй Жемчужного Плавника", side = "Alliance", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- CATACLYSM
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[1204] = {icon = 135805, icon2 = "", itemREP = "", name = "Хиджальские мстители", side = "-", },
	[1173] = {icon = 456574, icon2 = "", itemREP = "", name = "Рамкахены", side = "-", },
	[1171] = {icon = 456572, icon2 = "", itemREP = "", name = "Теразан", side = "-", },
	[1158] = {icon = 456570, icon2 = "", itemREP = "", name = "Стражи Хиджала", side = "-", },
	[1135] = {icon = 456567, icon2 = "", itemREP = "", name = "Служители Земли", side = "-", },
	[1178] = {icon = 456571, icon2 = "", itemREP = "", name = "Батальон Адского Крика", side = "Horde", },
	[1172] = {icon = 456565, icon2 = "", itemREP = "", name = "Клан Драконьей Пасти", side = "Horde", },
	[1177] = {icon = 456564, icon2 = "", itemREP = "", name = "Защитники Тол Барада", side = "Alliance", },
	[1174] = {icon = 456575, icon2 = "", itemREP = "", name = "Клан Громового Молота", side = "Alliance", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- Wrath of the Lich King
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[1156] = {icon = 313914, icon2 = "", itemREP = "", name = "Пепельный союз", side = "-", },
	[1119] = {icon = 236241, icon2 = "", itemREP = "", name = "Сыны Ходира", side = "-", },
	[1106] = {icon = 133441, icon2 = "", itemREP = "", name = "Серебряный Авангард", side = "-", },
	[1098] = {icon = 135309, icon2 = "", itemREP = "", name = "Рыцари Черного Клинка", side = "-", },
	[1091] = {icon = 134158, icon2 = "", itemREP = "", name = "Драконий союз", side = "-", },
	[1090] = {icon = 135933, icon2 = "", itemREP = "", name = "Кирин-Тор", side = "-", },
	[1073] = {icon = 132933, icon2 = "", itemREP = "", name = "Калу'ак", side = "-", },
	----------------------------------------------------------------
	[1117] = {icon = 236817, icon2 = "", itemREP = "", name = "Низина Шолазар", side = "-", },
	[1105] = {icon = 134418, icon2 = "", itemREP = "", name = "Оракулы", side = "-", },
	[1104] = {icon = 237427, icon2 = "", itemREP = "", name = "Племя Бешеного Сердца", side = "-", },
	----------------------------------------------------------------
	[1052] = {icon = 463451, icon2 = "", itemREP = "", name = "Экспедиция Орды", side = "Horde", },
	[1124] = {icon = 134473, icon2 = "", itemREP = "", name = "Похитители Солнца", side = "Horde", },
	[1085] = {icon = 463451, icon2 = "", itemREP = "", name = "Армия Песни Войны", side = "Horde", },
	[1067] = {icon = 463451, icon2 = "", itemREP = "", name = "Карающая Длань", side = "Horde", },
	[1064] = {icon = 463451, icon2 = "", itemREP = "", name = "Таунка", side = "Horde", },
	----------------------------------------------------------------
	[1037] = {icon = 463450, icon2 = "", itemREP = "", name = "Авангард Альянса", side = "Alliance", },
	[1094] = {icon = 134472, icon2 = "", itemREP = "", name = "Серебряный Союз", side = "Alliance", },
	[1126] = {icon = 463450, icon2 = "", itemREP = "", name = "Зиморожденные", side = "Alliance", },
	[1068] = {icon = 463450, icon2 = "", itemREP = "", name = "Лига исследователей", side = "Alliance", },
	[1050] = {icon = 463450, icon2 = "", itemREP = "", name = "Экспедиция Отважных", side = "Alliance", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- The Burning Crusade
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[1038] = {icon = 135026, icon2 = "", itemREP = "", name = "Огри'ла", side = "-", },
	[1015] = {icon = 132250, icon2 = "", itemREP = "", name = "Крылья Пустоты", side = "-", },
	[1012] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Пеплоусты-служители", side = "-", },
	[990] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Песчаная Чешуя", side = "-", },
	[989] = {icon = 135026, icon2 = "", itemREP = "", name = "Хранители Времени", side = "-", },
	[970] = {icon = 135026, icon2 = "", itemREP = "", name = "Спореггар", side = "-", },
	[967] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Аметистовое Око", side = "-", },
	[942] = {icon = 135026, icon2 = "", itemREP = "", name = "Кенарийская экспедиция", side = "-", },
	[933] = {icon = 135026, icon2 = "", itemREP = "", name = "Консорциум", side = "-", },
	[922] = {icon = 135026, icon2 = "", itemREP = "", name = "Транквиллион", side = "Horde", },
	----------------------------------------------------------------
	[936] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Город Шаттрат", side = "-", },
	----------------------------------------------------------------
	[1077] = {icon = 135026, icon2 = "", itemREP = "", name = "Армия Расколотого Солнца", side = "-", },
	[1031] = {icon = 135026, icon2 = "", itemREP = "", name = "Стражи небес Ша'тар", side = "-", },
	[1011] = {icon = 135026, icon2 = "", itemREP = "", name = "Нижний Город", side = "-", },
	[935] = {icon = 135026, icon2 = "", itemREP = "", name = "Ша'тар", side = "-", },
	[934] = {icon = 135026, icon2 = "", itemREP = "", name = "Провидцы", side = "-", },
	[932] = {icon = 135026, icon2 = "", itemREP = "", name = "Алдоры", side = "-", },
	----------------------------------------------------------------
	[947] = {icon = 463451, icon2 = "", itemREP = "", name = "Траллмар", side = "Horde", },
	[941] = {icon = 463451, icon2 = "", itemREP = "", name = "Маг'хары", side = "Horde", },
	----------------------------------------------------------------
	[946] = {icon = 463450, icon2 = "", itemREP = "", name = "Оплот Чести", side = "Alliance", },
	[978] = {icon = 463450, icon2 = "", itemREP = "", name = "Куренай", side = "Alliance", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	-- World of Warcraft
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
	[910] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Род Ноздорму", side = "-", },
	[909] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Ярмарка Новолуния", side = "-", },
	[809] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Шен'дралар", side = "-", },
	[749] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Гидраксианские Повелители Вод", side = "-", },
	[609] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Круг Кенария", side = "-", },
	[589] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Укротители ледопардов", side = "Alliance", },
	[576] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Древобрюхи", side = "-", },
	[529] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Серебряный Рассвет", side = "-", },
	[469] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Альянс", side = "Alliance", },
	[349] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Черный Ворон", side = "-", },
	[270] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Племя Зандалари", side = "-", },
	[169] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картель Хитрой Шестеренки", side = "-", },
	[93] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кентавры из племени Маграм", side = "-", },
	[92] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кентавры из племени Гелкис", side = "-", },
	[87] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Пираты Кровавого Паруса", side = "-", },
	[70] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Синдикат", side = "-", },
	[67] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Орда", side = "Horde", },
	[59] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Братство Тория", side = "-", },
	[577] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Круговзор", side = "-", },
	[470] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Кабестан", side = "-", },
	[369] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Прибамбасск", side = "-", },
	[21] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Пиратская Бухта", side = "-", },
	[2372] = {icon = 666624, icon2 = "", itemREP = "", name = "Арена \"Морд'Бой\"", side = "Horde", },
	[2010] = {icon = 666624, icon2 = "", itemREP = "", name = "Арена \"Морд'Бой\" (3-й сезон)", side = "Horde", },
	[1690] = {icon = 666624, icon2 = "", itemREP = "", name = "Арена \"Морд'Бой\" (сезон 2)", side = "Horde", },
	[1681] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Копье Вол'джина", side = "Horde", },
	[1374] = {icon = 666624, icon2 = "", itemREP = "", name = "Арена \"Морд'Бой\" (сезон 1)", side = "Horde", },
	[889] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Всадники Песни Войны", side = "Horde", },
	[729] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Азеротский клан Северного Волка", side = "Horde", },
	[510] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Осквернители", side = "Horde", },
	[2523] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Темные Когти", side = "Horde", },
	[1352] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Пандарены Хоцзинь", side = "Horde", },
	[1133] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Картель Трюмных Вод", side = "Horde", },
	[911] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Луносвет", side = "Horde", },
	[530] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Племя Черного Копья", side = "Horde", },
	[81] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Громовой Утес", side = "Horde", },
	[76] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Оргриммар", side = "Horde", },
	[68] = {icon = 255236, icon2 = "", itemREP = "", name = "Подгород", side = "Horde", },
	[2371] = {icon = 666623, icon2 = "", itemREP = "", name = "Потасовочная \"У Бизмо\"", side = "Alliance", },
	[2011] = {icon = 666624, icon2 = "", itemREP = "", name = "Потасовочная \"У Бизмо\" (3-й сезон)", side = "Alliance", },
	[1691] = {icon = 666624, icon2 = "", itemREP = "", name = "Потасовочная \"У Бизмо\" (сезон 2)", side = "Alliance", },
	[1682] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Авангард Ринна", side = "Alliance", },
	[1419] = {icon = 666623, icon2 = "", itemREP = "", name = "Потасовочная \"У Бизмо\" (сезон 1)", side = "Alliance", },
	[890] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Среброкрылые Часовые", side = "Alliance", },
	[730] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Стража Грозовой Вершины", side = "Alliance", },
	[509] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Лига Аратора", side = "Alliance", },
	[2524] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Обсидиановые Хранители", side = "Alliance", },
	[1353] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Пандарены Тушуй", side = "Alliance", },
	[1134] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Гилнеас", side = "Alliance", },
	[930] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Экзодар", side = "Alliance", },
	[72] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Штормград", side = "Alliance", },
	[69] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Дарнас", side = "Alliance", },
	[54] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Гномреган", side = "Alliance", },
	[47] = {icon = E.ICON_QUESTION_MARK, icon2 = "", itemREP = "", name = "Стальгорн", side = "Alliance", },
	[1168] = {icon = 135026, icon2 = "", itemREP = "", name = "Гильдия", side = "-", },
	----------------------------------------------------------------
	----------------------------------------------------------------
	----------------------------------------------------------------
}