local GlobalAddonName, E = ...
----------------------------------------------------------------
-- E.Octo_Table_ProfCurr = {
-- 	[129] = {
-- 		name = "FirstAid",
-- 		DRAGONFLIGHT = {
-- 			currency = nil
-- 		},
-- 		TWW = {
-- 			currency = nil
-- 		},
-- 		MIDNIGHT = {
-- 			currency = nil
-- 		},
-- 	},
-- 	[164] = {
-- 		name = "Blacksmithing", -- WorldofWarcraft
-- 		DRAGONFLIGHT = {
-- 			currency = 2035
-- 		},
-- 		TWW = {
-- 			currency = 2786
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3151
-- 		},
-- 	},
-- 	[165] = {
-- 		name = "Leatherworking",
-- 		DRAGONFLIGHT = {
-- 			currency = 2025
-- 		},
-- 		TWW = {
-- 			currency = 2792
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3157
-- 		},
-- 	},
-- 	[171] = {
-- 		name = "Alchemy",
-- 		DRAGONFLIGHT = {
-- 			currency = 2024
-- 		},
-- 		TWW = {
-- 			currency = 2785
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3150
-- 		},
-- 	},
-- 	[182] = {
-- 		name = "Herbalism",
-- 		DRAGONFLIGHT = {
-- 			currency = 2034
-- 		},
-- 		TWW = {
-- 			currency = 2789
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3154
-- 		},
-- 	},
-- 	[185] = {
-- 		name = "Cooking",
-- 		DRAGONFLIGHT = {
-- 			currency = nil
-- 		},
-- 		TWW = {
-- 			currency = nil
-- 		},
-- 		MIDNIGHT = {
-- 			currency = nil
-- 		},
-- 	},
-- 	[186] = {
-- 		name = "Mining",
-- 		DRAGONFLIGHT = {
-- 			currency = 2035
-- 		},
-- 		TWW = {
-- 			currency = 2793
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3158
-- 		},
-- 	},
-- 	[197] = {
-- 		name = "Tailoring",
-- 		DRAGONFLIGHT = {
-- 			currency = 2026
-- 		},
-- 		TWW = {
-- 			currency = 2795
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3160
-- 		},
-- 	},
-- 	[202] = {
-- 		name = "Engineering",
-- 		DRAGONFLIGHT = {
-- 			currency = 2027
-- 		},
-- 		TWW = {
-- 			currency = 2788
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3153
-- 		},
-- 	},
-- 	[333] = {
-- 		name = "Enchanting",
-- 		DRAGONFLIGHT = {
-- 			currency = 2030
-- 		},
-- 		TWW = {
-- 			currency = 2787
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3152
-- 		},
-- 	},
-- 	[356] = {
-- 		name = "Fishing",
-- 		DRAGONFLIGHT = {
-- 			currency = nil
-- 		},
-- 		TWW = {
-- 			currency = nil
-- 		},
-- 		MIDNIGHT = {
-- 			currency = nil
-- 		},
-- 	},
-- 	[393] = {
-- 		name = "Skinning",
-- 		DRAGONFLIGHT = {
-- 			currency = 2033
-- 		},
-- 		TWW = {
-- 			currency = 2794
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3159
-- 		},
-- 	},
-- 	[755] = {
-- 		name = "Jewelcrafting",
-- 		DRAGONFLIGHT = {
-- 			currency = 2029
-- 		},
-- 		TWW = {
-- 			currency = 2791
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3156
-- 		},
-- 	},
-- 	[773] = {
-- 		name = "Inscription", -- BurningCrusade
-- 		DRAGONFLIGHT = {
-- 			currency = 2028
-- 		},
-- 		TWW = {
-- 			currency = 2790
-- 		},
-- 		MIDNIGHT = {
-- 			currency = 3155
-- 		},
-- 	},
-- 	[794] = {
-- 		name = "Archaeology", -- WrathoftheLichKing
-- 		DRAGONFLIGHT = {
-- 			currency = nil
-- 		},
-- 		TWW = {
-- 			currency = nil
-- 		},
-- 		MIDNIGHT = {
-- 			currency = nil
-- 		},
-- 	},
-- 	-- Cataclysm
-- }
-- for k, SkillLineID in next,(E.Octo_Table_ProfCurr) do
-- 	if SkillLineID.DRAGONFLIGHT then
-- 	end
-- end