local GlobalAddonName, E = ...
----------------------------------------------------------------
E.Octo_Table_SI_IDS = {
	[33] = {
		["name"] = "Shadowfang Keep",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
		},
		["JI_ID"] = 64,
		["SI_ID"] = 33,
	},
	[552] = {
		["name"] = "The Arcatraz",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 254,
		["SI_ID"] = 552,
	},
	[2830] = {
		["name"] = "Eco-Dome Al'dani",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1303,
		["SI_ID"] = 2830,
	},
	[1228] = {
		["name"] = "Highmaul",
		["tier"] = 6,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 7,
			[16] = 7,
			[15] = 7,
			[17] = 7,
		},
		["JI_ID"] = 477,
		["SI_ID"] = 1228,
	},
	[43] = {
		["name"] = "Wailing Caverns",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			8,
		},
		["JI_ID"] = 240,
		["SI_ID"] = 43,
	},
	[967] = {
		["name"] = "Dragon Soul",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			nil,
			nil,
			8,
			8,
			8,
			8,
			8,
		},
		["JI_ID"] = 187,
		["SI_ID"] = 967,
	},
	[47] = {
		["name"] = "Razorfen Kraul",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			5,
		},
		["JI_ID"] = 234,
		["SI_ID"] = 47,
	},
	[389] = {
		["name"] = "Ragefire Chasm",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			4,
		},
		["JI_ID"] = 226,
		["SI_ID"] = 389,
	},
	[553] = {
		["name"] = "The Botanica",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[24] = 5,
		},
		["JI_ID"] = 257,
		["SI_ID"] = 553,
	},
	[585] = {
		["name"] = "Magisters' Terrace",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 249,
		["SI_ID"] = 585,
	},
	[649] = {
		["name"] = "Trial of the Crusader",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 5,
			[6] = 5,
			[4] = 5,
			[5] = 5,
		},
		["JI_ID"] = 757,
		["SI_ID"] = 649,
	},
	[1358] = {
		["name"] = "Upper Blackrock Spire",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
		},
		["JI_ID"] = 559,
		["SI_ID"] = 1358,
	},
	[1677] = {
		["name"] = "Cathedral of Eternal Night",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 4,
			[23] = 4,
		},
		["JI_ID"] = 900,
		["SI_ID"] = 1677,
	},
	[70] = {
		["name"] = "Uldaman",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			8,
		},
		["JI_ID"] = 239,
		["SI_ID"] = 70,
	},
	[650] = {
		["name"] = "Trial of the Champion",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 284,
		["SI_ID"] = 650,
	},
	[90] = {
		["name"] = "Gnomeregan",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			5,
		},
		["JI_ID"] = 231,
		["SI_ID"] = 90,
	},
	[1001] = {
		["name"] = "Scarlet Halls",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 311,
		["SI_ID"] = 1001,
	},
	[555] = {
		["name"] = "Shadow Labyrinth",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 253,
		["SI_ID"] = 555,
	},
	[619] = {
		["name"] = "Ahn'kahet: The Old Kingdom",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			5,
		},
		["JI_ID"] = 271,
		["SI_ID"] = 619,
	},
	[938] = {
		["name"] = "End Time",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 5,
			[24] = 5,
		},
		["JI_ID"] = 184,
		["SI_ID"] = 938,
	},
	[556] = {
		["name"] = "Sethekk Halls",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			2,
			3,
		},
		["JI_ID"] = 252,
		["SI_ID"] = 556,
	},
	[939] = {
		["name"] = "Well of Eternity",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 3,
		},
		["JI_ID"] = 185,
		["SI_ID"] = 939,
	},
	[1492] = {
		["name"] = "Maw of Souls",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 727,
		["SI_ID"] = 1492,
	},
	[557] = {
		["name"] = "Mana-Tombs",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			4,
			[24] = 4,
		},
		["JI_ID"] = 250,
		["SI_ID"] = 557,
	},
	[1493] = {
		["name"] = "Vault of the Wardens",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
			[24] = 5,
		},
		["JI_ID"] = 707,
		["SI_ID"] = 1493,
	},
	[940] = {
		["name"] = "Hour of Twilight",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 3,
		},
		["JI_ID"] = 186,
		["SI_ID"] = 940,
	},
	[1175] = {
		["name"] = "Bloodmaul Slag Mines",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 385,
		["SI_ID"] = 1175,
	},
	[1004] = {
		["name"] = "Scarlet Monastery",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 316,
		["SI_ID"] = 1004,
	},
	[558] = {
		["name"] = "Auchenai Crypts",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			2,
			2,
		},
		["JI_ID"] = 247,
		["SI_ID"] = 558,
	},
	[1176] = {
		["name"] = "Shadowmoon Burial Grounds",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 537,
		["SI_ID"] = 1176,
	},
	[2217] = {
		["name"] = "Ny'alotha, the Waking City",
		["tier"] = 8,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 12,
			[16] = 12,
			[15] = 12,
			[17] = 12,
		},
		["JI_ID"] = 1180,
		["SI_ID"] = 2217,
	},
	[2859] = {
		["name"] = "The Blinding Vale",
		["tier"] = 12,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1309,
		["SI_ID"] = 2859,
	},
	[1753] = {
		["name"] = "Seat of the Triumvirate",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 4,
			[23] = 4,
		},
		["JI_ID"] = 945,
		["SI_ID"] = 1753,
	},
	[2096] = {
		["name"] = "Crucible of Storms",
		["tier"] = 8,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 2,
			[16] = 2,
			[15] = 2,
			[17] = 2,
		},
		["JI_ID"] = 1177,
		["SI_ID"] = 2096,
	},
	[560] = {
		["name"] = "Old Hillsbrad Foothills",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 251,
		["SI_ID"] = 560,
	},
	[2097] = {
		["name"] = "Operation: Mechagon",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 8,
			[23] = 8,
		},
		["JI_ID"] = 1178,
		["SI_ID"] = 2097,
	},
	[624] = {
		["name"] = "Vault of Archavon",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 4,
			[4] = 4,
		},
		["JI_ID"] = 753,
		["SI_ID"] = 624,
	},
	[329] = {
		["name"] = "Stratholme - Service Entrance",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			6,
			[24] = 6,
		},
		["JI_ID"] = 1292,
		["SI_ID"] = 329,
	},
	[2481] = {
		["name"] = "Sepulcher of the First Ones",
		["tier"] = 9,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 11,
			[16] = 11,
			[15] = 11,
			[17] = 11,
		},
		["JI_ID"] = 1195,
		["SI_ID"] = 2481,
	},
	[720] = {
		["name"] = "Firelands",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 7,
			[33] = 7,
			[15] = 7,
		},
		["JI_ID"] = 78,
		["SI_ID"] = 720,
	},
	[1007] = {
		["name"] = "Scholomance",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[24] = 5,
		},
		["JI_ID"] = 246,
		["SI_ID"] = 1007,
	},
	[409] = {
		["name"] = "Molten Core",
		["tier"] = 1,
		["isRaid"] = true,
		["difficulties"] = {
			[9] = 10,
		},
		["JI_ID"] = 741,
		["SI_ID"] = 409,
	},
	[1182] = {
		["name"] = "Auchindoun",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 547,
		["SI_ID"] = 1182,
	},
	[1501] = {
		["name"] = "Black Rook Hold",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 740,
		["SI_ID"] = 1501,
	},
	[229] = {
		["name"] = "Lower Blackrock Spire",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			9,
		},
		["JI_ID"] = 229,
		["SI_ID"] = 229,
	},
	[1008] = {
		["name"] = "Mogu'shan Vaults",
		["tier"] = 5,
		["isRaid"] = true,
		["difficulties"] = {
			nil,
			nil,
			6,
			6,
			6,
			6,
			6,
		},
		["JI_ID"] = 317,
		["SI_ID"] = 1008,
	},
	[658] = {
		["name"] = "Pit of Saron",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 278,
		["SI_ID"] = 658,
	},
	[1009] = {
		["name"] = "Heart of Fear",
		["tier"] = 5,
		["isRaid"] = true,
		["difficulties"] = {
			nil,
			nil,
			6,
			6,
			6,
			6,
			6,
		},
		["JI_ID"] = 330,
		["SI_ID"] = 1009,
	},
	[531] = {
		["name"] = "Temple of Ahn'Qiraj",
		["tier"] = 1,
		["isRaid"] = true,
		["difficulties"] = {
			[9] = 9,
		},
		["JI_ID"] = 744,
		["SI_ID"] = 531,
	},
	[595] = {
		["name"] = "The Culling of Stratholme",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 279,
		["SI_ID"] = 595,
	},
	[755] = {
		["name"] = "Lost City of the Tol'vir",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 69,
		["SI_ID"] = 755,
	},
	[532] = {
		["name"] = "Karazhan",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 11,
		},
		["JI_ID"] = 745,
		["SI_ID"] = 532,
	},
	[564] = {
		["name"] = "Black Temple",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 9,
			[33] = 9,
		},
		["JI_ID"] = 751,
		["SI_ID"] = 564,
	},
	[1762] = {
		["name"] = "Kings' Rest",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			[24] = 4,
			[2] = 4,
			[23] = 4,
		},
		["JI_ID"] = 1041,
		["SI_ID"] = 1762,
	},
	[1571] = {
		["name"] = "Court of Stars",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			[24] = 3,
			[2] = 3,
			[23] = 3,
		},
		["JI_ID"] = 800,
		["SI_ID"] = 1571,
	},
	[724] = {
		["name"] = "The Ruby Sanctum",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 1,
			[6] = 1,
			[4] = 1,
			[5] = 1,
		},
		["JI_ID"] = 761,
		["SI_ID"] = 724,
	},
	[1011] = {
		["name"] = "Siege of Niuzao Temple",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 324,
		["SI_ID"] = 1011,
	},
	[533] = {
		["name"] = "Naxxramas",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 15,
			[4] = 15,
		},
		["JI_ID"] = 754,
		["SI_ID"] = 533,
	},
	[565] = {
		["name"] = "Gruul's Lair",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 2,
		},
		["JI_ID"] = 746,
		["SI_ID"] = 565,
	},
	[230] = {
		["name"] = "Blackrock Depths",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			18,
		},
		["JI_ID"] = 228,
		["SI_ID"] = 230,
	},
	[725] = {
		["name"] = "The Stonecore",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 67,
		["SI_ID"] = 725,
	},
	[757] = {
		["name"] = "Baradin Hold",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 3,
			[4] = 3,
		},
		["JI_ID"] = 75,
		["SI_ID"] = 757,
	},
	[534] = {
		["name"] = "The Battle for Mount Hyjal",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 5,
		},
		["JI_ID"] = 750,
		["SI_ID"] = 534,
	},
	[1448] = {
		["name"] = "Hellfire Citadel",
		["tier"] = 6,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 13,
			[16] = 13,
			[15] = 13,
			[17] = 13,
		},
		["JI_ID"] = 669,
		["SI_ID"] = 1448,
	},
	[2651] = {
		["name"] = "Darkflame Cleft",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1210,
		["SI_ID"] = 2651,
	},
	[2912] = {
		["name"] = "The Voidspire",
		["tier"] = 13,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 6,
			[16] = 6,
			[15] = 6,
			[17] = 6,
		},
		["JI_ID"] = 1307,
		["SI_ID"] = 2912,
	},
	[1861] = {
		["name"] = "Uldir",
		["tier"] = 8,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1031,
		["SI_ID"] = 1861,
	},
	[599] = {
		["name"] = "Halls of Stone",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 277,
		["SI_ID"] = 599,
	},
	[631] = {
		["name"] = "Icecrown Citadel",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 12,
			[6] = 12,
			[4] = 12,
			[5] = 12,
		},
		["JI_ID"] = 758,
		["SI_ID"] = 631,
	},
	[2296] = {
		["name"] = "Castle Nathria",
		["tier"] = 9,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 10,
			[16] = 10,
			[15] = 10,
			[17] = 10,
		},
		["JI_ID"] = 1190,
		["SI_ID"] = 2296,
	},
	[2805] = {
		["name"] = "Windrunner Spire",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1299,
		["SI_ID"] = 2805,
	},
	[1195] = {
		["name"] = "Iron Docks",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 558,
		["SI_ID"] = 1195,
	},
	[2923] = {
		["name"] = "Voidscar Arena",
		["tier"] = 12,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1313,
		["SI_ID"] = 2923,
	},
	[269] = {
		["name"] = "The Black Morass",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 255,
		["SI_ID"] = 269,
	},
	[568] = {
		["name"] = "Zul'Aman",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			6,
			6,
		},
		["JI_ID"] = 77,
		["SI_ID"] = 568,
	},
	[600] = {
		["name"] = "Drak'Tharon Keep",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 273,
		["SI_ID"] = 600,
	},
	[632] = {
		["name"] = "The Forge of Souls",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			2,
			2,
			[24] = 2,
		},
		["JI_ID"] = 280,
		["SI_ID"] = 632,
	},
	[2915] = {
		["name"] = "Nexus-Point Xenas",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1316,
		["SI_ID"] = 2915,
	},
	[349] = {
		["name"] = "Maraudon",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			8,
		},
		["JI_ID"] = 232,
		["SI_ID"] = 349,
	},
	[1516] = {
		["name"] = "The Arcway",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 5,
			[23] = 5,
		},
		["JI_ID"] = 726,
		["SI_ID"] = 1516,
	},
	[48] = {
		["name"] = "Blackfathom Deeps",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			8,
		},
		["JI_ID"] = 227,
		["SI_ID"] = 48,
	},
	[2874] = {
		["name"] = "Maisara Caverns",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1315,
		["SI_ID"] = 2874,
	},
	[2515] = {
		["name"] = "The Azure Vault",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1203,
		["SI_ID"] = 2515,
	},
	[429] = {
		["name"] = "Dire Maul - Warpwood Quarter",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			[24] = 4,
		},
		["JI_ID"] = 1276,
		["SI_ID"] = 429,
	},
	[2516] = {
		["name"] = "The Nokhud Offensive",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1198,
		["SI_ID"] = 2516,
	},
	[2811] = {
		["name"] = "Magisters' Terrace",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1300,
		["SI_ID"] = 2811,
	},
	[2825] = {
		["name"] = "Den of Nalorakk",
		["tier"] = 12,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1311,
		["SI_ID"] = 2825,
	},
	[2070] = {
		["name"] = "Battle of Dazar'alor",
		["tier"] = 8,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 9,
			[16] = 9,
			[15] = 9,
			[17] = 9,
		},
		["JI_ID"] = 1176,
		["SI_ID"] = 2070,
	},
	[509] = {
		["name"] = "Ruins of Ahn'Qiraj",
		["tier"] = 1,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 6,
		},
		["JI_ID"] = 743,
		["SI_ID"] = 509,
	},
	[2769] = {
		["name"] = "Liberation of Undermine",
		["tier"] = 11,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1296,
		["SI_ID"] = 2769,
	},
	[1136] = {
		["name"] = "Siege of Orgrimmar",
		["tier"] = 5,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 14,
			[16] = 14,
			[15] = 14,
			[17] = 14,
		},
		["JI_ID"] = 369,
		["SI_ID"] = 1136,
	},
	[602] = {
		["name"] = "Halls of Lightning",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 275,
		["SI_ID"] = 602,
	},
	[2520] = {
		["name"] = "Brackenhide Hollow",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1196,
		["SI_ID"] = 2520,
	},
	[2648] = {
		["name"] = "The Rookery",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1268,
		["SI_ID"] = 2648,
	},
	[2521] = {
		["name"] = "Ruby Life Pools",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1202,
		["SI_ID"] = 2521,
	},
	[1456] = {
		["name"] = "Eye of Azshara",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
			[24] = 5,
		},
		["JI_ID"] = 716,
		["SI_ID"] = 1456,
	},
	[1520] = {
		["name"] = "Invasion Points",
		["tier"] = 7,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 6,
			[16] = 6,
			[15] = 6,
			[17] = 6,
		},
		["JI_ID"] = 959,
		["SI_ID"] = 1520,
	},
	[2657] = {
		["name"] = "Nerub-ar Palace",
		["tier"] = 11,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1273,
		["SI_ID"] = 2657,
	},
	[1648] = {
		["name"] = "Trial of Valor",
		["tier"] = 7,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 3,
			[16] = 3,
			[15] = 3,
			[17] = 3,
		},
		["JI_ID"] = 861,
		["SI_ID"] = 1648,
	},
	[603] = {
		["name"] = "Ulduar",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 14,
			[33] = 13,
		},
		["JI_ID"] = 759,
		["SI_ID"] = 603,
	},
	[2774] = {
		["name"] = "Khaz Algar",
		["tier"] = 11,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 6,
		},
		["JI_ID"] = 1278,
		["SI_ID"] = 2774,
	},
	[2652] = {
		["name"] = "The Stonevault",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1269,
		["SI_ID"] = 2652,
	},
	[2773] = {
		["name"] = "Operation: Floodgate",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1298,
		["SI_ID"] = 2773,
	},
	[1458] = {
		["name"] = "Neltharion's Lair",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 767,
		["SI_ID"] = 1458,
	},
	[2526] = {
		["name"] = "Algeth'ar Academy",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1201,
		["SI_ID"] = 2526,
	},
	[540] = {
		["name"] = "The Shattered Halls",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			4,
			[24] = 4,
		},
		["JI_ID"] = 259,
		["SI_ID"] = 540,
	},
	[2527] = {
		["name"] = "Halls of Infusion",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1204,
		["SI_ID"] = 2527,
	},
	[859] = {
		["name"] = "Zul'Gurub",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			9,
			9,
		},
		["JI_ID"] = 76,
		["SI_ID"] = 859,
	},
	[2662] = {
		["name"] = "The Dawnbreaker",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1270,
		["SI_ID"] = 2662,
	},
	[668] = {
		["name"] = "Halls of Reflection",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 276,
		["SI_ID"] = 668,
	},
	[1651] = {
		["name"] = "Return to Karazhan",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 10,
			[23] = 10,
		},
		["JI_ID"] = 860,
		["SI_ID"] = 1651,
	},
	[1205] = {
		["name"] = "Blackrock Foundry",
		["tier"] = 6,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 10,
			[16] = 10,
			[15] = 10,
			[17] = 10,
		},
		["JI_ID"] = 457,
		["SI_ID"] = 1205,
	},
	[2649] = {
		["name"] = "Priory of the Sacred Flame",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1267,
		["SI_ID"] = 2649,
	},
	[2913] = {
		["name"] = "March on Quel'Danas",
		["tier"] = 13,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 2,
			[16] = 2,
			[15] = 2,
			[17] = 2,
		},
		["JI_ID"] = 1308,
		["SI_ID"] = 2913,
	},
	[2669] = {
		["name"] = "City of Threads",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1274,
		["SI_ID"] = 2669,
	},
	[36] = {
		["name"] = "Deadmines",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			6,
			[24] = 7,
		},
		["JI_ID"] = 63,
		["SI_ID"] = 36,
	},
	[2660] = {
		["name"] = "Ara-Kara, City of Echoes",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1271,
		["SI_ID"] = 2660,
	},
	[669] = {
		["name"] = "Blackwing Descent",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 6,
			[6] = 6,
			[4] = 6,
			[5] = 6,
		},
		["JI_ID"] = 73,
		["SI_ID"] = 669,
	},
	[2549] = {
		["name"] = "Amirdrassil, the Dream's Hope",
		["tier"] = 10,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 9,
			[16] = 9,
			[15] = 9,
			[17] = 9,
		},
		["JI_ID"] = 1207,
		["SI_ID"] = 2549,
	},
	[2661] = {
		["name"] = "Cinderbrew Meadery",
		["tier"] = 11,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1272,
		["SI_ID"] = 2661,
	},
	[2522] = {
		["name"] = "Vault of the Incarnates",
		["tier"] = 10,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1200,
		["SI_ID"] = 2522,
	},
	[542] = {
		["name"] = "The Blood Furnace",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 256,
		["SI_ID"] = 542,
	},
	[574] = {
		["name"] = "Utgarde Keep",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 285,
		["SI_ID"] = 574,
	},
	[1208] = {
		["name"] = "Grimrail Depot",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
			[24] = 3,
		},
		["JI_ID"] = 536,
		["SI_ID"] = 1208,
	},
	[2574] = {
		["name"] = "Dragon Isles",
		["tier"] = 10,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 6,
			[16] = 6,
			[15] = 6,
			[17] = 6,
		},
		["JI_ID"] = 1205,
		["SI_ID"] = 2574,
	},
	[670] = {
		["name"] = "Grim Batol",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 71,
		["SI_ID"] = 670,
	},
	[2792] = {
		["name"] = "Blackrock Depths",
		["tier"] = 1,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1301,
		["SI_ID"] = 2792,
	},
	[1209] = {
		["name"] = "Skyreach",
		["tier"] = 13,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 476,
		["SI_ID"] = 1209,
	},
	[2579] = {
		["name"] = "Dawn of the Infinite",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 8,
			[23] = 8,
		},
		["JI_ID"] = 1209,
		["SI_ID"] = 2579,
	},
	[543] = {
		["name"] = "Hellfire Ramparts",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 248,
		["SI_ID"] = 543,
	},
	[575] = {
		["name"] = "Utgarde Pinnacle",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 286,
		["SI_ID"] = 575,
	},
	[2451] = {
		["name"] = "Uldaman: Legacy of Tyr",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
		},
		["JI_ID"] = 1197,
		["SI_ID"] = 2451,
	},
	[2285] = {
		["name"] = "Spires of Ascension",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1186,
		["SI_ID"] = 2285,
	},
	[671] = {
		["name"] = "The Bastion of Twilight",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 4,
			[6] = 5,
			[4] = 4,
			[5] = 5,
		},
		["JI_ID"] = 72,
		["SI_ID"] = 671,
	},
	[2286] = {
		["name"] = "The Necrotic Wake",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1182,
		["SI_ID"] = 2286,
	},
	[1466] = {
		["name"] = "Darkheart Thicket",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 762,
		["SI_ID"] = 1466,
	},
	[129] = {
		["name"] = "Razorfen Downs",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			5,
		},
		["JI_ID"] = 233,
		["SI_ID"] = 129,
	},
	[544] = {
		["name"] = "Magtheridon's Lair",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 1,
		},
		["JI_ID"] = 747,
		["SI_ID"] = 544,
	},
	[576] = {
		["name"] = "The Nexus",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[24] = 5,
		},
		["JI_ID"] = 281,
		["SI_ID"] = 576,
	},
	[608] = {
		["name"] = "The Violet Hold",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			7,
			7,
		},
		["JI_ID"] = 283,
		["SI_ID"] = 608,
	},
	[2289] = {
		["name"] = "Plaguefall",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1183,
		["SI_ID"] = 2289,
	},
	[2519] = {
		["name"] = "Neltharus",
		["tier"] = 10,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1199,
		["SI_ID"] = 2519,
	},
	[959] = {
		["name"] = "Shado-Pan Monastery",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 312,
		["SI_ID"] = 959,
	},
	[2450] = {
		["name"] = "Sanctum of Domination",
		["tier"] = 9,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 10,
			[16] = 10,
			[15] = 10,
			[17] = 10,
		},
		["JI_ID"] = 1193,
		["SI_ID"] = 2450,
	},
	[2291] = {
		["name"] = "De Other Side",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1188,
		["SI_ID"] = 2291,
	},
	[545] = {
		["name"] = "The Steamvault",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 261,
		["SI_ID"] = 545,
	},
	[209] = {
		["name"] = "Zul'Farrak",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			7,
			[24] = 7,
		},
		["JI_ID"] = 241,
		["SI_ID"] = 209,
	},
	[2930] = {
		["name"] = "Midnight",
		["tier"] = 12,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 4,
		},
		["JI_ID"] = 1312,
		["SI_ID"] = 2930,
	},
	[2293] = {
		["name"] = "Theater of Pain",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
		},
		["JI_ID"] = 1187,
		["SI_ID"] = 2293,
	},
	[2559] = {
		["name"] = "Shadowlands",
		["tier"] = 9,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 6,
			[16] = 6,
			[15] = 6,
			[17] = 6,
		},
		["JI_ID"] = 1192,
		["SI_ID"] = 2559,
	},
	[960] = {
		["name"] = "Temple of the Jade Serpent",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 313,
		["SI_ID"] = 960,
	},
	[249] = {
		["name"] = "Onyxia's Lair",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 1,
			[4] = 1,
		},
		["JI_ID"] = 760,
		["SI_ID"] = 249,
	},
	[1279] = {
		["name"] = "The Everbloom",
		["tier"] = 6,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
			[24] = 4,
		},
		["JI_ID"] = 556,
		["SI_ID"] = 1279,
	},
	[546] = {
		["name"] = "The Underbog",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 262,
		["SI_ID"] = 546,
	},
	[578] = {
		["name"] = "The Oculus",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
		},
		["JI_ID"] = 282,
		["SI_ID"] = 578,
	},
	[2441] = {
		["name"] = "Tazavesh, the Veiled Market",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			[2] = 8,
			[23] = 8,
		},
		["JI_ID"] = 1194,
		["SI_ID"] = 2441,
	},
	[2284] = {
		["name"] = "Sanguine Depths",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1189,
		["SI_ID"] = 2284,
	},
	[2290] = {
		["name"] = "Mists of Tirna Scithe",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[23] = 3,
		},
		["JI_ID"] = 1184,
		["SI_ID"] = 2290,
	},
	[961] = {
		["name"] = "Stormstout Brewery",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 302,
		["SI_ID"] = 961,
	},
	[2287] = {
		["name"] = "Halls of Atonement",
		["tier"] = 9,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1185,
		["SI_ID"] = 2287,
	},
	[2164] = {
		["name"] = "The Eternal Palace",
		["tier"] = 8,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1179,
		["SI_ID"] = 2164,
	},
	[547] = {
		["name"] = "The Slave Pens",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 260,
		["SI_ID"] = 547,
	},
	[2810] = {
		["name"] = "Manaforge Omega",
		["tier"] = 11,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 8,
			[16] = 8,
			[15] = 8,
			[17] = 8,
		},
		["JI_ID"] = 1302,
		["SI_ID"] = 2810,
	},
	[109] = {
		["name"] = "The Temple of Atal'hakkar",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			4,
		},
		["JI_ID"] = 237,
		["SI_ID"] = 109,
	},
	[643] = {
		["name"] = "Throne of the Tides",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 65,
		["SI_ID"] = 643,
	},
	[2939] = {
		["name"] = "The Dreamrift",
		["tier"] = 13,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 1,
			[16] = 1,
			[15] = 1,
			[17] = 1,
		},
		["JI_ID"] = 1314,
		["SI_ID"] = 2939,
	},
	[962] = {
		["name"] = "Gate of the Setting Sun",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[24] = 4,
		},
		["JI_ID"] = 303,
		["SI_ID"] = 962,
	},
	[994] = {
		["name"] = "Mogu'shan Palace",
		["tier"] = 5,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 321,
		["SI_ID"] = 994,
	},
	[2813] = {
		["name"] = "Murder Row",
		["tier"] = 12,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1304,
		["SI_ID"] = 2813,
	},
	[548] = {
		["name"] = "Serpentshrine Cavern",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 6,
		},
		["JI_ID"] = 748,
		["SI_ID"] = 548,
	},
	[580] = {
		["name"] = "Sunwell Plateau",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 6,
		},
		["JI_ID"] = 752,
		["SI_ID"] = 580,
	},
	[1771] = {
		["name"] = "Tol Dagor",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1002,
		["SI_ID"] = 1771,
	},
	[644] = {
		["name"] = "Halls of Origination",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			7,
			7,
		},
		["JI_ID"] = 70,
		["SI_ID"] = 644,
	},
	[1841] = {
		["name"] = "The Underrot",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1022,
		["SI_ID"] = 1841,
	},
	[1594] = {
		["name"] = "The MOTHERLODE!!",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1012,
		["SI_ID"] = 1594,
	},
	[1877] = {
		["name"] = "Temple of Sethraliss",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1030,
		["SI_ID"] = 1877,
	},
	[1822] = {
		["name"] = "Siege of Boralus",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
		},
		["JI_ID"] = 1023,
		["SI_ID"] = 1822,
	},
	[554] = {
		["name"] = "The Mechanar",
		["tier"] = 2,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
		},
		["JI_ID"] = 258,
		["SI_ID"] = 554,
	},
	[1754] = {
		["name"] = "Freehold",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1001,
		["SI_ID"] = 1754,
	},
	[1477] = {
		["name"] = "Halls of Valor",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
		},
		["JI_ID"] = 721,
		["SI_ID"] = 1477,
	},
	[645] = {
		["name"] = "Blackrock Caverns",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[24] = 5,
		},
		["JI_ID"] = 66,
		["SI_ID"] = 645,
	},
	[1763] = {
		["name"] = "Atal'Dazar",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 968,
		["SI_ID"] = 1763,
	},
	[1712] = {
		["name"] = "Antorus, the Burning Throne",
		["tier"] = 7,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 11,
			[16] = 11,
			[15] = 11,
			[17] = 11,
		},
		["JI_ID"] = 946,
		["SI_ID"] = 1712,
	},
	[996] = {
		["name"] = "Terrace of Endless Spring",
		["tier"] = 5,
		["isRaid"] = true,
		["difficulties"] = {
			nil,
			nil,
			4,
			4,
			4,
			4,
			4,
		},
		["JI_ID"] = 320,
		["SI_ID"] = 996,
	},
	[1676] = {
		["name"] = "Tomb of Sargeras",
		["tier"] = 7,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 9,
			[16] = 9,
			[15] = 9,
			[17] = 9,
		},
		["JI_ID"] = 875,
		["SI_ID"] = 1676,
	},
	[550] = {
		["name"] = "The Eye",
		["tier"] = 2,
		["isRaid"] = true,
		["difficulties"] = {
			[4] = 4,
		},
		["JI_ID"] = 749,
		["SI_ID"] = 550,
	},
	[1530] = {
		["name"] = "The Nighthold",
		["tier"] = 7,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 10,
			[16] = 10,
			[15] = 10,
			[17] = 10,
		},
		["JI_ID"] = 786,
		["SI_ID"] = 1530,
	},
	[601] = {
		["name"] = "Azjol-Nerub",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 272,
		["SI_ID"] = 601,
	},
	[34] = {
		["name"] = "The Stockade",
		["tier"] = 1,
		["isRaid"] = false,
		["difficulties"] = {
			3,
		},
		["JI_ID"] = 238,
		["SI_ID"] = 34,
	},
	[1862] = {
		["name"] = "Waycrest Manor",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			5,
			5,
			[23] = 5,
			[24] = 5,
		},
		["JI_ID"] = 1021,
		["SI_ID"] = 1862,
	},
	[2569] = {
		["name"] = "Aberrus, the Shadowed Crucible",
		["tier"] = 10,
		["isRaid"] = true,
		["difficulties"] = {
			[14] = 9,
			[16] = 9,
			[15] = 9,
			[17] = 9,
		},
		["JI_ID"] = 1208,
		["SI_ID"] = 2569,
	},
	[616] = {
		["name"] = "The Eye of Eternity",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 1,
			[4] = 1,
		},
		["JI_ID"] = 756,
		["SI_ID"] = 616,
	},
	[1544] = {
		["name"] = "Assault on Violet Hold",
		["tier"] = 7,
		["isRaid"] = false,
		["difficulties"] = {
			8,
			8,
			[23] = 8,
		},
		["JI_ID"] = 777,
		["SI_ID"] = 1544,
	},
	[1098] = {
		["name"] = "Throne of Thunder",
		["tier"] = 5,
		["isRaid"] = true,
		["difficulties"] = {
			nil,
			nil,
			12,
			12,
			13,
			13,
			12,
		},
		["JI_ID"] = 362,
		["SI_ID"] = 1098,
	},
	[469] = {
		["name"] = "Blackwing Lair",
		["tier"] = 1,
		["isRaid"] = true,
		["difficulties"] = {
			[9] = 8,
		},
		["JI_ID"] = 742,
		["SI_ID"] = 469,
	},
	[615] = {
		["name"] = "The Obsidian Sanctum",
		["tier"] = 3,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 1,
			[4] = 1,
		},
		["JI_ID"] = 755,
		["SI_ID"] = 615,
	},
	[657] = {
		["name"] = "The Vortex Pinnacle",
		["tier"] = 4,
		["isRaid"] = false,
		["difficulties"] = {
			3,
			3,
			[24] = 3,
		},
		["JI_ID"] = 68,
		["SI_ID"] = 657,
	},
	[1864] = {
		["name"] = "Shrine of the Storm",
		["tier"] = 8,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			4,
			[23] = 4,
			[24] = 4,
		},
		["JI_ID"] = 1036,
		["SI_ID"] = 1864,
	},
	[754] = {
		["name"] = "Throne of the Four Winds",
		["tier"] = 4,
		["isRaid"] = true,
		["difficulties"] = {
			[3] = 2,
			[6] = 2,
			[4] = 2,
			[5] = 2,
		},
		["JI_ID"] = 74,
		["SI_ID"] = 754,
	},
	[604] = {
		["name"] = "Gundrak",
		["tier"] = 3,
		["isRaid"] = false,
		["difficulties"] = {
			4,
			5,
			[24] = 5,
		},
		["JI_ID"] = 274,
		["SI_ID"] = 604,
	},

}