local GlobalAddonName, E = ...
--------------------------------------------------------------------------------
local AL3 = LibStub("AceLocale-3.0")
local debug = false
local L = AL3:NewLocale("OctoTODO", "enUS", true, debug)
if L then
	L["Only Horde"] = true
	L["Only Alliance"] = true


	L["AddonHeight"] = true
	L["AddonLeftFrameWeight"] = true
	L["AddonCentralFrameWeight"] = true
	L["MainFrameDefaultLines"] = true
	L["SFDropDownWeight"] = true


	L["fullName"] = true
	L["showIcons"] = true
	L["showIconsQuestionMark"] = true
	L["showVersion"] = true
	L["showIndex"] = true
	L["defaultAddonList"] = true
	L["showOnlyLoaded"] = true



	L["minimaphide"] = true
	L["hookMenuButton"] = true
	L["sortingCpu"] = true
	L["cpuShowCurrent"] = true
	L["cpuShowEncounter"] = true
	L["profilingcpuShowPeak"] = true
	L["profilingcpuShowAverage"] = true
	L["profilingcpuUpdate"] = true
	L["localizeCategoryName"] = true
	L["autofocusSearch"] = true
	L["showSecureAddons"] = true
	L["showTocXCategory"] = true
	L["showTocCategory"] = true
	L["showMemoryInBrokerTtp"] = true
	L["isCategoryFrameVisible"] = true
	L["time_YEAR"] = "y"
	L["time_DAY"] = "d"
	L["time_HOUR"] = "h"
	L["time_MINUTE"] = "m"
	L["time_SECOND"] = "s"
	L["Abandon All Quests"] = true
	L["Abandon: "] = true
	L["Battle Pet"] = true
	L["Bind Location"] = true
	L["Coins"] = true
	L["Community Feast"] = true
	L["Current Location"] = true
	L["Expire on"] = true
	L["Fyrakk Asssaults"] = true
	L["AutoSellGrey"] = true
	L["Grand Hunt"] = true
	L["Keys of Loyalty"] = true
	L["Korthia"] = true
	L["Kyrian"] = true
	L["Last Update"] = true
	L["Level"] = true
	L["Necrolord"] = true
	L["Night Fae"] = true
	L["Other"] = true
	L["General"] = true
	L["Researchers Under Fire"] = true
	L["RESET"] = RESET
	L["Siege on Dragonbane Keep"] = true
	L["The Forbidden Reach"] = true
	L["The Storm's Fury"] = true
	L["Transferable Anima"] = true
	L["Transferable Flakes"] = true
	L["Treasure Goblin"] = true
	L["Vendored gray items for: "] = true
	L["Venthyr"] = true
	L["We need more gold"] = true
	L["You don't have enough money to repair."] = true
	L["Your items have been repaired for: "] = true
	L["Your items have been repaired using guild bank funds for: "] = true
	L["Zaralek Cavern"] = true
	L["Zereth Mortis"] = true
	L["Bodyguards"] = true
	L["Mythic Keystone"] = true
	L["Disciple of Fyrakk"] = true
	L["Fighting is Its Own Reward"] = true
	L["World Boss"] = true
	L["World Bosses"] = true
	L["PvP"] = true
	L["Weekend Event"] = true
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = true
	L["Sniffenseeking"] = true
	L["Sniffenseeking (items)"] = true
	L["Warmode"] = PVP_LABEL_WAR_MODE
	L["OFF"] = LOC_OPTION_OFF
	L["ON"] = PVP_WAR_MODE_ENABLED
	L["AutoRepair"] = true
	L["InputDelete"] = true
	L["AutoOpen"] = true
	L["AutoGossip"] = true
	L["CinematicCanceler"] = true
	L["ClearChat"] = true
	L["Covenant"] = true
	L["UIErrorsFramePosition"] = true
	L["Functions"] = true
	L["Modules"] = true
	L["DisplaySettings"] = true
	L["TimeRift"] = true
	L["Dreamsurges"] = true
	L["Storm-Bound Chest"] = true
	L["Temporal Acquisitions Specialist"] = true
	L["y. "] = true
	L["d. "] = true
	L["h. "] = true
	L["m. "] = true
	L["s. "] = true
	L["Dilated Time Capsule"] = true
	L["Dreamsurge Chrysalis"] = true
	L["Dreamsurge Coalescence"] = true
	L["Charred Elemental Remains"] = true
	L["Encapsulated Destiny"] = true
	L["Dreamsurge Investigation"] = true
	L["Shaping the Dreamsurge"] = true
	L["Head"] = true
	L["Shoulder"] = true
	L["Back"] = true
	L["Chest"] = true
	L["Wrist"] = true
	L["Hands"] = true
	L["Waist"] = true
	L["Legs"] = true
	L["Feet"] = true
	L["Only Current Server"] = true
	L["Only Current BattleTag"] = true
	L["Player level"] = true
	L["Player MAX level"] = true
	L["Item level: "] = true -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = true
	L["Auto Turn Quests"] = true
	L["Aiding the Accord"] = true
	L["InDev"] = true
	L["Total"] = true
	L["Elemental"] = true
	L["Auto_Screenshot"] = true
	L["When Time Needs Mending"] = true
	L["Current Date"] = true
	L["About"] = true
	L["Portals"] = true
	L["Firelands"] = true
	L["Black Temple"] = true
	L["Dawn of the Infinites"] = true
	L["Ulduar"] = true
	L["Paragon"] = true
	-- L["Superbloom"] = true
	L["Dreamseeds"] = true
	-- L["Dream Wardens"] = true
	L["Crests"] = true
	L["Sparks"] = true
	L["Flightstones"] = true
	L["Rares"] = true
	L["Treasures"] = true
	L["Emerald Dream"] = true
	L["The Coalition of Flames"] = true
	L["Enter the Dream"] = true
	L["Druids of the Flame"] = true
	L["Ice and Fire"] = true
	L["Eye of Ysera"] = true
	L["A Dream of Fields and Fire"] = true
	L["New Beginnings"] = true
	L["Characters"] = true
	L["Hide: Boss Banner"] = true
	L["Hide: Covenant"] = true
	L["Hide: Error Messages"] = true
	L["Hide: RaidBossEmoteFrame"] = true
	L["Hide: TalkingHeadFrame"] = true
	L["Hide: Zone Text"] = true
	L["Catalyst Charges"] = true
	L["Sparks of Life"] = true
	L["Season Maximum"] = true
	L["Can Earned"] = true
	L["Gift"] = true
	L["Gifts"] = true
	L["The Gilneas Reclamation"] = true
	L["The Big Dig"] = true
	L["Azerothian Archives"] = true
	L["Daily Reset"] = true
	-- L["Blooming Dreamseeds"] = true
	L["Was online"] = true
	-- L["Warbanding Together"] = true
	L["Weekly Dungeon Quest"] = true
	L["Light/Dark Cycle"] = true
	L["Major Keyflames"] = true
	L["Minor Keyflames"] = true
	L["Turn on"] = true
	L["Turn off"] = true
	L["No quests"] = true
	L["Additional Buttons"] = true
	L["Bags"] = true
	L["Bank"] = true
	L["Another quests"] = true
	L["Maw"] = true
	L["Shadowmourne"] = true
	L["Green Fire"] = true
	L["Some Wicked Things"] = true
	L["Only Current Realm"] = true
	L["Parts"] = true
	L["Optional Reagents"] = true
	L["Trade Goods"] = true
	L["Races"] = true
	L["Allied Races"] = true
	L["Hide: Azerite Animations"] = true
	L["Hide: Objectives In Instance"] = true
end
L = AL3:NewLocale("OctoTODO", "ruRU")
if L then
	L["Only Horde"] = "Только Орда"
	L["Only Alliance"] = "Только Альянс"

	L["AddonHeight"] = "Высота строк"
	L["AddonLeftFrameWeight"] = "Ширина левого"
	L["AddonCentralFrameWeight"] = "Ширина строк"
	L["MainFrameDefaultLines"] = "Количество строк"
	L["SFDropDownWeight"] = "SFDropDownWeight"

	L["fullName"] = "Полное название"
	L["showIcons"] = "Показывать иконку"
	L["showIconsQuestionMark"] = "Показывать иконку со знаком вопроса"
	L["showVersion"] = "Показывать версию"
	L["showIndex"] = "Показывать индекс"
	L["defaultAddonList"] = "Стандартный список аддонов"
	L["showOnlyLoaded"] = "Показывать только загруженные"

	L["minimaphide"] = "|cffFF4C4F".."minimaphide".."|r"
	L["hookMenuButton"] = "|cffFF4C4F".."hookMenuButton".."|r"
	L["sortingCpu"] = "|cffFF4C4F".."sortingCpu".."|r"
	L["cpuShowCurrent"] = "|cffFF4C4F".."cpuShowCurrent".."|r"
	L["cpuShowEncounter"] = "|cffFF4C4F".."cpuShowEncounter".."|r"
	L["profilingcpuShowPeak"] = "|cffFF4C4F".."profilingcpuShowPeak".."|r"
	L["profilingcpuShowAverage"] = "|cffFF4C4F".."profilingcpuShowAverage".."|r"
	L["profilingcpuUpdate"] = "|cffFF4C4F".."profilingcpuUpdate".."|r"
	L["localizeCategoryName"] = "|cffFF4C4F".."localizeCategoryName".."|r"
	L["autofocusSearch"] = "|cffFF4C4F".."autofocusSearch".."|r"
	L["showSecureAddons"] = "|cffFF4C4F".."showSecureAddons".."|r"
	L["showTocXCategory"] = "|cffFF4C4F".."showTocXCategory".."|r"
	L["showTocCategory"] = "|cffFF4C4F".."showTocCategory".."|r"
	L["showMemoryInBrokerTtp"] = "|cffFF4C4F".."showMemoryInBrokerTtp".."|r"
	L["isCategoryFrameVisible"] = "|cffFF4C4F".."isCategoryFrameVisible".."|r"
	L["time_YEAR"] = "г"
	L["time_DAY"] = "д"
	L["time_HOUR"] = "ч"
	L["time_MINUTE"] = "м"
	L["time_SECOND"] = "с"
	L["Abandon All Quests"] = "Отменить все задания"
	L["Abandon: "] = "Отменено: "
	L["Battle Pet"] = "Боевой питомец"
	L["Bind Location"] = "Место привязки"
	L["Coins"] = "Монетки"
	L["Community Feast"] = "Большое пиршество"
	L["Current Location"] = "Текущее местоположение"
	L["Expire on"] = "Истекает"
	L["Fyrakk Asssaults"] = "Налет Фиракка (Локалка)"
	L["Grand Hunt"] = "Великая охота"
	L["Keys of Loyalty"] = "Ключи преданности"
	L["Korthia"] = "Кортия"
	L["Kyrian"] = "Кирии"
	L["Last Update"] = "Последнее Обновление"
	L["Level"] = "Уровень"
	L["Necrolord"] = "Некролорды"
	L["Night Fae"] = "Ночной народец"
	L["Other"] = "Другое"
	L["General"] = "Общие"
	L["Researchers Under Fire"] = "Исследователли под огнем" --func_questName(74905)
	L["RESET"] = "Сброс всех данных аддона"
	L["Siege on Dragonbane Keep"] = "Осада Драконьей Погибели"
	L["The Forbidden Reach"] = "Запретный край" -- "Запретный край (10.0.7)"
	L["The Storm's Fury"] = "Неистовство бури"
	L["Transferable Anima"] = "Переносимая анима"
	L["Transferable Flakes"] = "Переносимая стружка"
	L["Treasure Goblin"] = "Алчный гоблин"
	L["Vendored gray items for: "] = "Серые предметы проданы на сумму: "
	L["Venthyr"] = "Вентиры"
	L["We need more gold"] = "Нужно больше золота!"
	L["You don't have enough money to repair."] = "У Вас недостаточно денег для ремонта."
	L["Your items have been repaired for: "] = "Ремонт обошелся в "
	L["Your items have been repaired using guild bank funds for: "] = "Ремонт обошелся гильдии в "
	L["Zaralek Cavern"] = "Пещера Заралек" -- "Пещера Заралек (10.1.0)"
	L["Zereth Mortis"] = "Зерет Мортис"
	L["Bodyguards"] = "Телохранители"
	L["Mythic Keystone"] = "Эпохальный ключ"
	L["Disciple of Fyrakk"] = "Ученик Фиракка"
	L["Fighting is Its Own Reward"] = "Славный бой – это уже награда"
	L["World Boss"] = "Мировой босс"
	L["World Bosses"] = "Мировые боcсы"
	L["PvP"] = "PvP"
	L["Weekend Event"] = "Событие выходного дня"
	L["PLAYER_DIFFICULTY_TIMEWALKER"] = PLAYER_DIFFICULTY_TIMEWALKER
	L["A Worthy Ally: Loamm Niffen"] = "Достойный союзник: лоаммские ниффы"
	-- L["Blooming Dreamseeds"] = "Цветение во сне"
	L["Sniffenseeking"] = "Нюхорысканье"
	L["Sniffenseeking (items)"] = "Нюхорысканье (" .. ITEMS .. ")"
	L["AutoRepair"] = "Автопочинка"
	L["InputDelete"] = "Автозаполнение 'УДАЛИТЬ'"
	L["AutoOpen"] = "Автооткрытие предметов"
	L["AutoGossip"] = "Авторазговор с НПЦ"
	L["CinematicCanceler"] = "Автопропуск видео"
	L["ClearChat"] = "Чистка чата при заходе в игру"
	L["UIErrorsFramePosition"] = "Смена позиции фрейма ошибок"
	L["Functions"] = "Функции"
	L["Modules"] = "Модули"
	L["DisplaySettings"] = "Настройки отображения"
	L["TimeRift"] = "Портал времени"
	L["Dreamsurges"] = "Прилив Снов"
	L["Storm-Bound Chest"] = "Запечатанный бурей сундук"
	L["Temporal Acquisitions Specialist"] = "Темпоральный специалист по снабжению"
	L["y. "] = "г. "
	L["d. "] = "д. "
	L["h. "] = "ч. "
	L["m. "] = "м. "
	L["s. "] = "с. "
	L["Dilated Time Capsule"] = "Капсула растянутого времени"
	L["Dreamsurge Chrysalis"] = "Хризалида Дикого Сна"
	L["Dreamsurge Coalescence"] = "Слияние Прилива Снов"
	L["Charred Elemental Remains"] = "Обугленные останки элементалей"
	L["Encapsulated Destiny"] = "Инкапсулированная судьба"
	L["Dreamsurge Investigation"] = "Исследование Прилива Снов"
	L["Shaping the Dreamsurge"] = "Укрощение Прилива Снов"
	L["Head"] = "Голова"
	L["Shoulder"] = "Плечи"
	L["Back"] = "Спина"
	L["Chest"] = "Грудь"
	L["Wrist"] = "Запястья"
	L["Hands"] = "Кисти рук"
	L["Waist"] = "Пояс"
	L["Legs"] = "Ноги"
	L["Feet"] = "Ступни"
	L["InDev"] = "|cffFF4C4FВ разработке|r"
	L["Only Current Server"] = "Только текущий сервер"
	L["Only Current BattleTag"] = "Только текущий BattleTag"
	L["Player level"] = "Мин. уровень"
	L["Player MAX level"] = "Макс. уровень"
	L["Item level: "] = "Уровень предметов: " -- LFG_LIST_ITEM_LEVEL_INSTR_SHORT
	L["Width: "] = "Ширина: "
	L["Auto Turn Quests"] = "Автопринятие заданий"
	L["Aiding the Accord"] = "Помощь союзу"
	L["Total"] = "Всего"
	L["Elemental"] = "Стихии"
	L["Auto_Screenshot"] = "Автоскриншот"
	L["When Time Needs Mending"] = "Исцелить само время"
	L["Current Date"] = "Текущая дата"
	L["About"] = "Об аддоне"
	L["Portals"] = "Порталы"
	L["Firelands"] = "Огненные Просторы"
	L["Dawn of the Infinites"] = "Рассвет Бесконечности"
	L["Black Temple"] = "Чёрный Храм"
	L["Ulduar"] = "Ульдуар"
	L["Paragon"] = "Парагон"
	-- L["Superbloom"] = "Цветочный бум"
	L["Dreamseeds"] = "Семена"
	-- L["Dream Wardens"] = "Стражи Сна"
	L["Crests"] = "Гребни"
	L["Sparks"] = "Искры"
	L["Flightstones"] = "Драконьи камни"
	L["Rares"] = "Рарки"
	L["Treasures"] = "Сундуки"
	L["Emerald Dream"] = "Изумрудный Сон"
	L["The Coalition of Flames"] = "Союз пламени"
	L["Enter the Dream"] = "Погружение в сон"
	L["Druids of the Flame"] = "Друиды пламени"
	L["Ice and Fire"] = "Лед и огонь"
	L["Eye of Ysera"] = "Око Изеры"
	L["A Dream of Fields and Fire"] = "Сон о полях в огне"
	L["New Beginnings"] = "Новое начало"
	L["Characters"] = "Персонажи"
	L["Hide: Boss Banner"] = "Скрытие баннера босса"
	L["Hide: Covenant"] = "Скрытие ковенанта"
	L["Hide: Error Messages"] = "Скрытие текста ошибок"
	L["Hide: RaidBossEmoteFrame"] = "Скрытие эмоций босса"
	L["Hide: TalkingHeadFrame"] = "Скрытие говорящей головы"
	L["Hide: Zone Text"] = "Скрытие текста зон"
	L["Catalyst Charges"] = "Заряды Катализатора"
	L["Sparks of Life"] = "Искры жизни"
	L["Season Maximum"] = "Максимум за сезон"
	L["Can Earned"] = "Можно получить"
	L["Gift"] = "Подарок"
	L["Gifts"] = "Подарки"
	L["The Gilneas Reclamation"] = "Возвращение Гилнеаса"
	L["The Big Dig"] = "Большие раскопки"
	L["Azerothian Archives"] = "Азеротские архивы"
	L["Daily Reset"] = "Ежедневный сброс"
	L["Was online"] = "Был в сети"
	-- L["Warbanding Together"] = "Всё ради удобства"
	L["Weekly Dungeon Quest"] = "Еженедельное задание подземелья"
	L["Light/Dark Cycle"] = "Лайт/Дарк цикл"
	L["Major Keyflames"] = "Основные огни"
	L["Minor Keyflames"] = "Второстепенные огни"
	L["Turn on"] = "Включить"
	L["Turn off"] = "Выключить"
	L["No quests"] = "Нет квестов"
	L["Additional Buttons"] = "Дополнительные кнопки"
	L["Bags"] = "Сумки"
	L["Abandon"] = "Отменено: "
	L["Bank"] = "Банк"
	L["Another quests"] = "Другие задания"
	L["Maw"] = "Утроба"
	L["Sniffenseeking (items)"] = "Нюхорысканье ("..ITEMS..")"
	L["Shadowmourne"] = "Темная Скорбь"
	L["Green Fire"] = "Зелёный Огонь"
	L["Some Wicked Things"] = "Некоторые неприятные вещи (10.1.5)"
	L["Only Current Realm"] = "Только текущий сервер"
	L["Parts"] = "Детали"
	L["Optional Reagents"] = "Дополнительные реагенты"
	L["Trade Goods"] = "Хозяйственные товары"
	L["Races"] = "Рассовые"
	L["Allied Races"] = "Союзные расы"
	L["Hide: Azerite Animations"] = "Скрытие анимации Азерита"
	L["Hide: Objectives In Instance"] = "Скрытие заданий в подземельях"
	L["AutoSellGrey"] = "Автопродажа серого хлама"
end
