-- local GlobalAddonName, E = ...
-- ----------------------------------------------------------------------------------------------------------------------------------
-- -- Module_Global_Fade_Persist
-- tinsert(E.Modules, function()
-- 		if Octo_ToDo_DB_Vars.config.GlobalFadePersist then
-- 			C_Timer.After(1, function()
-- 					if E.isElvUI == true then
-- 						local E, L, V, P, G = unpack(ElvUI)
-- 						local GFP = E:NewModule('ElvUI_GlobalFadePersist', 'AceHook-3.0', 'AceEvent-3.0')
-- 						local EP = LibStub("LibElvUIPlugin-1.0")
-- 						local AB = E:GetModule("ActionBars")
-- 						function FadeParent_OnEvent(self, event)
-- 							if UnitInVehicle("player") and (event == 'UNIT_ENTERED_VEHICLE' or 'UNIT_ENTERING_VEHICLE') then
-- 								self.mouseLock = true
-- 								E:UIFrameFadeIn(self, 0.2, self:GetAlpha(), 1)
-- 							else
-- 								self.mouseLock = false
-- 								E:UIFrameFadeOut(self, 0.2, self:GetAlpha(), 1 - AB.db.globalFadeAlpha)
-- 							end
-- 						end
-- 						function GFP:Initialize()
-- 							EP:RegisterPlugin(GFP:GetName())
-- 							AB.fadeParent:RegisterEvent("UNIT_ENTERING_VEHICLE")
-- 							AB.fadeParent:RegisterEvent("UNIT_ENTERED_VEHICLE")
-- 							AB.fadeParent:RegisterEvent("UNIT_EXITING_VEHICLE")
-- 							AB.fadeParent:RegisterEvent("UNIT_EXITED_VEHICLE")
-- 							AB.fadeParent:RegisterEvent("PLAYER_DEAD")
-- 							AB.fadeParent:UnregisterEvent("PLAYER_REGEN_DISABLED")
-- 							AB.fadeParent:UnregisterEvent("PLAYER_REGEN_ENABLED")
-- 							AB.fadeParent:UnregisterEvent("PLAYER_TARGET_CHANGED")
-- 							AB.fadeParent:UnregisterEvent("UNIT_SPELLCAST_START", "player")
-- 							AB.fadeParent:UnregisterEvent("UNIT_SPELLCAST_STOP", "player")
-- 							AB.fadeParent:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_START", "player")
-- 							AB.fadeParent:UnregisterEvent("UNIT_SPELLCAST_CHANNEL_STOP", "player")
-- 							AB.fadeParent:UnregisterEvent("UNIT_HEALTH", "player")
-- 							AB.fadeParent:UnregisterEvent("PLAYER_FOCUS_CHANGED")
-- 							AB.fadeParent:SetScript("OnEvent", FadeParent_OnEvent)
-- 						end
-- 						E:RegisterModule(GFP:GetName())
-- 					end
-- 			end)
-- 		end
-- end)