local GlobalAddonName, E = ...
local AddonTitle = C_AddOns.GetAddOnMetadata(GlobalAddonName, "Title")
--------------------------------------------------------------------------------
E.OctoTable_Race = {
	{raceID = 24, RaceEnglish = "Pandaren", faction = "Neutral"},
	{raceID = 2, RaceEnglish = "Orc", faction = "Horde"},
	{raceID = 5, RaceEnglish = "Scourge", faction = "Horde"},
	{raceID = 6, RaceEnglish = "Tauren", faction = "Horde"},
	{raceID = 8, RaceEnglish = "Troll", faction = "Horde"},
	{raceID = 9, RaceEnglish = "Goblin", faction = "Horde"},
	{raceID = 10, RaceEnglish = "BloodElf", faction = "Horde"},
	{raceID = 26, RaceEnglish = "Pandaren", faction = "Horde"},
	{raceID = 27, RaceEnglish = "Nightborne", faction = "Horde"},
	{raceID = 28, RaceEnglish = "HighmountainTauren", faction = "Horde"},
	{raceID = 31, RaceEnglish = "ZandalariTroll", faction = "Horde"},
	{raceID = 35, RaceEnglish = "Vulpera", faction = "Horde"},
	{raceID = 36, RaceEnglish = "MagharOrc", faction = "Horde"},
	{raceID = 70, RaceEnglish = "Dracthyr", faction = "Horde"},
	{raceID = 1, RaceEnglish = "Human", faction = "Alliance"},
	{raceID = 3, RaceEnglish = "Dwarf", faction = "Alliance"},
	{raceID = 4, RaceEnglish = "NightElf", faction = "Alliance"},
	{raceID = 7, RaceEnglish = "Gnome", faction = "Alliance"},
	{raceID = 11, RaceEnglish = "Draenei", faction = "Alliance"},
	{raceID = 12, RaceEnglish = "FelOrc", faction = "Alliance"},
	{raceID = 13, RaceEnglish = "Naga_", faction = "Alliance"},
	{raceID = 14, RaceEnglish = "Broken", faction = "Alliance"},
	{raceID = 15, RaceEnglish = "Skeleton", faction = "Alliance"},
	{raceID = 16, RaceEnglish = "Vrykul", faction = "Alliance"},
	{raceID = 17, RaceEnglish = "Tuskarr", faction = "Alliance"},
	{raceID = 18, RaceEnglish = "ForestTroll", faction = "Alliance"},
	{raceID = 19, RaceEnglish = "Taunka", faction = "Alliance"},
	{raceID = 20, RaceEnglish = "NorthrendSkeleton", faction = "Alliance"},
	{raceID = 21, RaceEnglish = "IceTroll", faction = "Alliance"},
	{raceID = 22, RaceEnglish = "Worgen", faction = "Alliance"},
	{raceID = 23, RaceEnglish = "Human", faction = "Alliance"},
	{raceID = 25, RaceEnglish = "Pandaren", faction = "Alliance"},
	{raceID = 29, RaceEnglish = "VoidElf", faction = "Alliance"},
	{raceID = 30, RaceEnglish = "LightforgedDraenei", faction = "Alliance"},
	{raceID = 32, RaceEnglish = "KulTiran", faction = "Alliance"},
	{raceID = 33, RaceEnglish = "ThinHuman", faction = "Alliance"},
	{raceID = 34, RaceEnglish = "DarkIronDwarf", faction = "Alliance"},
	{raceID = 37, RaceEnglish = "Mechagnome", faction = "Alliance"},
	{raceID = 52, RaceEnglish = "Dracthyr", faction = "Alliance"}
}