local GlobalAddonName, E = ...
local AddonTitle = C_AddOns.GetAddOnMetadata(GlobalAddonName, "Title")
----------------------------------------------------------------
E.Octo_Table.Movies = {
	[EXPANSION_NAME0] = {
		{name = "Ten Years of Warcraft", id = 1,},
		{name = "World of Warcraft", id = 2,},
	},
	[EXPANSION_NAME1] = {
		{name = "The Burning Crusade", id = 27,},
	},
	[EXPANSION_NAME2] = {
		{name = "Wrath of the Lich King", id = 18,},
		{name = "Battle of Angrathar the Wrathgate", id = 14,},
		{name = "Fall of the Lich King", id = 16,},
	},
	[EXPANSION_NAME3] = {
		{name = "Cataclysm", id = 23,},
		{name = "Last Stand", id = 21,},
		{name = "Leaving Kezan", id = 22,},
		{name = "The Dragon Soul", id = 73,},
		{name = "Spine of Deathwing", id = 74,},
		{name = "Madness of Deathwing", id = 75,},
		{name = "Fall of Deathwing", id = 76,},
	},
	[EXPANSION_NAME4] = {
		{name = "Mists of Pandaria", id = 115,},
		{name = "Risking It All", id = 117,},
		{name = "Leaving the Wandering Isle", id = 116,},
		{name = "Jade Forest Crash", id = 121,},
		{name = "The King's Command", id = 119,},
		{name = "The Art of War", id = 120,},
		{name = "Battle of Serpent's Heart", id = 118,},
		{name = "The Fleet in Krasarang (Horde)", id = 128,},
		{name = "The Fleet in Krasarang (Alliance)", id = 127,},
		{name = "Hellscream's Downfall (Horde)", id = 151,},
		{name = "Hellscream's Downfall (Alliance)", id = 152,},
	},
	[EXPANSION_NAME5] = {
		{name = "Warlords of Draenor", id = 195,},
		{name = "Darkness Falls", id = 167,},
		{name = "The Battle of Thunder Pass", id = 168,},
		{name = "And Justice for Thrall", id = 177,},
		{name = "Into the Portal", id = 185,},
		{name = "A Taste of Iron", id = 187,},
		{name = "The Battle for Shattrath", id = 188,},
		{name = "Gul'dan Ascendant", id = 270,},
		{name = "Gul'dan's Plan", id = 294,},
		{name = "Victory in Draenor!", id = 295,},
		{name = "Establish Your Garrison (Horde)", id = 189,},
		{name = "Establish Your Garrison (Alliance)", id = 192,},
		{name = "Bigger is Better (Horde)", id = 190,},
		{name = "Bigger is Better (Alliance)", id = 193,},
		{name = "My Very Own Castle (Horde)", id = 191,},
		{name = "My Very Own Castle (Alliance)", id = 194,},
		{name = "Shipyard Construction (Horde)", id = 292,},
		{name = "Shipyard Construction (Alliance)", id = 293,},
	},
	[EXPANSION_NAME6] = {
		{name = "Legion", id = 470,},
		{name = "The Invasion Begins", id = 469,},
		{name = "Return to the Black Temple", id = 471,},
		{name = "The Demon's Trail", id = 473,},
		{name = "The Fate of Val'sharah", id = 472,},
		{name = "Fate of the Horde", id = 474,},
		{name = "A New Life for Undeath", id = 475,},
		{name = "Harbingers Gul'dan", id = 476,},
		{name = "Harbingers Khadgar", id = 477,},
		{name = "Harbingers Illidan", id = 478,},
		{name = "The Nightborne Pact", id = 485,},
		{name = "Stormheim (Alliance)", id = 483,},
		{name = "Stormheim (Horde)", id = 484,},
		{name = "Tomb of Sargeras", id = 486,},
		{name = "The Battle for Broken Shore", id = 487,},
		{name = "A Falling Star", id = 489,},
		{name = "Destiny Unfulfilled", id = 490,},
		{name = "The Nighthold", id = 549,},
		{name = "Victory at The Nighthold", id = 635,},
		{name = "A Found Memento", id = 636,},
		{name = "Assault on the Broken Shore", id = 637,},
		{name = "Kil'jaeden's Downfall", id = 656,},
		{name = "Arrival on Argus", id = 677,},
		{name = "Rejection of the Gift", id = 679,},
		{name = "Reincarnation of Alleria Windrunner", id = 682,},
		{name = "Rise of Argus", id = 687,},
		{name = "Antorus Ending", id = 689,},
		{name = "Epilogue (Horde)", id = 717,},
		{name = "Epilogue (Alliance)", id = 716,},
	},
	[EXPANSION_NAME7] = {
		{name = "Battle for Azeroth", id = 852,},
		{name = "Warbringers Sylvanas", id = 853,},
		{name = "The Fall of Lordaeron", id = 855,},
		{name = "Jaina Joins the Battle", id = 856,},
		{name = "Embers of War", id = 854,},
		{name = "Arrival to Zandalar", id = 857,},
		{name = "Vision of Sailor's Memory", id = 858,},
		{name = "Jaina Returns to Kul Tiras", id = 859,},
		{name = "Jaina's Nightmare", id = 860,},
		{name = "Warbringers Jaina", id = 861,},
		{name = "A Deal with Death", id = 862,},
		{name = "The Threat Within", id = 863,},
		{name = "The Return of Hope", id = 864,},
		{name = "Realm Of Torment", id = 865,},
		{name = "Terror of Darkshore", id = 874,},
		{name = "An Unexpected Reunion", id = 879,},
		{name = "Siege of Dazar'alor", id = 876,},
		{name = "Battle of Dazar'alor", id = 875,},
		{name = "Warbringers Azshara", id = 884,},
		{name = "Rise of Azshara (Horde)", id = 894,},
		{name = "Rise of Azshara (Alliance)", id = 883,},
		{name = "The Negotiation", id = 903,},
		{name = "Reckoning", id = 904,},
		{name = "Azshara's Eternal Palace", id = 920,},
		{name = "Wrathion's Scene", id = 927,},
		{name = "Visions of N'Zoth", id = 928,},
	},
	[EXPANSION_NAME8] = {
		{name = "Shadowlands", id = 936,},
		{name = "Afterlives Ardenweald", id = 935,},
		{name = "Afterlives Bastion", id = 932,},
		{name = "Afterlives Maldraxxus", id = 934,},
		{name = "Afterlives Revendreth", id = 933,},
		{name = "Exile's Reach (Horde)", id = 931,},
		{name = "Exile's Reach (Alliance)", id = 895,},
		{name = "Dark Abduction", id = 937,},
		{name = "For Teldrassil", id = 942,},
		{name = "Beyond The Veil", id = 943,},
		{name = "Remember This Lesson", id = 944,},
		{name = "Breaking The Arbiter", id = 945,},
		{name = "A Glimpse Into Darkness", id = 946,},
		{name = "No More Lies", id = 947,},
		{name = "Sylvanas' Choice", id = 948,},
		{name = "Kingsmourne", id = 949,},
		{name = "Ysera Reborn", id = 941,},
		{name = "Battle For Ardenweald", id = 951,},
		{name = "Fate of Sylvanas", id = 950,},
		{name = "By Our Hand", id = 953,},
		{name = "Arbiter Pelagos", id = 954,},
		{name = "Shattered Legacies", id = 955,},
		{name = "Arthas Menethil's Fate", id = 956,},
		{name = "Eternity's End", id = 957,},
		{name = "The Jailer's Fall", id = 958,},
	},
	[EXPANSION_NAME9] = {
		{name = "Dragonflight", id = 960,},
		{name = "Take To The Skies", id = 973,},
		{name = "Raszageth the Storm-Eater (1)", id = 961,},
		{name = "Raszageth the Storm-Eater (2)", id = 962,},
		{name = "Raszageth Confronts Alexstrasza", id = 965,},
		{name = "Dragonflight Legacies (1)", id = 966,},
		{name = "Dragonflight Legacies (2)", id = 967,},
		{name = "Dragonflight Legacies (3)", id = 968,},
		{name = "The Ebon Scales", id = 969,},
		{name = "The Seed of Hope", id = 963,},
		{name = "Secrets of the Reach", id = 974,},
		{name = "Opening The Way", id = 979,},
		{name = "Fyrakk Incinerates Loamm", id = 981,},
		{name = "A Symbol of Hope", id = 980,},
		{name = "Dawn of the Infinite (Interlude)", id = 991,},
		{name = "Dawn of the Infinite (Finale)", id = 992,},
		{name = "A Matter of Time", id = 993,},
		{name = "Fury Incarnate", id = 1001,},
		{name = "Crown of Flame", id = 1002,},
		{name = "Blessing of Amirdrassil", id = 1003,},
		{name = "Iridikron and Vyranoth", id = 1009,},
	},
	[EXPANSION_NAME10] = {
		{name = "The War Within", id = 1023,},
		{name = "Thrall and Anduin", id = 1014,},
		{name = "Threads of Destiny", id = 1021,},
		{name = "The Story So Far", id = 1024,},
		{name = "Dalaran Arrives at Khaz Algar", id = 1010,},
		{name = "The Guardian and the Harbinger", id = 1012,},
		{name = "Magni's Sacrifice", id = 1013,},
		{name = "Ascension Day", id = 1020,},
		{name = "Confronting Xal'atath", id = 1019,},
	},
}

-- /run MovieFrame_PlayMovie(MovieFrame, 1019)
-- /run MovieFrame_PlayMovie(MovieFrame, 1020)
-- /run MovieFrame_PlayMovie(MovieFrame, 960)