local GlobalAddonName, E = ...
--------------------------------------------------------------------------------
E.OctoTable_CLASSES = {
	["HUNTER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Повелитель зверей",
			["id"] = 253,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 461112,
			["iconPath"] = "Interface/Icons/ABILITY_HUNTER_BESTIALDISCIPLINE",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Стрельба",
			["id"] = 254,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 236179,
			["iconPath"] = "Interface/Icons/Ability_Hunter_FocusedAim",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Выживание",
			["id"] = 255,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 461113,
			["iconPath"] = "Interface/Icons/Ability_Hunter_Camouflage",
		},
		["classId"] = 3,
	},
	["WARRIOR"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Оружие",
			["primaryStat"] = 1,
			["id"] = 71,
			["primaryStatString"] = "Strength",
			["icon"] = 132355,
			["iconPath"] = "Interface/Icons/Ability_Warrior_SavageBlow",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Неистовство",
			["primaryStat"] = 1,
			["id"] = 72,
			["primaryStatString"] = "Strength",
			["icon"] = 132347,
			["iconPath"] = "Interface/Icons/Ability_Warrior_InnerRage",
		},
		{
			["role"] = "TANK",
			["name"] = "Защита",
			["primaryStat"] = 1,
			["id"] = 73,
			["primaryStatString"] = "Strength",
			["icon"] = 132341,
			["iconPath"] = "Interface/Icons/Ability_Warrior_DefensiveStance",
		},
		["classId"] = 1,
	},
	["SHAMAN"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Стихии",
			["iconPath"] = "Interface/Icons/Spell_Nature_Lightning",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136048,
			["id"] = 262,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Совершенствование",
			["iconPath"] = "Interface/Icons/Spell_Shaman_ImprovedStormstrike",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 237581,
			["id"] = 263,
		},
		{
			["role"] = "HEALER",
			["name"] = "Исцеление",
			["iconPath"] = "Interface/Icons/Spell_Nature_MagicImmunity",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136052,
			["id"] = 264,
		},
		["classId"] = 7,
	},
	["MAGE"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Arcane",
			["iconPath"] = "Interface/Icons/Spell_Holy_MagicalSentry",
			["id"] = 62,
			["primaryStatString"] = "Intellect",
			["icon"] = 135932,
			["primaryStat"] = 4,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Fire",
			["iconPath"] = "Interface/Icons/Spell_Fire_FireBolt02",
			["id"] = 63,
			["primaryStatString"] = "Intellect",
			["icon"] = 135810,
			["primaryStat"] = 4,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Frost",
			["iconPath"] = "Interface/Icons/Spell_Frost_FrostBolt02",
			["id"] = 64,
			["primaryStatString"] = "Intellect",
			["icon"] = 135846,
			["primaryStat"] = 4,
		},
		["classId"] = 8,
	},
	["PRIEST"] = {
		{
			["role"] = "HEALER",
			["name"] = "Послушание",
			["primaryStat"] = 4,
			["id"] = 256,
			["primaryStatString"] = "Intellect",
			["icon"] = 135940,
			["iconPath"] = "Interface/Icons/Spell_Holy_PowerWordShield",
		},
		{
			["role"] = "HEALER",
			["name"] = "Свет",
			["primaryStat"] = 4,
			["id"] = 257,
			["primaryStatString"] = "Intellect",
			["icon"] = 237542,
			["iconPath"] = "Interface/Icons/Spell_Holy_GuardianSpirit",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Тьма",
			["primaryStat"] = 4,
			["id"] = 258,
			["primaryStatString"] = "Intellect",
			["icon"] = 136207,
			["iconPath"] = "Interface/Icons/Spell_Shadow_ShadowWordPain",
		},
		["classId"] = 5,
	},
	["PALADIN"] = {
		{
			["role"] = "HEALER",
			["name"] = "Свет",
			["iconPath"] = "Interface/Icons/Spell_Holy_HolyBolt",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 135920,
			["id"] = 65,
		},
		{
			["role"] = "TANK",
			["name"] = "Защита",
			["iconPath"] = "Interface/Icons/Ability_Paladin_ShieldoftheTemplar",
			["primaryStat"] = 1,
			["primaryStatString"] = "Strength",
			["icon"] = 236264,
			["id"] = 66,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Воздаяние",
			["iconPath"] = "Interface/Icons/Spell_Holy_AuraOfLight",
			["primaryStat"] = 1,
			["primaryStatString"] = "Strength",
			["icon"] = 135873,
			["id"] = 70,
		},
		["classId"] = 2,
	},
	["MONK"] = {
		{
			["role"] = "TANK",
			["name"] = "Хмелевар",
			["primaryStat"] = 2,
			["id"] = 268,
			["primaryStatString"] = "Agility",
			["icon"] = 608951,
			["iconPath"] = "Interface/Icons/Spell_Monk_Brewmaster_Spec",
		},
		{
			["role"] = "HEALER",
			["name"] = "Ткач туманов",
			["primaryStat"] = 4,
			["id"] = 270,
			["primaryStatString"] = "Intellect",
			["icon"] = 608952,
			["iconPath"] = "Interface/Icons/Spell_Monk_MistWeaver_Spec",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Танцующий с ветром",
			["primaryStat"] = 2,
			["id"] = 269,
			["primaryStatString"] = "Agility",
			["icon"] = 608953,
			["iconPath"] = "Interface/Icons/Spell_Monk_WindWalker_Spec",
		},
		["classId"] = 10,
	},
	["WARLOCK"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Колдовство",
			["id"] = 265,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136145,
			["iconPath"] = "Interface/Icons/Spell_Shadow_DeathCoil",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Демонология",
			["id"] = 266,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136172,
			["iconPath"] = "Interface/Icons/Spell_Shadow_Metamorphosis",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Разрушение",
			["id"] = 267,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136186,
			["iconPath"] = "Interface/Icons/Spell_Shadow_RainOfFire",
		},
		["classId"] = 9,
	},
	["DEMONHUNTER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Истребление",
			["iconPath"] = "Interface/Icons/Ability_DemonHunter_SpecDPS",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 1247264,
			["id"] = 577,
		},
		{
			["role"] = "TANK",
			["name"] = "Месть",
			["iconPath"] = "Interface/Icons/Ability_DemonHunter_SpecTank",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 1247265,
			["id"] = 581,
		},
		["classId"] = 12,
	},
	["ROGUE"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Ликвидация",
			["iconPath"] = "Interface/Icons/Ability_Rogue_DeadlyBrew",
			["id"] = 259,
			["primaryStatString"] = "Agility",
			["icon"] = 236270,
			["primaryStat"] = 2,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Головорез",
			["iconPath"] = "Interface/Icons/Ability_Rogue_Waylay",
			["id"] = 260,
			["primaryStatString"] = "Agility",
			["icon"] = 236286,
			["primaryStat"] = 2,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Скрытность",
			["iconPath"] = "Interface/Icons/Ability_Stealth",
			["id"] = 261,
			["primaryStatString"] = "Agility",
			["icon"] = 132320,
			["primaryStat"] = 2,
		},
		["classId"] = 4,
	},
	["DRUID"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Баланс",
			["iconPath"] = "Interface/Icons/Spell_Nature_StarFall",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136096,
			["id"] = 102,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Сила зверя",
			["iconPath"] = "Interface/Icons/Ability_Druid_CatForm",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 132115,
			["id"] = 103,
		},
		{
			["role"] = "TANK",
			["name"] = "Страж",
			["iconPath"] = "Interface/Icons/Ability_Racial_BearForm",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 132276,
			["id"] = 104,
		},
		{
			["role"] = "HEALER",
			["name"] = "Исцеление",
			["iconPath"] = "Interface/Icons/SPELL_NATURE_HEALINGTOUCH",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136041,
			["id"] = 105,
		},
		["classId"] = 11,
	},
	["EVOKER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Опустошитель",
			["id"] = 1467,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 4511811,
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Devastation",
		},
		{
			["role"] = "HEALER",
			["name"] = "Хранитель",
			["id"] = 1468,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 4511812,
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Preservation",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Насыщатель",
			["id"] = 1473,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 5198700,
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Augmentation",
		},
		["classId"] = 13,
	},
	["DEATHKNIGHT"] = {
		{
			["role"] = "TANK",
			["name"] = "Кровь",
			["primaryStat"] = 1,
			["id"] = 250,
			["primaryStatString"] = "Strength",
			["icon"] = 135770,
			["iconPath"] = "Interface/Icons/Spell_Deathknight_BloodPresence",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Лед",
			["primaryStat"] = 1,
			["id"] = 251,
			["primaryStatString"] = "Strength",
			["icon"] = 135773,
			["iconPath"] = "Interface/Icons/Spell_Deathknight_FrostPresence",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Нечестивость",
			["primaryStat"] = 1,
			["id"] = 252,
			["primaryStatString"] = "Strength",
			["icon"] = 135775,
			["iconPath"] = "Interface/Icons/Spell_Deathknight_UnholyPresence",
		},
		["classId"] = 6,
	},
}