local GlobalAddonName, E = ...
--------------------------------------------------------------------------------
E.OctoTable_reputation_ALL = {
	2590,
	2640,
	2594,
	2570,
	2600,
}

E.OctoTable_reputationID_Hidden = {
	2463,
}

E.OctoTable_FACTIONTABLE = {
	[1072] = {icon = 0, name = "[DNT] AC Major Faction Child Renown Test", faction = "", other = "Кентавры Маруук", },
	[2159] = {icon = 2024072, name = "7-й легион", faction = "", other = "Battle for Azeroth", },
	[2384] = {icon = 0, name = "7-й легион (идеал)", faction = "", other = "Battle for Azeroth", },
	[1861] = {icon = 0, name = "Arcane Thirst (Silgryn) DEPRECATED", faction = "", other = "Помраченные", },
	[2063] = {icon = 0, name = "Arne Test - Paragon Reputation Stormwind", faction = "", other = "Другое", },
	[2104] = {icon = 0, name = "Battle for Azeroth", faction = "", other = "Другое", },
	[1162] = {icon = 0, name = "Cataclysm", faction = "", other = "Другое", },
	[2233] = {icon = 0, name = "Dino Training - Pterrodax", faction = "", other = "Battle for Azeroth", },
	[2506] = {icon = 0, name = "Dragonflight", faction = "", other = "Другое", },
	[1834] = {icon = 0, name = "Legion", faction = "", other = "Другое", },
	[1245] = {icon = 0, name = "Mists of Pandaria", faction = "", other = "Другое", },
	[2431] = {icon = 0, name = "Owen Test", faction = "", other = "Другое", },
	[980] = {icon = 0, name = "The Burning Crusade", faction = "", other = "Другое", },
	[2569] = {icon = 0, name = "The War Within", faction = "", other = "Другое", },
	[1444] = {icon = 0, name = "Warlords of Draenor", faction = "", other = "Другое", },
	[1118] = {icon = 0, name = "World of Warcraft", faction = "", other = "Другое", },
	[1097] = {icon = 0, name = "Wrath of the Lich King", faction = "", other = "Другое", },
	[1037] = {icon = "NONE", name = "Авангард Альянса", faction = E.Icon_Alliance, other = "Wrath of the Lich King", },
	[1682] = {icon = 1042294, name = "Авангард Ринна", faction = "", other = "Силы Альянса", },
	[2160] = {icon = 2012311, name = "Адмиралтейство Праудмуров", faction = E.Icon_Alliance, other = "Battle for Azeroth", },
	[2379] = {icon = "NONE", name = "Адмиралтейство Праудмуров (идеал)", faction = "", other = "Battle for Azeroth", },
	[1740] = {icon = "NONE", name = "Аеда Ясная Заря", faction = "", other = "Телохранители из казарм", },
	[2615] = {icon = "NONE", name = "Азеротские Архивы", faction = "", other = "Драконья экспедиция", },
	[729] = {icon = "NONE", name = "Азеротский клан Северного Волка", faction = "", other = "Силы Орды", },
	[1216] = {icon = "NONE", name = "Академия Шан Си", faction = "", other = "Mists of Pandaria", },
	[2099] = {icon = 236575, name = "Акуле Речной Рог", faction = "", other = "Legion", },
	[932] = {icon = 135026, name = "Алдоры", faction = "", other = "Город Шаттрат", },
	[2450] = {icon = "NONE", name = "Александрос Могрейн", faction = "", other = "Пепельный двор", },
	[469] = {icon = "NONE", name = "Альянс", faction = E.Icon_Alliance, other = "World of Warcraft", },
	[967] = {icon = "NONE", name = "Аметистовое Око", faction = "", other = "The Burning Crusade", },
	[2401] = {icon = "NONE", name = "Анкоа из клана Клинков Волн (идеал)", faction = "", other = "Battle for Azeroth", },
	[1515] = {icon = 1042646, name = "Араккоа-изгои", faction = "", other = "Warlords of Draenor", },
	[2570] = {icon = "NONE", name = "Арати Тайносводья", faction = "", other = "The War Within", },
	[2611] = {icon = "NONE", name = "Арати Тайносводья (идеал)", faction = "", other = "The War Within", },
	[2372] = {icon = "NONE", name = "Арена \"Морд'Бой\"", faction = "", other = "Силы Орды", },
	[2010] = {icon = "NONE", name = "Арена \"Морд'Бой\" (3-й сезон)", faction = "", other = "Силы Орды", },
	[1374] = {icon = "NONE", name = "Арена \"Морд'Бой\" (сезон 1)", faction = "", other = "Силы Орды", },
	[1690] = {icon = "NONE", name = "Арена \"Морд'Бой\" (сезон 2)", faction = "", other = "Силы Орды", },
	[1387] = {icon = "NONE", name = "Армия Кирин-Тора", faction = "", other = "Mists of Pandaria", },
	[1085] = {icon = "NONE", name = "Армия Песни Войны", faction = E.Icon_Horde, other = "Экспедиция Орды", },
	[2045] = {icon = "NONE", name = "Армия погибели Легиона", faction = "", other = "Legion", },
	[2091] = {icon = "NONE", name = "Армия погибели Легиона (идеал)", faction = "", other = "Legion", },
	[1375] = {icon = "NONE", name = "Армия Покорителей", faction = "", other = "Mists of Pandaria", },
	[1077] = {icon = "NONE", name = "Армия Расколотого Солнца", faction = "", other = "Город Шаттрат", },
	[2165] = {icon = "NONE", name = "Армия Света", faction = "", other = "Legion", },
	[2166] = {icon = "NONE", name = "Армия Света (идеал)", faction = "", other = "Legion", },
	[2157] = {icon = "NONE", name = "Армия Чести", faction = "", other = "Battle for Azeroth", },
	[2385] = {icon = "NONE", name = "Армия Чести (идеал)", faction = "", other = "Battle for Azeroth", },
	[1711] = {icon = "NONE", name = "Археологическое общество Хитрой Шестеренки", faction = "", other = "Warlords of Draenor", },
	[2594] = {icon = "NONE", name = "Ассамблея глубин", faction = "", other = "The War Within", },
	[2613] = {icon = "NONE", name = "Ассамблея глубин (идеал)", faction = "", other = "The War Within", },
	[2446] = {icon = "NONE", name = "Баронесса Вайш", faction = "", other = "Пепельный двор", },
	[1178] = {icon = "NONE", name = "Батальон Адского Крика", faction = "", other = "Cataclysm", },
	[2102] = {icon = 236575, name = "Бесс", faction = "", other = "Legion", },
	[2640] = {icon = "NONE", name = "Бранн Бронзобород", faction = "", other = "The War Within", },
	[59] = {icon = "NONE", name = "Братство Тория", faction = "", other = "World of Warcraft", },
	[1948] = {icon = "NONE", name = "Валарьяры", faction = "", other = "Legion", },
	[2086] = {icon = "NONE", name = "Валарьяры (идеал)", faction = "", other = "Legion", },
	[2432] = {icon = "NONE", name = "Ве'нари", faction = "", other = "Темные Земли", },
	[2474] = {icon = "NONE", name = "Ве'нари (идеал)", faction = "", other = "Темные Земли", },
	[2457] = {icon = "NONE", name = "Великий мастер Воул", faction = "", other = "Пепельный двор", },
	[1739] = {icon = "NONE", name = "Вивианна", faction = "", other = "Телохранители из казарм", },
	[2607] = {icon = "NONE", name = "Визирь", faction = "", other = "Отрезанные нити", },
	[2647] = {icon = "NONE", name = "Визирь (идеал)", faction = "", other = "Отрезанные нити", },
	[2390] = {icon = "NONE", name = "Вим Соленодух", faction = "", other = "Battle for Azeroth", },
	[1388] = {icon = "NONE", name = "Войска Похитителей Солнца", faction = "", other = "Mists of Pandaria", },
	[1440] = {icon = "NONE", name = "Восстание Черного Копья", faction = "", other = "Mists of Pandaria", },
	[889] = {icon = "NONE", name = "Всадники Песни Войны", faction = "", other = "Силы Орды", },
	[1815] = {icon = "NONE", name = "Выжившие из Гилнеаса", faction = "", other = "Legion", },
	[2644] = {icon = "NONE", name = "Вылазки: 1-й сезон", faction = "", other = "The War Within", },
	[2605] = {icon = "NONE", name = "Генерал", faction = "", other = "Отрезанные нити", },
	[2649] = {icon = "NONE", name = "Генерал (идеал)", faction = "", other = "Отрезанные нити", },
	[749] = {icon = "NONE", name = "Гидраксианские Повелители Вод", faction = "", other = "World of Warcraft", },
	[1134] = {icon = "NONE", name = "Гилнеас", faction = E.Icon_Alliance, other = "Альянс", },
	[1168] = {icon = "NONE", name = "Гильдия", faction = "", other = "Гильдия", },
	[1169] = {icon = "NONE", name = "Гильдия", faction = "", other = "Другое", },
	[2517] = {icon = "NONE", name = "Гневион", faction = "", other = "Союз Вальдраккена", },
	[54] = {icon = "NONE", name = "Гномреган", faction = E.Icon_Alliance, other = "Альянс", },
	[2568] = {icon = "NONE", name = "Гонщик Мерцающего Огга", faction = "", other = "Dragonflight", },
	[936] = {icon = "NONE", name = "Город Шаттрат", faction = E.Icon_Alliance, other = "The Burning Crusade", },
	[2449] = {icon = "NONE", name = "Графиня", faction = "", other = "Пепельный двор", },
	[81] = {icon = "NONE", name = "Громовой Утес", faction = E.Icon_Horde, other = "Орда", },
	[69] = {icon = "NONE", name = "Дарнас", faction = E.Icon_Alliance, other = "Альянс", },
	[2413] = {icon = "NONE", name = "Двор Жнецов", faction = "", other = "Темные Земли", },
	[2442] = {icon = "NONE", name = "Двор Жнецов (Идеал)", faction = "", other = "Темные Земли", },
	[2464] = {icon = "NONE", name = "Двор Ночи", faction = "", other = "Темные Земли", },
	[1900] = {icon = "NONE", name = "Двор Фарондиса", faction = "", other = "Legion", },
	[2087] = {icon = "NONE", name = "Двор Фарондиса (идеал)", faction = "", other = "Legion", },
	[1733] = {icon = "NONE", name = "Делвар Железный Кулак", faction = "", other = "Телохранители из казарм", },
	[1281] = {icon = "NONE", name = "Джина Грязный Коготь", faction = "", other = "Земледельцы", },
	[2465] = {icon = "NONE", name = "Дикая Охота", faction = "", other = "Темные Земли", },
	[2444] = {icon = "NONE", name = "Дикая Охота (Идеал)", faction = "", other = "Темные Земли", },
	[1847] = {icon = "NONE", name = "Длань Пророка", faction = "", other = "Warlords of Draenor", },
	[1091] = {icon = "NONE", name = "Драконий союз", faction = "", other = "Wrath of the Lich King", },
	[2507] = {icon = "NONE", name = "Драконья экспедиция", faction = "", other = "Dragonflight", },
	[2508] = {icon = "NONE", name = "Драконья экспедиция (идеал)", faction = "", other = "Dragonflight", },
	[576] = {icon = "NONE", name = "Древобрюхи", faction = "", other = "World of Warcraft", },
	[1732] = {icon = "NONE", name = "Дренорcкая Экспедиция Хитрой Шестеренки", faction = "", other = "Warlords of Draenor", },
	[2456] = {icon = "NONE", name = "Дроман Алиот", faction = "", other = "Пепельный двор", },
	[1919] = {icon = "NONE", name = "Жажда магии Вальтруа", faction = "", other = "Помраченные", },
	[1862] = {icon = "NONE", name = "Жажда магии Окулета", faction = "", other = "Помраченные", },
	[1860] = {icon = "NONE", name = "Жажда магии Талисры", faction = "", other = "Помраченные", },
	[2158] = {icon = "NONE", name = "Жители Вол'дуна", faction = E.Icon_Horde, other = "Battle for Azeroth", },
	[2382] = {icon = "NONE", name = "Жители Вол'дуна (идеал)", faction = "", other = "Battle for Azeroth", },
	[1737] = {icon = "NONE", name = "Жрец Когтя Ишааль", faction = "", other = "Телохранители из казарм", },
	[2111] = {icon = "NONE", name = "Зандаларские динозавры", faction = "", other = "Battle for Azeroth", },
	[2164] = {icon = "NONE", name = "Защитники Азерот", faction = "", other = "Battle for Azeroth", },
	[2386] = {icon = "NONE", name = "Защитники Азерот (идеал)", faction = "", other = "Battle for Azeroth", },
	[2170] = {icon = "NONE", name = "Защитники Аргуса", faction = "", other = "Legion", },
	[2167] = {icon = "NONE", name = "Защитники Аргуса (идеал)", faction = "", other = "Другое", },
	[1177] = {icon = "NONE", name = "Защитники Тол Барада", faction = "", other = "Cataclysm", },
	[1710] = {icon = "NONE", name = "Защитники Ша'тар", faction = "", other = "Warlords of Draenor", },
	[1738] = {icon = "NONE", name = "Защитница Иллона", faction = "", other = "Телохранители из казарм", },
	[2645] = {icon = "NONE", name = "Земельники", faction = "", other = "Совет Дорногала", },
	[1272] = {icon = "NONE", name = "Земледельцы", faction = "", other = "Mists of Pandaria", },
	[1126] = {icon = "NONE", name = "Зиморожденные", faction = "", other = "Авангард Альянса", },
	[1269] = {icon = "NONE", name = "Золотой Лотос", faction = "", other = "Mists of Pandaria", },
	[1520] = {icon = "NONE", name = "Изгнанники клана Призрачной Луны", faction = "", other = "Warlords of Draenor", },
	[2461] = {icon = "NONE", name = "Изобретатель чумы Марилет", faction = "", other = "Пепельный двор", },
	[2097] = {icon = 236575, name = "Илиссия Водная", faction = "", other = "Legion", },
	[1947] = {icon = "NONE", name = "Иллидари", faction = "", other = "Legion", },
	[1492] = {icon = "NONE", name = "Император Шаохао", faction = "", other = "Mists of Pandaria", },
	[2103] = {icon = "NONE", name = "Империя Зандалари", faction = E.Icon_Horde, other = "Battle for Azeroth", },
	[2378] = {icon = "NONE", name = "Империя Зандалари (идеал)", faction = "", other = "Battle for Azeroth", },
	[2511] = {icon = "NONE", name = "Искарские клыкарры", faction = "", other = "Dragonflight", },
	[2551] = {icon = "NONE", name = "Искарские клыкарры (идеал)", faction = "", other = "Dragonflight", },
	[1273] = {icon = "NONE", name = "Йогу Пьяный", faction = "", other = "Земледельцы", },
	[470] = {icon = "NONE", name = "Кабестан", faction = "", other = "Картель Хитрой Шестеренки", },
	[1073] = {icon = "NONE", name = "Калу'ак", faction = "", other = "Wrath of the Lich King", },
	[2460] = {icon = "NONE", name = "Камнелоб", faction = "", other = "Пепельный двор", },
	[2451] = {icon = "NONE", name = "Капитан-егерь Корейн", faction = "", other = "Пепельный двор", },
	[1067] = {icon = "NONE", name = "Карающая Длань", faction = "", other = "Экспедиция Орды", },
	[1133] = {icon = "NONE", name = "Картель Трюмных Вод", faction = E.Icon_Horde, other = "Орда", },
	[169] = {icon = "NONE", name = "Картель Хитрой Шестеренки", faction = E.Icon_Horde, other = "World of Warcraft", },
	[942] = {icon = "NONE", name = "Кенарийская экспедиция", faction = "", other = "The Burning Crusade", },
	[92] = {icon = "NONE", name = "Кентавры из племени Гелкис", faction = "", other = "World of Warcraft", },
	[93] = {icon = "NONE", name = "Кентавры из племени Маграм", faction = "", other = "World of Warcraft", },
	[2503] = {icon = "NONE", name = "Кентавры Маруук", faction = "", other = "Dragonflight", },
	[2504] = {icon = "NONE", name = "Кентавры Маруук (идеал)", faction = "", other = "Dragonflight", },
	[1090] = {icon = "NONE", name = "Кирин-Тор", faction = "", other = "Wrath of the Lich King", },
	[1337] = {icon = "NONE", name = "Клакси", faction = "", other = "Mists of Pandaria", },
	[2512] = {icon = "NONE", name = "Клан Айлааг", faction = "", other = "Кентавры Маруук", },
	[1708] = {icon = "NONE", name = "Клан Веселого Черепа", faction = "", other = "Warlords of Draenor", },
	[1174] = {icon = "NONE", name = "Клан Громового Молота", faction = "", other = "Cataclysm", },
	[1172] = {icon = "NONE", name = "Клан Драконьей Пасти", faction = "", other = "Cataclysm", },
	[2555] = {icon = "NONE", name = "Клан Кейган", faction = "", other = "Dragonflight", },
	[2521] = {icon = "NONE", name = "Клан Нокуд (идеал)", faction = "", other = "Dragonflight", },
	[2520] = {icon = "NONE", name = "Клан Нокхуд", faction = "", other = "Dragonflight", },
	[2513] = {icon = "NONE", name = "Клан Он'ир", faction = "", other = "Кентавры Маруук", },
	[1445] = {icon = "NONE", name = "Клан Северного Волка", faction = "", other = "Warlords of Draenor", },
	[2522] = {icon = "NONE", name = "Клан Тирай", faction = "", other = "Кентавры Маруук", },
	[2554] = {icon = "NONE", name = "Клан Тогус", faction = "", other = "Кентавры Маруук", },
	[2542] = {icon = "NONE", name = "Клан Укхел", faction = "", other = "Dragonflight", },
	[2509] = {icon = "NONE", name = "Клан Шикаар", faction = "", other = "Кентавры Маруук", },
	[2458] = {icon = "NONE", name = "Клейя и Пелагий", faction = "", other = "Пепельный двор", },
	[2400] = {icon = "NONE", name = "Клинки Волн", faction = "", other = "Battle for Azeroth", },
	[2550] = {icon = "NONE", name = "Кобальтовая ассамблея", faction = "", other = "Союз Вальдраккена", },
	[2472] = {icon = "NONE", name = "Кодекс архивариуса", faction = "", other = "Темные Земли", },
	[2473] = {icon = "NONE", name = "Кодекс архивариуса (идеал)", faction = "", other = "Темные Земли", },
	[2593] = {icon = "NONE", name = "Команда Бочконога", faction = "", other = "Другое", },
	[2604] = {icon = "NONE", name = "Команда Бочконога (идеал)", faction = "", other = "Другое", },
	[933] = {icon = "NONE", name = "Консорциум", faction = "", other = "The Burning Crusade", },
	[2544] = {icon = "NONE", name = "Консорциум ремесленников – филиал на Драконьих островах", faction = "", other = "Союз Вальдраккена", },
	[1681] = {icon = "NONE", name = "Копье Вол'джина", faction = "", other = "Силы Орды", },
	[2100] = {icon = 236575, name = "Корбин", faction = "", other = "Legion", },
	[609] = {icon = "NONE", name = "Круг Кенария", faction = "", other = "World of Warcraft", },
	[577] = {icon = "NONE", name = "Круговзор", faction = "", other = "Картель Хитрой Шестеренки", },
	[1015] = {icon = "NONE", name = "Крылья Пустоты", faction = "", other = "The Burning Crusade", },
	[1975] = {icon = "NONE", name = "Кудесник Маргосс", faction = "", other = "Legion", },
	[2265] = {icon = "NONE", name = "Кул-Тирас - долина Штормов", faction = "", other = "Орден Возрождения Шторма", },
	[2264] = {icon = "NONE", name = "Кул-Тирас - Друствар", faction = "", other = "Орден Пылающих Углей", },
	[2120] = {icon = "NONE", name = "Кул-Тирас - Тирагард", faction = E.Icon_Alliance, other = "Адмиралтейство Праудмуров", },
	[978] = {icon = "NONE", name = "Куренай", faction = "", other = "The Burning Crusade", },
	[2470] = {icon = "NONE", name = "Легион Смерти", faction = "", other = "Темные Земли", },
	[2471] = {icon = "NONE", name = "Легион Смерти (идеал)", faction = "", other = "Темные Земли", },
	[2447] = {icon = "NONE", name = "Леди Лунная Ягода", faction = "", other = "Пепельный двор", },
	[1741] = {icon = "NONE", name = "Леорадж", faction = "", other = "Телохранители из казарм", },
	[1228] = {icon = "NONE", name = "Лесные хозены", faction = "", other = "Mists of Pandaria", },
	[509] = {icon = "NONE", name = "Лига Аратора", faction = "", other = "Силы Альянса", },
	[1068] = {icon = "NONE", name = "Лига исследователей", faction = E.Icon_Alliance, other = "Авангард Альянса", },
	[2564] = {icon = "NONE", name = "Лоаммские ниффы", faction = "", other = "Dragonflight", },
	[2565] = {icon = "NONE", name = "Лоаммские ниффы (идеал)", faction = "", other = "Dragonflight", },
	[1899] = {icon = "NONE", name = "Лунные стражи", faction = "", other = "Legion", },
	[1989] = {icon = "NONE", name = "Лунные стражи", faction = "", other = "Legion", },
	[911] = {icon = "NONE", name = "Луносвет", faction = E.Icon_Horde, other = "Орда", },
	[941] = {icon = "NONE", name = "Маг'хары", faction = E.Icon_Horde, other = "The Burning Crusade", },
	[2377] = {icon = "NONE", name = "Мастер клинка Иновари", faction = "", other = "Battle for Azeroth", },
	[2375] = {icon = "NONE", name = "Мастер охоты Акана", faction = "", other = "Battle for Azeroth", },
	[2448] = {icon = "NONE", name = "Миканикос", faction = "", other = "Пепельный двор", },
	[2427] = {icon = "NONE", name = "Молодой акир", faction = "", other = "Battle for Azeroth", },
	[1358] = {icon = "NONE", name = "Нат Пэгл", faction = "", other = "Рыболовы", },
	[1435] = {icon = "NONE", name = "Натиск Шадо-Пан", faction = "", other = "Mists of Pandaria", },
	[1341] = {icon = "NONE", name = "Небожители", faction = "", other = "Mists of Pandaria", },
	[2439] = {icon = "NONE", name = "Нераскаявшиеся", faction = "", other = "Темные Земли", },
	[2389] = {icon = "NONE", name = "Нери Остроерш", faction = "", other = "Battle for Azeroth", },
	[2410] = {icon = "NONE", name = "Неумирающая армия", faction = "", other = "Темные Земли", },
	[2440] = {icon = "NONE", name = "Неумирающая армия (Идеал)", faction = "", other = "Темные Земли", },
	[1011] = {icon = "NONE", name = "Нижний Город", faction = "", other = "Город Шаттрат", },
	[1117] = {icon = "NONE", name = "Низина Шолазар", faction = "", other = "Wrath of the Lich King", },
	[1357] = {icon = "NONE", name = "Номи", faction = "", other = "Другое", },
	[2422] = {icon = "NONE", name = "Ночной народец", faction = "", other = "Дикая Охота", },
	[2524] = {icon = "NONE", name = "Обсидиановые Хранители", faction = E.Icon_Alliance, other = "Альянс", },
	[2370] = {icon = "NONE", name = "Обучение динозавров – Дикорог", faction = "", other = "Battle for Azeroth", },
	[1038] = {icon = "NONE", name = "Огри'ла", faction = "", other = "The Burning Crusade", },
	[1376] = {icon = "NONE", name = "Операция \"Заслон\"", faction = "", other = "Mists of Pandaria", },
	[946] = {icon = "NONE", name = "Оплот Чести", faction = "", other = "The Burning Crusade", },
	[2376] = {icon = "NONE", name = "Оракул Ори", faction = "", other = "Battle for Azeroth", },
	[1105] = {icon = "NONE", name = "Оракулы", faction = "", other = "Низина Шолазар", },
	[76] = {icon = "NONE", name = "Оргриммар", faction = E.Icon_Horde, other = "Орда", },
	[67] = {icon = "NONE", name = "Орда", faction = E.Icon_Horde, other = "World of Warcraft", },
	[2162] = {icon = "NONE", name = "Орден Возрождения Шторма", faction = "", other = "Battle for Azeroth", },
	[2381] = {icon = "NONE", name = "Орден Возрождения Шторма (идеал)", faction = "", other = "Battle for Azeroth", },
	[1271] = {icon = "NONE", name = "Орден Облачного Змея", faction = "", other = "Mists of Pandaria", },
	[1849] = {icon = "NONE", name = "Орден Пробудившихся", faction = "", other = "Warlords of Draenor", },
	[2161] = {icon = "NONE", name = "Орден Пылающих Углей", faction = "", other = "Battle for Azeroth", },
	[2383] = {icon = "NONE", name = "Орден Пылающих Углей (идеал)", faction = "", other = "Battle for Azeroth", },
	[2373] = {icon = "NONE", name = "Освобожденные", faction = "", other = "Battle for Azeroth", },
	[2374] = {icon = "NONE", name = "Освобожденные (идеал)", faction = "", other = "Battle for Azeroth", },
	[510] = {icon = "NONE", name = "Осквернители", faction = "", other = "Силы Орды", },
	[2018] = {icon = "NONE", name = "Отмщение Когтя", faction = "", other = "Legion", },
	[2600] = {icon = "NONE", name = "Отрезанные нити", faction = "", other = "The War Within", },
	[2596] = {icon = "NONE", name = "Отрезанные нити (идеал)", faction = "", other = "The War Within", },
	[1848] = {icon = "NONE", name = "Охотники за головами", faction = "", other = "Warlords of Draenor", },
	[1850] = {icon = "NONE", name = "Охотники за саблеронами", faction = "", other = "Warlords of Draenor", },
	[1353] = {icon = "NONE", name = "Пандарены Тушуй", faction = E.Icon_Alliance, other = "Альянс", },
	[1352] = {icon = "NONE", name = "Пандарены Хоцзинь", faction = E.Icon_Horde, other = "Орда", },
	[2445] = {icon = "NONE", name = "Пепельный двор", faction = "", other = "Темные Земли", },
	[1156] = {icon = "NONE", name = "Пепельный союз", faction = "", other = "Wrath of the Lich King", },
	[1012] = {icon = "NONE", name = "Пеплоусты-служители", faction = "", other = "The Burning Crusade", },
	[2407] = {icon = "NONE", name = "Перерожденные", faction = "", other = "Темные Земли", },
	[2441] = {icon = "NONE", name = "Перерожденные (Идеал)", faction = "", other = "Темные Земли", },
	[990] = {icon = "NONE", name = "Песчаная Чешуя", faction = "", other = "The Burning Crusade", },
	[21] = {icon = "NONE", name = "Пиратская Бухта", faction = "", other = "Картель Хитрой Шестеренки", },
	[87] = {icon = "NONE", name = "Пираты Кровавого Паруса", faction = "", other = "World of Warcraft", },
	[1828] = {icon = "NONE", name = "Племена Крутогорья", faction = "", other = "Legion", },
	[2085] = {icon = "NONE", name = "Племена Крутогорья (идеал)", faction = "", other = "Legion", },
	[1104] = {icon = "NONE", name = "Племя Бешеного Сердца", faction = "", other = "Низина Шолазар", },
	[270] = {icon = "NONE", name = "Племя Зандалари", faction = "", other = "World of Warcraft", },
	[530] = {icon = "NONE", name = "Племя Черного Копья", faction = E.Icon_Horde, other = "Орда", },
	[68] = {icon = "NONE", name = "Подгород", faction = E.Icon_Horde, other = "Орда", },
	[2452] = {icon = "NONE", name = "Полемарх Адрест", faction = "", other = "Пепельный двор", },
	[1859] = {icon = "NONE", name = "Помраченные", faction = "", other = "Legion", }, -- E.Icon_Horde
	[2089] = {icon = "NONE", name = "Помраченные (идеал)", faction = "", other = "Legion", },
	[2469] = {icon = "NONE", name = "Понимание фракталов", faction = "", other = "Темные Земли", },
	[2371] = {icon = "NONE", name = "Потасовочная \"У Бизмо\"", faction = "", other = "Силы Альянса", },
	[2011] = {icon = "NONE", name = "Потасовочная \"У Бизмо\" (3-й сезон)", faction = "", other = "Силы Альянса", },
	[1419] = {icon = "NONE", name = "Потасовочная \"У Бизмо\" (сезон 1)", faction = "", other = "Силы Альянса", },
	[1691] = {icon = "NONE", name = "Потасовочная \"У Бизмо\" (сезон 2)", faction = "", other = "Силы Альянса", },
	[1124] = {icon = "NONE", name = "Похитители Солнца", faction = E.Icon_Horde, other = "Экспедиция Орды", },
	[2388] = {icon = "NONE", name = "Поэн Солежабрик", faction = "", other = "Battle for Azeroth", },
	[369] = {icon = "NONE", name = "Прибамбасск", faction = "", other = "Картель Хитрой Шестеренки", },
	[934] = {icon = "NONE", name = "Провидцы", faction = "", other = "Город Шаттрат", },
	[2478] = {icon = "NONE", name = "Просветленные", faction = "", other = "Темные Земли", },
	[2479] = {icon = "NONE", name = "Просветленные (идеал)", faction = "", other = "Темные Земли", },
	[2601] = {icon = "NONE", name = "Прядильщица", faction = "", other = "Отрезанные нити", },
	[2648] = {icon = "NONE", name = "Прядильщица (идеал)", faction = "", other = "Отрезанные нити", },
	[2397] = {icon = "NONE", name = "Пчеломатка улья Медокрылов", faction = "", other = "Другое", },
	[2415] = {icon = "NONE", name = "Раджани", faction = "", other = "Battle for Azeroth", },
	[2416] = {icon = "NONE", name = "Раджани (идеал)", faction = "", other = "Battle for Azeroth", },
	[1173] = {icon = "NONE", name = "Рамкахены", faction = "", other = "Cataclysm", },
	[2453] = {icon = "NONE", name = "Рендл и Дуборыл", faction = "", other = "Пепельный двор", },
	[2391] = {icon = "NONE", name = "Ржавоболтское сопротивление", faction = "", other = "Battle for Azeroth", },
	[2392] = {icon = "NONE", name = "Ржавоболтское сопротивление (идеал)", faction = "", other = "Battle for Azeroth", },
	[910] = {icon = "NONE", name = "Род Ноздорму", faction = "", other = "World of Warcraft", },
	[1282] = {icon = "NONE", name = "Рыба Тростниковая Шкура", faction = "", other = "Земледельцы", },
	[1302] = {icon = "NONE", name = "Рыболовы", faction = "", other = "Mists of Pandaria", },
	[1098] = {icon = "NONE", name = "Рыцари Черного Клинка", faction = "", other = "Wrath of the Lich King", },
	[2518] = {icon = "NONE", name = "Сабеллиан", faction = "", other = "Союз Вальдраккена", },
	[1106] = {icon = "NONE", name = "Серебряный Авангард", faction = "", other = "Wrath of the Lich King", },
	[529] = {icon = "NONE", name = "Серебряный Рассвет", faction = "", other = "World of Warcraft", },
	[1094] = {icon = "NONE", name = "Серебряный Союз", faction = E.Icon_Alliance, other = "Авангард Альянса", },
	[2459] = {icon = "NONE", name = "Сика", faction = "", other = "Пепельный двор", },
	[891] = {icon = "NONE", name = "Силы Альянса", faction = E.Icon_Alliance, other = "World of Warcraft", },
	[892] = {icon = "NONE", name = "Силы Орды", faction = "", other = "World of Warcraft", },
	[70] = {icon = "NONE", name = "Синдикат", faction = "", other = "World of Warcraft", },
	[1135] = {icon = "NONE", name = "Служители Земли", faction = "", other = "Cataclysm", },
	[2590] = {icon = "NONE", name = "Совет Дорногала", faction = "", other = "The War Within", },
	[2612] = {icon = "NONE", name = "Совет Дорногала (идеал)", faction = "", other = "The War Within", },
	[1731] = {icon = "NONE", name = "Совет экзархов", faction = "", other = "Warlords of Draenor", },
	[2553] = {icon = "NONE", name = "Соридорми", faction = "", other = "Союз Вальдраккена", },
	[2510] = {icon = "NONE", name = "Союз Вальдраккена", faction = "", other = "Dragonflight", },
	[2552] = {icon = "NONE", name = "Союз Вальдраккена (идеал)", faction = "", other = "Dragonflight", },
	[1984] = {icon = "NONE", name = "Спасатели", faction = "", other = "Legion", },
	[970] = {icon = "NONE", name = "Спореггар", faction = "", other = "The Burning Crusade", },
	[890] = {icon = "NONE", name = "Среброкрылые Часовые", faction = "", other = "Силы Альянса", },
	[47] = {icon = "NONE", name = "Стальгорн", faction = E.Icon_Alliance, other = "Альянс", },
	[1276] = {icon = "NONE", name = "Старик Горная Лапа", faction = "", other = "Земледельцы", },
	[730] = {icon = "NONE", name = "Стража Грозовой Вершины", faction = E.Icon_Alliance, other = "Силы Альянса", },
	[1894] = {icon = "NONE", name = "Стражи", faction = "", other = "Legion", },
	[2090] = {icon = "NONE", name = "Стражи (идеал)", faction = "", other = "Legion", },
	[1031] = {icon = "NONE", name = "Стражи небес Ша'тар", faction = "", other = "Город Шаттрат", },
	[2574] = {icon = "NONE", name = "Стражи Сна", faction = "", other = "Dragonflight", },
	[2575] = {icon = "NONE", name = "Стражи Сна (идеал)", faction = "", other = "Dragonflight", },
	[1158] = {icon = "NONE", name = "Стражи Хиджала", faction = "", other = "Cataclysm", },
	[1119] = {icon = "NONE", name = "Сыны Ходира", faction = "", other = "Wrath of the Lich King", },
	[1064] = {icon = "NONE", name = "Таунка", faction = E.Icon_Horde, other = "Экспедиция Орды", },
	[1735] = {icon = "NONE", name = "Телохранители из казарм", faction = "", other = "Warlords of Draenor", },
	[2414] = {icon = "NONE", name = "Темные Земли", faction = "", other = "Другое", },
	[2523] = {icon = "NONE", name = "Темные Когти", faction = E.Icon_Horde, other = "Орда", },
	[1171] = {icon = "NONE", name = "Теразан", faction = "", other = "Cataclysm", },
	[949] = {icon = "NONE", name = "Тестовая фракция 1", faction = "", other = "Другое", },
	[948] = {icon = "NONE", name = "Тестовая фракция 2", faction = "", other = "Тестовая фракция 1", },
	[1280] = {icon = "NONE", name = "Тина Грязный Коготь", faction = "", other = "Земледельцы", },
	[1883] = {icon = "NONE", name = "Ткачи Снов", faction = "", other = "Legion", },
	[2088] = {icon = "NONE", name = "Ткачи Снов (идеал)", faction = "", other = "Legion", },
	[1736] = {icon = "NONE", name = "Тормок", faction = "", other = "Телохранители из казарм", },
	[2163] = {icon = "NONE", name = "Тортолланские искатели", faction = "", other = "Battle for Azeroth", },
	[2387] = {icon = "NONE", name = "Тортолланские искатели (идеал)", faction = "", other = "Battle for Azeroth", },
	[947] = {icon = "NONE", name = "Траллмар", faction = "", other = "The Burning Crusade", },
	[922] = {icon = "NONE", name = "Транквиллион", faction = "", other = "The Burning Crusade", },
	[2396] = {icon = "NONE", name = "Трутень из улья Медокрылов", faction = "", other = "Другое", },
	[589] = {icon = "NONE", name = "Укротители ледопардов", faction = "", other = "World of Warcraft", },
	[2395] = {icon = "NONE", name = "Улей Медокрылов", faction = "", other = "Battle for Azeroth", },
	[2417] = {icon = "NONE", name = "Ульдумский союз", faction = "", other = "Battle for Azeroth", },
	[2418] = {icon = "NONE", name = "Ульдумский союз (идеал)", faction = "", other = "Battle for Azeroth", },
	[1283] = {icon = "NONE", name = "Фермер Фун", faction = "", other = "Земледельцы", },
	[2398] = {icon = "NONE", name = "Фуражир из улья Медокрылов", faction = "", other = "Другое", },
	[2526] = {icon = "NONE", name = "Фурболги из клана Зимней Шкуры", faction = "", other = "Dragonflight", },
	[1279] = {icon = "NONE", name = "Хаохань Грязный Коготь", faction = "", other = "Земледельцы", },
	[1204] = {icon = "NONE", name = "Хиджальские мстители", faction = "", other = "Cataclysm", },
	[1351] = {icon = "NONE", name = "Хмелевары", faction = "", other = "Mists of Pandaria", },
	[989] = {icon = "NONE", name = "Хранители Времени", faction = "", other = "The Burning Crusade", },
	[1345] = {icon = "NONE", name = "Хранители истории", faction = "", other = "Mists of Pandaria", },
	[2455] = {icon = "NONE", name = "Хранитель склепа Каззир", faction = "", other = "Пепельный двор", },
	[2098] = {icon = 236575, name = "Хранительница Рейна", faction = "", other = "Legion", },
	[2135] = {icon = "NONE", name = "Хроми", faction = "", other = "Legion", },
	[1242] = {icon = "NONE", name = "Цзинь-юй Жемчужного Плавника", faction = "", other = "Mists of Pandaria", },
	[349] = {icon = "NONE", name = "Черный Ворон", faction = "", other = "World of Warcraft", },
	[1359] = {icon = "NONE", name = "Черный принц", faction = "", other = "Mists of Pandaria", },
	[2463] = {icon = "NONE", name = "Чесночник", faction = "", other = "Темные Земли", },
	[1277] = {icon = "NONE", name = "Чи-Чи", faction = "", other = "Земледельцы", },
	[2454] = {icon = "NONE", name = "Чуфа", faction = "", other = "Пепельный двор", },
	[2101] = {icon = 236575, name = "Ша'лет", faction = "", other = "Legion", },
	[935] = {icon = "NONE", name = "Ша'тар", faction = "", other = "Город Шаттрат", },
	[1270] = {icon = "NONE", name = "Шадо-Пан", faction = "", other = "Mists of Pandaria", },
	[809] = {icon = "NONE", name = "Шен'дралар", faction = "", other = "World of Warcraft", },
	[1278] = {icon = "NONE", name = "Шо", faction = "", other = "Земледельцы", },
	[2462] = {icon = "NONE", name = "Штопальщики", faction = "", other = "Темные Земли", },
	[72] = {icon = "NONE", name = "Штормград", faction = E.Icon_Alliance, other = "Альянс", },
	[930] = {icon = "NONE", name = "Экзодар", faction = E.Icon_Alliance, other = "Альянс", },
	[1052] = {icon = "NONE", name = "Экспедиция Орды", faction = "", other = "Wrath of the Lich King", },
	[1050] = {icon = "NONE", name = "Экспедиция Отважных", faction = E.Icon_Alliance, other = "Авангард Альянса", },
	[2156] = {icon = "NONE", name = "Экспедиция Таланджи", faction = "", other = "Battle for Azeroth", },
	[2380] = {icon = "NONE", name = "Экспедиция Таланджи (идеал)", faction = "", other = "Battle for Azeroth", },
	[1275] = {icon = "NONE", name = "Элла", faction = "", other = "Земледельцы", },
	[1888] = {icon = "NONE", name = "Яндвикские врайкулы", faction = "", other = "Legion", },
	[909] = {icon = "NONE", name = "Ярмарка Новолуния", faction = "", other = "World of Warcraft", },
	-- [2693] = {icon = "NONE", name = "Delver's Journey (Season 1)", faction = "", other = "The War Within", },
	[2693] = {icon = "NONE", name = "Путь участника вылазки (1-й сезон)", faction = "", other = "The War Within", },



}
