local  tbl  = {



    [2669] = {expansion = "TWW",},
    [2685] = {expansion = "TWW",},
    [2677] = {expansion = "TWW",},
    [2675] = {expansion = "TWW",},
    [2673] = {expansion = "TWW",},
    [2671] = {expansion = "TWW",},
    [2653] = {expansion = "TWW",},
    [2570] = {expansion = "TWW",},
    [2594] = {expansion = "TWW",},
    [2601] = {expansion = "TWW",},
    [2590] = {expansion = "TWW",},
    [2600] = {expansion = "TWW",},
    [2640] = {expansion = "TWW",},
    [2607] = {expansion = "TWW",},
    [2605] = {expansion = "TWW",},
    [2668] = {expansion = "TWW",},
    [2684] = {expansion = "TWW",},
    [2645] = {expansion = "TWW",},
    [2693] = {expansion = "TWW",},
    [2667] = {expansion = "TWW",},
    [2674] = {expansion = "TWW",},
    [2683] = {expansion = "TWW",},
    [2676] = {expansion = "TWW",},
    [2611] = {expansion = "TWW",},
    [2613] = {expansion = "TWW",},
    [2672] = {expansion = "TWW",},
    [2670] = {expansion = "TWW",},
    [2647] = {expansion = "TWW",},
    [2612] = {expansion = "TWW",},
    [2644] = {expansion = "TWW",},
    [2596] = {expansion = "TWW",},
    [2648] = {expansion = "TWW",},
    [2649] = {expansion = "TWW",},



    [2511] = {expansion = "Dragonflight",},
    [2553] = {expansion = "Dragonflight",},
    [2507] = {expansion = "Dragonflight",},
    [2526] = {expansion = "Dragonflight",},
    [2503] = {expansion = "Dragonflight",},
    [2510] = {expansion = "Dragonflight",},
    [2564] = {expansion = "Dragonflight",},
    [2550] = {expansion = "Dragonflight",},
    [2574] = {expansion = "Dragonflight",},
    [2518] = {expansion = "Dragonflight",},
    [2544] = {expansion = "Dragonflight",},
    [2568] = {expansion = "Dragonflight",},
    [2615] = {expansion = "Dragonflight",},
    [2517] = {expansion = "Dragonflight",},
    [2513] = {expansion = "Dragonflight",},
    [2542] = {expansion = "Dragonflight",},
    [2521] = {expansion = "Dragonflight",},
    [2520] = {expansion = "Dragonflight",},
    [1072] = {expansion = "Dragonflight",},
    [2555] = {expansion = "Dragonflight",},
    [2509] = {expansion = "Dragonflight",},
    [2551] = {expansion = "Dragonflight",},
    [2565] = {expansion = "Dragonflight",},
    [2504] = {expansion = "Dragonflight",},
    [2554] = {expansion = "Dragonflight",},
    [2575] = {expansion = "Dragonflight",},
    [2508] = {expansion = "Dragonflight",},
    [2512] = {expansion = "Dragonflight",},
    [2552] = {expansion = "Dragonflight",},
    [2522] = {expansion = "Dragonflight",},




    [2463] = {expansion = "Shadowlands",},
    [2439] = {expansion = "Shadowlands",},
    [2464] = {expansion = "Shadowlands",},
    [2465] = {expansion = "Shadowlands",},
    [2445] = {expansion = "Shadowlands",},
    [2478] = {expansion = "Shadowlands",},
    [2407] = {expansion = "Shadowlands",},
    [2413] = {expansion = "Shadowlands",},
    [2470] = {expansion = "Shadowlands",},
    [2472] = {expansion = "Shadowlands",},
    [2410] = {expansion = "Shadowlands",},
    [2462] = {expansion = "Shadowlands",},
    [2446] = {expansion = "Shadowlands",},
    [2432] = {expansion = "Shadowlands",},
    [2422] = {expansion = "Shadowlands",},
    [2460] = {expansion = "Shadowlands",},
    [2449] = {expansion = "Shadowlands",},
    [2453] = {expansion = "Shadowlands",},
    [2454] = {expansion = "Shadowlands",},
    [2444] = {expansion = "Shadowlands",},
    [2458] = {expansion = "Shadowlands",},
    [2450] = {expansion = "Shadowlands",},
    [2469] = {expansion = "Shadowlands",},
    [2455] = {expansion = "Shadowlands",},
    [2456] = {expansion = "Shadowlands",},
    [2448] = {expansion = "Shadowlands",},
    [2440] = {expansion = "Shadowlands",},
    [2457] = {expansion = "Shadowlands",},
    [2459] = {expansion = "Shadowlands",},
    [2451] = {expansion = "Shadowlands",},
    [2447] = {expansion = "Shadowlands",},
    [2471] = {expansion = "Shadowlands",},
    [2452] = {expansion = "Shadowlands",},
    [2474] = {expansion = "Shadowlands",},
    [2461] = {expansion = "Shadowlands",},
    [2479] = {expansion = "Shadowlands",},
    [2442] = {expansion = "Shadowlands",},
    [2473] = {expansion = "Shadowlands",},
    [2441] = {expansion = "Shadowlands",},



    [2415] = {expansion = "BFA",},
    [2164] = {expansion = "BFA",},
    [2162] = {expansion = "BFA",},
    [2103] = {expansion = "BFA",},
    [2160] = {expansion = "BFA",},
    [2157] = {expansion = "BFA",},
    [2161] = {expansion = "BFA",},
    [2391] = {expansion = "BFA",},
    [2159] = {expansion = "BFA",},
    [2163] = {expansion = "BFA",},
    [2158] = {expansion = "BFA",},
    [2400] = {expansion = "BFA",},
    [2373] = {expansion = "BFA",},
    [2417] = {expansion = "BFA",},
    [2395] = {expansion = "BFA",},
    [2156] = {expansion = "BFA",},
    [2427] = {expansion = "BFA",},
    [2377] = {expansion = "BFA",},
    [2389] = {expansion = "BFA",},
    [2376] = {expansion = "BFA",},
    [2392] = {expansion = "BFA",},
    [2385] = {expansion = "BFA",},
    [2386] = {expansion = "BFA",},
    [2382] = {expansion = "BFA",},
    [2233] = {expansion = "BFA",},
    [2381] = {expansion = "BFA",},
    [2111] = {expansion = "BFA",},
    [2370] = {expansion = "BFA",},
    [2375] = {expansion = "BFA",},
    [2265] = {expansion = "BFA",},
    [2374] = {expansion = "BFA",},
    [2418] = {expansion = "BFA",},
    [2383] = {expansion = "BFA",},
    [2379] = {expansion = "BFA",},
    [2390] = {expansion = "BFA",},
    [2401] = {expansion = "BFA",},
    [2384] = {expansion = "BFA",},
    [2416] = {expansion = "BFA",},
    [2387] = {expansion = "BFA",},
    [2264] = {expansion = "BFA",},
    [2378] = {expansion = "BFA",},
    [2120] = {expansion = "BFA",},
    [2388] = {expansion = "BFA",},
    [2380] = {expansion = "BFA",},





    [1859] = {expansion = "Legion",},
    [1975] = {expansion = "Legion",},
    [2165] = {expansion = "Legion",},
    [1948] = {expansion = "Legion",},
    [1883] = {expansion = "Legion",},
    [1900] = {expansion = "Legion",},
    [2018] = {expansion = "Legion",},
    [2098] = {expansion = "Legion",},
    [2045] = {expansion = "Legion",},
    [2097] = {expansion = "Legion",},
    [1894] = {expansion = "Legion",},
    [1828] = {expansion = "Legion",},
    [2102] = {expansion = "Legion",},
    [2101] = {expansion = "Legion",},
    [2170] = {expansion = "Legion",},
    [2135] = {expansion = "Legion",},
    [2099] = {expansion = "Legion",},
    [2100] = {expansion = "Legion",},
    [2087] = {expansion = "Legion",},
    [1947] = {expansion = "Legion",},
    [2166] = {expansion = "Legion",},
    [2085] = {expansion = "Legion",},
    [1862] = {expansion = "Legion",},
    [2089] = {expansion = "Legion",},
    [2086] = {expansion = "Legion",},
    [1815] = {expansion = "Legion",},
    [1989] = {expansion = "Legion",},
    [1899] = {expansion = "Legion",},
    [1984] = {expansion = "Legion",},
    [1860] = {expansion = "Legion",},
    [1888] = {expansion = "Legion",},
    [2090] = {expansion = "Legion",},
    [1919] = {expansion = "Legion",},
    [1861] = {expansion = "Legion",},
    [2091] = {expansion = "Legion",},
    [2088] = {expansion = "Legion",},



    [1711] = {expansion = "Draenor",},
    [1445] = {expansion = "Draenor",},
    [1708] = {expansion = "Draenor",},
    [1849] = {expansion = "Draenor",},
    [1731] = {expansion = "Draenor",},
    [1847] = {expansion = "Draenor",},
    [1515] = {expansion = "Draenor",},
    [1710] = {expansion = "Draenor",},
    [1850] = {expansion = "Draenor",},
    [1848] = {expansion = "Draenor",},
    [1735] = {expansion = "Draenor",},
    [1733] = {expansion = "Draenor",},
    [1737] = {expansion = "Draenor",},
    [1741] = {expansion = "Draenor",},
    [1520] = {expansion = "Draenor",},
    [1739] = {expansion = "Draenor",},
    [1740] = {expansion = "Draenor",},
    [1732] = {expansion = "Draenor",},
    [1738] = {expansion = "Draenor",},
    [1736] = {expansion = "Draenor",},



    [1341] = {expansion = "panda",},
    [1302] = {expansion = "panda",},
    [1358] = {expansion = "panda",},
    [1271] = {expansion = "panda",},
    [1269] = {expansion = "panda",},
    [1270] = {expansion = "panda",},
    [1345] = {expansion = "panda",},
    [1272] = {expansion = "panda",},
    [1337] = {expansion = "panda",},
    [1359] = {expansion = "panda",},
    [1492] = {expansion = "panda",},
    [1435] = {expansion = "panda",},
    [1387] = {expansion = "panda",},
    [1242] = {expansion = "panda",},
    [1375] = {expansion = "panda",},
    [1376] = {expansion = "panda",},
    [1388] = {expansion = "panda",},
    [1228] = {expansion = "panda",},
    [1216] = {expansion = "panda",},
    [1278] = {expansion = "panda",},
    [1276] = {expansion = "panda",},
    [1280] = {expansion = "panda",},
    [1282] = {expansion = "panda",},
    [1281] = {expansion = "panda",},
    [1275] = {expansion = "panda",},
    [1277] = {expansion = "panda",},
    [1440] = {expansion = "panda",},
    [1283] = {expansion = "panda",},
    [1279] = {expansion = "panda",},
    [1273] = {expansion = "panda",},
    [1351] = {expansion = "panda",},


    [1204] = {expansion = "Cataclysm",},
    [1171] = {expansion = "Cataclysm",},
    [1135] = {expansion = "Cataclysm",},
    [1173] = {expansion = "Cataclysm",},
    [1174] = {expansion = "Cataclysm",},
    [1172] = {expansion = "Cataclysm",},
    [1158] = {expansion = "Cataclysm",},
    [1177] = {expansion = "Cataclysm",},
    [1178] = {expansion = "Cataclysm",},


    [1073] = {expansion = "WOTLK",},
    [1105] = {expansion = "WOTLK",},
    [1106] = {expansion = "WOTLK",},
    [1156] = {expansion = "WOTLK",},
    [1104] = {expansion = "WOTLK",},
    [1091] = {expansion = "WOTLK",},
    [1085] = {expansion = "WOTLK",},
    [1119] = {expansion = "WOTLK",},
    [1090] = {expansion = "WOTLK",},
    [1098] = {expansion = "WOTLK",},
    [1094] = {expansion = "WOTLK",},
    [1124] = {expansion = "WOTLK",},
    [1037] = {expansion = "WOTLK",},
    [1052] = {expansion = "WOTLK",},
    [1068] = {expansion = "WOTLK",},
    [1126] = {expansion = "WOTLK",},
    [1067] = {expansion = "WOTLK",},
    [1064] = {expansion = "WOTLK",},
    [1050] = {expansion = "WOTLK",},
    [1117] = {expansion = "WOTLK",},



    [1015] = {expansion = "BC",},
    [932] = {expansion = "BC",},
    [990] = {expansion = "BC",},
    [942] = {expansion = "BC",},
    [933] = {expansion = "BC",},
    [967] = {expansion = "BC",},
    [1031] = {expansion = "BC",},
    [978] = {expansion = "BC",},
    [1011] = {expansion = "BC",},
    [1077] = {expansion = "BC",},
    [970] = {expansion = "BC",},
    [935] = {expansion = "BC",},
    [946] = {expansion = "BC",},
    [934] = {expansion = "BC",},
    [989] = {expansion = "BC",},
    [1038] = {expansion = "BC",},
    [941] = {expansion = "BC",},
    [1012] = {expansion = "BC",},
    [922] = {expansion = "BC",},
    [947] = {expansion = "BC",},
    [936] = {expansion = "BC",},




    [529] = {expansion = "Classic",},
    [21] = {expansion = "Classic",},
    [1133] = {expansion = "Classic",},
    [349] = {expansion = "Classic",},
    [87] = {expansion = "Classic",},
    [749] = {expansion = "Classic",},
    [576] = {expansion = "Classic",},
    [169] = {expansion = "Classic",},
    [470] = {expansion = "Classic",},
    [910] = {expansion = "Classic",},
    [909] = {expansion = "Classic",},
    [369] = {expansion = "Classic",},
    [609] = {expansion = "Classic",},
    [2524] = {expansion = "Classic",},
    [730] = {expansion = "Classic",},
    [59] = {expansion = "Classic",},
    [70] = {expansion = "Classic",},
    [577] = {expansion = "Classic",},
    [2523] = {expansion = "Classic",},
    [530] = {expansion = "Classic",},
    [509] = {expansion = "Classic",},
    [72] = {expansion = "Classic",},
    [930] = {expansion = "Classic",},
    [1134] = {expansion = "Classic",},
    [68] = {expansion = "Classic",},
    [911] = {expansion = "Classic",},
    [93] = {expansion = "Classic",},
    [589] = {expansion = "Classic",},
    [729] = {expansion = "Classic",},
    [890] = {expansion = "Classic",},
    [76] = {expansion = "Classic",},
    [809] = {expansion = "Classic",},
    [510] = {expansion = "Classic",},
    [92] = {expansion = "Classic",},
    [1352] = {expansion = "Classic",},
    [81] = {expansion = "Classic",},
    [1353] = {expansion = "Classic",},
    [69] = {expansion = "Classic",},
    [270] = {expansion = "Classic",},
    [54] = {expansion = "Classic",},
    [1681] = {expansion = "Classic",},
    [47] = {expansion = "Classic",},
    [1682] = {expansion = "Classic",},
    [889] = {expansion = "Classic",},
    [1419] = {expansion = "Classic",},
    [469] = {expansion = "Classic",},
    [1374] = {expansion = "Classic",},
    [2372] = {expansion = "Classic",},
    [67] = {expansion = "Classic",},
    [2371] = {expansion = "Classic",},
    [1691] = {expansion = "Classic",},
    [2010] = {expansion = "Classic",},
    [891] = {expansion = "Classic",},
    [2695] = {expansion = "Classic",},
    [892] = {expansion = "Classic",},
    [2011] = {expansion = "Classic",},
    [1690] = {expansion = "Classic",},

















}

