local GlobalAddonName, E = ...
----------------------------------------------------------------
E.list = {
	["HUNTER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Beast Mastery",
			["iconPath"] = "Interface/Icons/ABILITY_HUNTER_BESTIALDISCIPLINE",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 461112,
			["id"] = 253,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Marksmanship",
			["iconPath"] = "Interface/Icons/Ability_Hunter_FocusedAim",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 236179,
			["id"] = 254,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Survival",
			["iconPath"] = "Interface/Icons/Ability_Hunter_Camouflage",
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 461113,
			["id"] = 255,
		},
		["classId"] = 3,
	},
	["WARRIOR"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Arms",
			["iconPath"] = "Interface/Icons/Ability_Warrior_SavageBlow",
			["id"] = 71,
			["primaryStatString"] = "Strength",
			["icon"] = 132355,
			["primaryStat"] = 1,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Fury",
			["iconPath"] = "Interface/Icons/Ability_Warrior_InnerRage",
			["id"] = 72,
			["primaryStatString"] = "Strength",
			["icon"] = 132347,
			["primaryStat"] = 1,
		},
		{
			["role"] = "TANK",
			["name"] = "Protection",
			["iconPath"] = "Interface/Icons/Ability_Warrior_DefensiveStance",
			["id"] = 73,
			["primaryStatString"] = "Strength",
			["icon"] = 132341,
			["primaryStat"] = 1,
		},
		["classId"] = 1,
	},
	["SHAMAN"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Elemental",
			["primaryStat"] = 4,
			["id"] = 262,
			["primaryStatString"] = "Intellect",
			["icon"] = 136048,
			["iconPath"] = "Interface/Icons/Spell_Nature_Lightning",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Enhancement",
			["primaryStat"] = 2,
			["id"] = 263,
			["primaryStatString"] = "Agility",
			["icon"] = 237581,
			["iconPath"] = "Interface/Icons/Spell_Shaman_ImprovedStormstrike",
		},
		{
			["role"] = "HEALER",
			["name"] = "Restoration",
			["primaryStat"] = 4,
			["id"] = 264,
			["primaryStatString"] = "Intellect",
			["icon"] = 136052,
			["iconPath"] = "Interface/Icons/Spell_Nature_MagicImmunity",
		},
		["classId"] = 7,
	},
	["MAGE"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Arcane",
			["id"] = 62,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 135932,
			["iconPath"] = "Interface/Icons/Spell_Holy_MagicalSentry",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Fire",
			["id"] = 63,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 135810,
			["iconPath"] = "Interface/Icons/Spell_Fire_FireBolt02",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Frost",
			["id"] = 64,
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 135846,
			["iconPath"] = "Interface/Icons/Spell_Frost_FrostBolt02",
		},
		["classId"] = 8,
	},
	["PRIEST"] = {
		{
			["role"] = "HEALER",
			["name"] = "Discipline",
			["iconPath"] = "Interface/Icons/Spell_Holy_PowerWordShield",
			["id"] = 256,
			["primaryStatString"] = "Intellect",
			["icon"] = 135940,
			["primaryStat"] = 4,
		},
		{
			["role"] = "HEALER",
			["name"] = "Holy",
			["iconPath"] = "Interface/Icons/Spell_Holy_GuardianSpirit",
			["id"] = 257,
			["primaryStatString"] = "Intellect",
			["icon"] = 237542,
			["primaryStat"] = 4,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Shadow",
			["iconPath"] = "Interface/Icons/Spell_Shadow_ShadowWordPain",
			["id"] = 258,
			["primaryStatString"] = "Intellect",
			["icon"] = 136207,
			["primaryStat"] = 4,
		},
		["classId"] = 5,
	},
	["DEATHKNIGHT"] = {
		{
			["role"] = "TANK",
			["name"] = "Blood",
			["iconPath"] = "Interface/Icons/Spell_Deathknight_BloodPresence",
			["id"] = 250,
			["primaryStatString"] = "Strength",
			["icon"] = 135770,
			["primaryStat"] = 1,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Frost",
			["iconPath"] = "Interface/Icons/Spell_Deathknight_FrostPresence",
			["id"] = 251,
			["primaryStatString"] = "Strength",
			["icon"] = 135773,
			["primaryStat"] = 1,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Unholy",
			["iconPath"] = "Interface/Icons/Spell_Deathknight_UnholyPresence",
			["id"] = 252,
			["primaryStatString"] = "Strength",
			["icon"] = 135775,
			["primaryStat"] = 1,
		},
		["classId"] = 6,
	},
	["EVOKER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Devastation",
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Devastation",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 4511811,
			["id"] = 1467,
		},
		{
			["role"] = "HEALER",
			["name"] = "Preservation",
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Preservation",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 4511812,
			["id"] = 1468,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Augmentation",
			["iconPath"] = "Interface/Icons/ClassIcon_Evoker_Augmentation",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 5198700,
			["id"] = 1473,
		},
		["classId"] = 13,
	},
	["WARLOCK"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Affliction",
			["iconPath"] = "Interface/Icons/Spell_Shadow_DeathCoil",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136145,
			["id"] = 265,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Demonology",
			["iconPath"] = "Interface/Icons/Spell_Shadow_Metamorphosis",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136172,
			["id"] = 266,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Destruction",
			["iconPath"] = "Interface/Icons/Spell_Shadow_RainOfFire",
			["primaryStat"] = 4,
			["primaryStatString"] = "Intellect",
			["icon"] = 136186,
			["id"] = 267,
		},
		["classId"] = 9,
	},
	["DEMONHUNTER"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Havoc",
			["primaryStat"] = 2,
			["id"] = 577,
			["primaryStatString"] = "Agility",
			["icon"] = 1247264,
			["iconPath"] = "Interface/Icons/Ability_DemonHunter_SpecDPS",
		},
		{
			["role"] = "TANK",
			["name"] = "Vengeance",
			["primaryStat"] = 2,
			["id"] = 581,
			["primaryStatString"] = "Agility",
			["icon"] = 1247265,
			["iconPath"] = "Interface/Icons/Ability_DemonHunter_SpecTank",
		},
		["classId"] = 12,
	},
	["ROGUE"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Assassination",
			["id"] = 259,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 236270,
			["iconPath"] = "Interface/Icons/Ability_Rogue_DeadlyBrew",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Outlaw",
			["id"] = 260,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 236286,
			["iconPath"] = "Interface/Icons/Ability_Rogue_Waylay",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Subtlety",
			["id"] = 261,
			["primaryStat"] = 2,
			["primaryStatString"] = "Agility",
			["icon"] = 132320,
			["iconPath"] = "Interface/Icons/Ability_Stealth",
		},
		["classId"] = 4,
	},
	["DRUID"] = {
		{
			["role"] = "DAMAGER",
			["name"] = "Balance",
			["primaryStat"] = 4,
			["id"] = 102,
			["primaryStatString"] = "Intellect",
			["icon"] = 136096,
			["iconPath"] = "Interface/Icons/Spell_Nature_StarFall",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Feral",
			["primaryStat"] = 2,
			["id"] = 103,
			["primaryStatString"] = "Agility",
			["icon"] = 132115,
			["iconPath"] = "Interface/Icons/Ability_Druid_CatForm",
		},
		{
			["role"] = "TANK",
			["name"] = "Guardian",
			["primaryStat"] = 2,
			["id"] = 104,
			["primaryStatString"] = "Agility",
			["icon"] = 132276,
			["iconPath"] = "Interface/Icons/Ability_Racial_BearForm",
		},
		{
			["role"] = "HEALER",
			["name"] = "Restoration",
			["primaryStat"] = 4,
			["id"] = 105,
			["primaryStatString"] = "Intellect",
			["icon"] = 136041,
			["iconPath"] = "Interface/Icons/SPELL_NATURE_HEALINGTOUCH",
		},
		["classId"] = 11,
	},
	["MONK"] = {
		{
			["role"] = "TANK",
			["name"] = "Brewmaster",
			["iconPath"] = "Interface/Icons/Spell_Monk_Brewmaster_Spec",
			["id"] = 268,
			["primaryStatString"] = "Agility",
			["icon"] = 608951,
			["primaryStat"] = 2,
		},
		{
			["role"] = "HEALER",
			["name"] = "Mistweaver",
			["iconPath"] = "Interface/Icons/Spell_Monk_MistWeaver_Spec",
			["id"] = 270,
			["primaryStatString"] = "Intellect",
			["icon"] = 608952,
			["primaryStat"] = 4,
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Windwalker",
			["iconPath"] = "Interface/Icons/Spell_Monk_WindWalker_Spec",
			["id"] = 269,
			["primaryStatString"] = "Agility",
			["icon"] = 608953,
			["primaryStat"] = 2,
		},
		["classId"] = 10,
	},
	["PALADIN"] = {
		{
			["role"] = "HEALER",
			["name"] = "Holy",
			["primaryStat"] = 4,
			["id"] = 65,
			["primaryStatString"] = "Intellect",
			["icon"] = 135920,
			["iconPath"] = "Interface/Icons/Spell_Holy_HolyBolt",
		},
		{
			["role"] = "TANK",
			["name"] = "Protection",
			["primaryStat"] = 1,
			["id"] = 66,
			["primaryStatString"] = "Strength",
			["icon"] = 236264,
			["iconPath"] = "Interface/Icons/Ability_Paladin_ShieldoftheTemplar",
		},
		{
			["role"] = "DAMAGER",
			["name"] = "Retribution",
			["primaryStat"] = 1,
			["id"] = 70,
			["primaryStatString"] = "Strength",
			["icon"] = 135873,
			["iconPath"] = "Interface/Icons/Spell_Holy_AuraOfLight",
		},
		["classId"] = 2,
	},
}